//! Enable Background Dancers — revives the pre-World 3D background dancers:
//! during every gameplay song a randomly chosen A3 stage and randomly chosen
//! A3 dancer(s) animate behind the lane, rendered by the game's OWN model
//! passes from the character / stage / motion / camera arcs the stock World
//! install still ships but never opens.
//!
//! Architecture (design `.agents/planning/2026-09-16-enable-background-dancers/`):
//! World's engine kept the whole 3D pipeline (KTMDL loader, `MODEL:*` passes,
//! `agcs::scene::SceneGraph`, camera); Konami deleted only the game-side scene
//! layer. `services::scene3d` supplies that layer's engine contact points and
//! this mod supplies the game logic (selection, the A3 choreography/camera
//! rules, the per-song lifecycle). Zero rendering detours; nothing is patched.
//!
//! ## Shape (plan Steps 7–10)
//!
//! At the first entry into the song window {26, 27, 28} ([`lifecycle`]) a
//! seeded random pick ([`selection`], [`session::Pick`]) chooses one A3
//! stage row + one dancer per entered side (+ the accessory parts whose
//! arcs exist), applies the Background Movies mode to every entered side's
//! movie size for the song ([`movie_mode`], [`movie_size`]), hands the pick's arcs to
//! the engine's FileManager and parses them on one background thread
//! ([`session::parse_pick`] → `core::anm`: stage `_play_loop`s, dance
//! clips, the body `.b2it`, the part / shadow bone tables, the stage's
//! `.camanm` sets). Every resident model becomes a render item + scene node
//! (stage parts, bodies, parts, one `pl_shadow00` per dancer). The scene is
//! shown from the DancePlaySequence's step-5 edge (`song_reset::dps_step`)
//! and clocked by the content-domain music count ([`clock`]) turned into
//! DANCE TIME through the chart's tempo map ([`tempo`], sourced from the
//! song's SSQ by [`tempo_source`]: half a second of the 120-BPM clips per
//! chart beat, phase-pinned to the measure grid, 1/12 speed through STOPs —
//! the two A3 `ConfigBank` switches, both ON by default via the
//! `background_dancers` config section); every frame
//! the [`director`] evaluates each body once and publishes bodies, parts
//! (`E · bone · body`), shadows (the A3 ground-bone rule) and stage loops
//! onto the `scene3d::frame_board` the nodes copy from, and writes the
//! camera slot from the A3 stage-mode camera sequencing ([`schedule`] over
//! the shuffled main / `_non` camanm lists). [`background_hide`] makes the
//! 2D background transparent for the song. Torn down at window exit
//! (nodes → destroy vector → dtors → arcs; movie size + hide restored).
//! `DEFAULT_OFF_MODS`: the maintainer flips the default once cabinet-proven.
//!
//! ## Background movies (2026-09-22)
//!
//! GLOBAL SETTINGS row "Background Movies" (`background_dancers.movie_mode`,
//! next song) decides what a song with a background movie does, for every
//! entered player whose VIDEO SIZE shows one: OFF (VIDEO SIZE OFF for the
//! song + the shared BuildGraph suppressor; the stage as usual), THUMBNAIL
//! (the default and the original behaviour: the movie's small window over
//! the stage) or FULLSCREEN (NO STAGE) — the DDR 5th Mix look. The game
//! already draws a fullscreen movie into the 3D target ahead of the model
//! passes, so the last mode only has to leave the movie fullscreen and not
//! draw the stage: [`movie_backdrop`] probes the live DancePlaySequence's
//! MovieActor every frame, and while its movie really plays the stage parts
//! and floor shadows are published hidden and the camera director films the
//! dancers with the MOVIE camera set ([`movie_camera`]: loose `.camanm`
//! clips in `data_mods/background_dancers/movie_camera/`, generated by
//! `scripts/gen_movie_cameras.py` — close, front-facing shots; `_1p` / `_2p`
//! variants per dancer count) instead of the stage's own cameras. RE:
//! `docs/background_dancers_research.md` §7.
//!
//! ## Player choice (2026-09-21)
//!
//! Two in-game option rows under PLAYFIELD STYLING OPTIONS — BACKGROUND
//! DANCER (per player) and BACKGROUND STAGE (cabinet-wide, mirrored in
//! versus) — let a player pick a specific dancer / stage instead of RANDOM
//! ([`options`] over the sorted, labelled [`catalog`]; local persistence
//! only). The pick order at window entry is developer pin → option rows →
//! random (`selection::resolve_choice`); the per-song INFO names each
//! element's source.
//!
//! ## Custom dancers & stages (2026-09-22)
//!
//! With `background_dancers.custom_content` on (GLOBAL SETTINGS row "Custom
//! Dancers & Stages", default ON, next launch) the tables also carry the
//! community content under the ONE custom-models base
//! (`data_mods/custom_models/dancers/<Friendly Name>/pl_<key>.arc`,
//! `data_mods/custom_models/stages/<Friendly Name>/mapset_<key>.arc`, optional
//! sidecar rlists beside them — [`custom_content`] plans, [`custom_scan`]
//! walks + mounts through `scene3d::arc_set`). They take part in random
//! picks, the two rows (labelled by their folder name) and the previews
//! exactly like the stock rows; the stock block of the catalog never moves.
//!
//! ## Degradation
//!
//! `required_signatures` names the `scene3d` group's anchor; the group is
//! all-or-nothing, so a miss on any build skips the mod cleanly. Without the
//! `startup.arc` rlists or without any stage/dancer arc in the install the
//! mod reports inactive. Everything else is per-song fail-open (a part, a
//! shadow, a camera set, the movie-size override — each degrades alone with
//! one WARN/INFO). `is_active()` = "this mod CAN work" (the service resolved
//! and the tables loaded), never "something rendered this boot".

pub mod background_hide;
pub mod catalog;
pub mod clock;
pub mod custom_content;
pub mod custom_scan;
pub mod director;
pub mod director_math;
pub mod instance_plan;
pub mod lifecycle;
pub mod movie_backdrop;
pub mod movie_camera;
pub mod movie_mode;
pub mod movie_size;
pub mod options;
pub mod outline;
pub mod pick;
pub mod preview;
pub mod scene_window;
pub mod schedule;
pub mod selection;
pub mod session;
pub mod style;
pub mod tempo;
pub mod tempo_source;
pub mod viewport_smoke;

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use crate::mods::mod_trait::{Mod, ModContext};
use crate::services::{input_manager, scene3d, scene_manager};
use crate::{log_info, log_warn};

/// Mod enabled (registry toggle); read by the callbacks.
static ENABLED: AtomicBool = AtomicBool::new(false);

pub struct BackgroundDancersMod {
    scene_cb: Option<usize>,
    frame_cb: Option<usize>,
}

impl BackgroundDancersMod {
    pub fn new() -> Self {
        Self {
            scene_cb: None,
            frame_cb: None,
        }
    }
}

impl Mod for BackgroundDancersMod {
    fn id(&self) -> &str {
        "background-dancers"
    }

    fn name(&self) -> &str {
        // Also the GLOBAL SETTINGS group header of the mod menu (maintainer:
        // no "Enable" prefix there).
        "Background Dancers"
    }

    fn description(&self) -> &str {
        "Random A3 3D stage + dancers behind the lane, rendered by the game's own model passes"
    }

    fn required_signatures(&self) -> &[&str] {
        &[
            "scene3d_scene_graph_manager",
            "file_manager_load",
            "file_manager_free",
            "file_manager_singleton",
        ]
    }

    fn init(&mut self, ctx: &ModContext) -> bool {
        // Optional: the movie-size override and the fullscreen-movie probe
        // behind Background Movies = FULLSCREEN (fail-open without them).
        let _ = movie_size::init(ctx.signatures);
        let _ = movie_backdrop::init(ctx.signatures);
        scene3d::is_available()
    }

    fn enable(&mut self) {
        if !scene3d::is_available() {
            log_warn!("BackgroundDancers: scene3d service unavailable -- mod inactive");
            return;
        }
        if !lifecycle::tables_ready() && !lifecycle::init_tables() {
            return;
        }
        ENABLED.store(true, Ordering::Release);
        style::init_from_config();
        // The BACKGROUND DANCER / BACKGROUND STAGE rows (options.rs) over the
        // catalog derived from the tables (stock block first, then the custom
        // data_mods entries under their folder names); fail-open (absent rows
        // ⇒ random picks, one WARN inside).
        match lifecycle::tables_snapshot() {
            Some((stages, _camera_rows, dancers)) => {
                let custom = lifecycle::custom_labels_snapshot();
                options::register(catalog::build_catalog_with_custom(
                    &stages, &dancers, &custom,
                ));
            }
            None => log_warn!("BackgroundDancers: tables unreadable -- option rows not registered"),
        }
        // The live 3D previews behind the two rows (fail-open without the
        // compositor).
        preview::init();
        // Dev-mode compositor smoke (`DDR_DANCERS_VIEWPORT_SMOKE`).
        viewport_smoke::init_from_env();
        if self.scene_cb.is_none() {
            self.scene_cb = Some(scene_manager::on_scene_change(Box::new(|prev, next| {
                if !ENABLED.load(Ordering::Acquire) {
                    return;
                }
                lifecycle::on_scene_change(prev, next);
                preview::on_scene_change(prev, next);
                viewport_smoke::on_scene_change(prev, next);
            })));
        }
        if self.frame_cb.is_none() {
            self.frame_cb = Some(input_manager::on_frame(Arc::new(|| {
                if !ENABLED.load(Ordering::Acquire) {
                    return;
                }
                background_hide::on_frame();
                lifecycle::on_frame();
                preview::on_frame();
                viewport_smoke::on_frame();
                // The ONE per-frame reaper call for every viewport-pass
                // owner in this mod (frees detached sets after 2 frames).
                scene3d::viewport_pass::reap();
            })));
        }
        log_info!("BackgroundDancers: enabled -- random A3 stage + dancers every song");
    }

    fn disable(&mut self) {
        ENABLED.store(false, Ordering::Release);
        if let Some(id) = self.frame_cb.take() {
            input_manager::remove_frame_callback(id);
        }
        if let Some(id) = self.scene_cb.take() {
            scene_manager::remove_callback(id);
        }
        // Hide the option rows (values + persistence stay; a re-enable
        // re-arms them) and stop mirroring the stage row.
        options::set_available(false);
        preview::shutdown();
        viewport_smoke::shutdown();
        // Restore the 2D background first (its alpha is a write into a
        // game-owned layer), then neutralise any live scene.
        background_hide::disarm();
        lifecycle::teardown_on_disable();
        log_info!("BackgroundDancers: disabled");
    }

    fn is_active(&self) -> bool {
        scene3d::is_available() && lifecycle::tables_ready()
    }
}
