//! The MOVIE camera set — the stage-mode camera clips used instead of the
//! stage's own cameras while Background Movies = FULLSCREEN (NO STAGE) has a
//! movie as the backdrop (`movie_mode.rs`). Std-only (the host harness
//! mounts it: `scripts/validate_background_dancers.sh`).
//!
//! The clips are loose `.camanm` files in ONE fixed folder,
//! [`MOVIE_CAMERA_DIR`] (the `preview/badge.rs` fixed-path convention; the
//! engine never loads them — like every stage camera set they are read by
//! the mod's own parser only). The shipped set is generated by
//! `scripts/gen_movie_cameras.py`; an operator may replace or extend it.
//! Naming, per clip stem:
//! - `_non` anywhere ⇒ an A3 cut-away (shown for 1–2 s at a dance change,
//!   `schedule::CameraSchedule`), otherwise a main clip (cycled);
//! - a `_1p` token ⇒ only with ONE dancer, a `_2p` token ⇒ only with TWO or
//!   more; no token ⇒ always.
//!
//! When the dancer count leaves no main clip (only `_2p` clips installed and
//! one dancer, say), the other count's clips are used rather than falling
//! back to the stage cameras. No main clip at all ⇒ the stage cameras stay
//! (the caller logs it).

use std::path::PathBuf;

/// Where the movie camera clips live (relative to the game's working
/// directory, like every `data_mods` path the mod reads directly).
pub const MOVIE_CAMERA_DIR: &str = "./data_mods/background_dancers/movie_camera";
/// Clip extension.
pub const EXT: &str = "camanm";

/// The player-count tag of a clip stem: `Some(1)` for a `_1p` token,
/// `Some(2)` for `_2p`, `None` for an untagged (any count) clip. A token is
/// `_1p` / `_2p` followed by the end of the stem or another `_`.
pub fn player_tag(stem: &str) -> Option<u8> {
    let lower = stem.to_ascii_lowercase();
    for (tag, n) in [("_1p", 1u8), ("_2p", 2u8)] {
        let mut from = 0usize;
        while let Some(pos) = lower[from..].find(tag) {
            let end = from + pos + tag.len();
            if end == lower.len() || lower.as_bytes()[end] == b'_' {
                return Some(n);
            }
            from = end;
        }
    }
    None
}

/// Whether a stem is a cut-away (`_non`, the A3 rule of
/// `selection::camera_lists`).
pub fn is_cutaway(stem: &str) -> bool {
    stem.contains("_non")
}

/// The clips a scene with `dancers` dancers uses, sorted (the caller
/// shuffles them with the per-song rng through `selection::camera_lists`).
/// Falls back to the other player count's clips when the matching ones hold
/// no MAIN clip (see the module doc).
pub fn filter_for(stems: &[String], dancers: usize) -> Vec<String> {
    let want: u8 = if dancers >= 2 { 2 } else { 1 };
    let mut sorted: Vec<String> = stems.to_vec();
    sorted.sort();
    sorted.dedup();
    let matching: Vec<String> = sorted
        .iter()
        .filter(|s| player_tag(s).map_or(true, |t| t == want))
        .cloned()
        .collect();
    if matching.iter().any(|s| !is_cutaway(s)) {
        matching
    } else {
        sorted
    }
}

/// The `.camanm` stems in `dir` (non-recursive, case-insensitive
/// extension), sorted; empty when the folder is missing or unreadable.
pub fn list_stems(dir: &str) -> Vec<String> {
    let Ok(rd) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut out: Vec<String> = rd
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let path = e.path();
            if !path.is_file() {
                return None;
            }
            let ext = path.extension()?.to_str()?;
            if !ext.eq_ignore_ascii_case(EXT) {
                return None;
            }
            Some(path.file_stem()?.to_str()?.to_string())
        })
        .collect();
    out.sort();
    out
}

/// The file path of a clip stem.
pub fn clip_path(stem: &str) -> PathBuf {
    PathBuf::from(MOVIE_CAMERA_DIR).join(format!("{stem}.{EXT}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn s(v: &[&str]) -> Vec<String> {
        v.iter().map(|x| x.to_string()).collect()
    }

    #[test]
    fn tags() {
        assert_eq!(player_tag("movie_st01_1p"), Some(1));
        assert_eq!(player_tag("movie_st01_2p"), Some(2));
        assert_eq!(player_tag("movie_1p_st01"), Some(1));
        assert_eq!(player_tag("MOVIE_ST01_2P"), Some(2));
        assert_eq!(player_tag("movie_st01"), None);
        // Not a token: `_1pt`, `_12p`.
        assert_eq!(player_tag("movie_1pt"), None);
        assert_eq!(player_tag("movie_12p"), None);
        assert!(is_cutaway("movie_non01_1p"));
        assert!(!is_cutaway("movie_st01_1p"));
    }

    #[test]
    fn filter_by_dancer_count() {
        let all = s(&[
            "movie_st02_2p",
            "movie_st01_1p",
            "movie_st01_2p",
            "movie_non01_1p",
            "movie_non01_2p",
            "movie_any",
        ]);
        assert_eq!(
            filter_for(&all, 1),
            s(&["movie_any", "movie_non01_1p", "movie_st01_1p"])
        );
        assert_eq!(
            filter_for(&all, 2),
            s(&[
                "movie_any",
                "movie_non01_2p",
                "movie_st01_2p",
                "movie_st02_2p"
            ])
        );
        // Three dancers use the two-player clips; zero use the solo ones.
        assert_eq!(filter_for(&all, 3), filter_for(&all, 2));
        assert_eq!(filter_for(&all, 0), filter_for(&all, 1));
    }

    #[test]
    fn falls_back_to_the_other_count_without_a_main_clip() {
        // Only duo main clips + a solo cut-away: one dancer still gets a set.
        let v = s(&["b_st01_2p", "a_non01_1p"]);
        assert_eq!(filter_for(&v, 1), s(&["a_non01_1p", "b_st01_2p"]));
        // Nothing but cut-aways: returned as-is (the caller finds no main).
        let v = s(&["x_non01"]);
        assert_eq!(filter_for(&v, 1), s(&["x_non01"]));
        assert!(filter_for(&[], 1).is_empty());
        // Duplicates collapse.
        assert_eq!(filter_for(&s(&["a", "a"]), 1), s(&["a"]));
    }

    #[test]
    fn listing_reads_camanm_stems_only() {
        let dir = std::env::temp_dir().join(format!("bd_movie_cam_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("sub.camanm")).unwrap();
        for f in ["b_st01_1p.camanm", "a_non01.CAMANM", "readme.txt", "c.anm"] {
            std::fs::write(dir.join(f), b"x").unwrap();
        }
        let got = list_stems(dir.to_str().unwrap());
        assert_eq!(got, s(&["a_non01", "b_st01_1p"]));
        assert!(list_stems(dir.join("missing").to_str().unwrap()).is_empty());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
