//! Fixture-equality tests: replay `tests/fixtures/anm/*.json` (generated by
//! `scripts/gen_anm_fixtures.py` from the Python reference codecs) against the
//! REAL stock arcs read from `$DDR_WORLD_INSTALL/data/arc/`.
//!
//! Every test SKIPS (after an `eprintln!`) when the install or the fixtures
//! are absent, so the synthetic suite stays runnable anywhere. The arc reader
//! + Konami LZ77 decoder below are TEST-ONLY copies (`scripts/unpack_arc.py`
//! semantics; the DLL's own `core::arc` cannot mount into the harness).

use super::super::anm::parse;
use super::super::camera::{camera_from_slots, sample_slots};
use super::super::pose::{evaluate, sampled_trs, seed_local_trs, Skeleton, Trs};
use super::super::sample::{sample, Sample};
use super::super::{b2it, ktmdl, mat_mul, rlist, Mat4, MAT4_IDENTITY};
use serde_json::Value;
use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// Test-only arc reader
// ---------------------------------------------------------------------------

const ARC_MAGIC: u32 = 0x1975_1120;

struct ArcFile {
    data: Vec<u8>,
    /// (path, data_off, decompressed, compressed)
    entries: Vec<(String, usize, usize, usize)>,
}

fn le_u32(d: &[u8], o: usize) -> Option<u32> {
    let b = d.get(o..o + 4)?;
    Some(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
}

impl ArcFile {
    fn open(path: &Path) -> Option<ArcFile> {
        let data = std::fs::read(path).ok()?;
        if le_u32(&data, 0)? != ARC_MAGIC {
            return None;
        }
        let count = le_u32(&data, 8)? as usize;
        let mut entries = Vec::with_capacity(count);
        for i in 0..count {
            let e = 16 + 16 * i;
            let path_off = le_u32(&data, e)? as usize;
            let data_off = le_u32(&data, e + 4)? as usize;
            let dec = le_u32(&data, e + 8)? as usize;
            let comp = le_u32(&data, e + 12)? as usize;
            let tail = data.get(path_off..)?;
            let end = tail.iter().position(|&b| b == 0).unwrap_or(tail.len());
            let name = String::from_utf8_lossy(&tail[..end]).into_owned();
            entries.push((name, data_off, dec, comp));
        }
        Some(ArcFile { data, entries })
    }

    fn names(&self) -> impl Iterator<Item = &str> {
        self.entries.iter().map(|e| e.0.as_str())
    }

    fn get(&self, name: &str) -> Option<Vec<u8>> {
        let (_, off, dec, comp) = self.entries.iter().find(|e| e.0 == name)?;
        let raw = self.data.get(*off..*off + *comp)?;
        if comp != dec {
            let out = konami_lz77_decompress(raw);
            assert_eq!(out.len(), *dec, "decompressed size mismatch for {name}");
            Some(out)
        } else {
            Some(raw.to_vec())
        }
    }
}

/// `unpack_arc.py::KonamiLz77.decompress`.
fn konami_lz77_decompress(input: &[u8]) -> Vec<u8> {
    const WINDOW: usize = 0x1000;
    const MASK: usize = WINDOW - 1;
    let mut window = vec![0u8; WINDOW];
    let mut cursor = 0usize;
    let mut out = Vec::new();
    let mut i = 0usize;
    while i < input.len() {
        let flag = input[i];
        i += 1;
        for bit in 0..8 {
            if i >= input.len() {
                break;
            }
            if (flag >> bit) & 1 == 1 {
                let b = input[i];
                i += 1;
                out.push(b);
                window[cursor] = b;
                cursor = (cursor + 1) & MASK;
            } else {
                if i + 1 >= input.len() {
                    break;
                }
                let w = ((input[i] as usize) << 8) | input[i + 1] as usize;
                if w == 0 {
                    return out;
                }
                i += 2;
                let mut pos = (cursor.wrapping_sub(w >> 4)) & MASK;
                let len = (w & 0x0F) + 3;
                for _ in 0..len {
                    let b = window[pos & MASK];
                    out.push(b);
                    window[cursor] = b;
                    cursor = (cursor + 1) & MASK;
                    pos += 1;
                }
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Environment
// ---------------------------------------------------------------------------

fn fixture_dir() -> Option<PathBuf> {
    let p = std::env::var_os("ANM_FIXTURE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("tests/fixtures/anm"));
    p.is_dir().then_some(p)
}

fn arc_dir() -> Option<PathBuf> {
    let p = PathBuf::from(std::env::var_os("DDR_WORLD_INSTALL")?)
        .join("data")
        .join("arc");
    p.is_dir().then_some(p)
}

/// `(fixture json, arc dir)` or `None` (+ a printed skip note).
fn env(test: &str, fixture: &str) -> Option<(Value, PathBuf)> {
    let Some(fd) = fixture_dir() else {
        eprintln!("[skip] {test}: fixtures missing (ANM_FIXTURE_DIR / tests/fixtures/anm)");
        return None;
    };
    let Some(ad) = arc_dir() else {
        eprintln!("[skip] {test}: DDR_WORLD_INSTALL unset or has no data/arc");
        return None;
    };
    let text = std::fs::read_to_string(fd.join(fixture)).ok()?;
    let v: Value = serde_json::from_str(&text).expect("fixture json");
    Some((v, ad))
}

fn f(v: &Value) -> f32 {
    v.as_f64().expect("number") as f32
}

fn farr(v: &Value) -> Vec<f32> {
    v.as_array().expect("array").iter().map(f).collect()
}

fn i(v: &Value) -> i64 {
    v.as_i64().expect("int")
}

fn close(a: f32, b: f32, tol: f32) -> bool {
    (a - b).abs() <= tol
}

fn quat_close(a: &[f32], b: &[f32], tol: f32) -> bool {
    a.iter().zip(b).all(|(x, y)| close(*x, *y, tol))
        || a.iter().zip(b).all(|(x, y)| close(*x, -*y, tol))
}

// ---------------------------------------------------------------------------
// Clips
// ---------------------------------------------------------------------------

/// World-matrix tolerance vs the f64 Python chain: 33-deep f32 products.
const WORLD_TOL: f32 = 2e-5;
/// Per-track sample tolerance (one decode + one slerp/lerp in f32).
const SAMPLE_TOL: f32 = 1e-5;

fn check_clip(clip: &Value, arcs: &Path) -> usize {
    let arc_name = clip["arc"].as_str().unwrap();
    let path = clip["path"].as_str().unwrap();
    let arc = ArcFile::open(&arcs.join(arc_name)).unwrap_or_else(|| panic!("open {arc_name}"));
    let bytes = arc
        .get(path)
        .unwrap_or_else(|| panic!("{arc_name} lacks {path}"));
    let a = parse(&bytes).unwrap_or_else(|e| panic!("{path}: {e}"));

    assert_eq!(
        a.frame_count as i64,
        i(&clip["frame_count"]),
        "{path} frame_count"
    );
    assert_eq!(
        a.loops,
        clip["loops"].as_bool().unwrap(),
        "{path} loop flag"
    );
    assert_eq!(a.fps, f(&clip["fps"]), "{path} fps");
    let tracks = clip["tracks"].as_array().unwrap();
    assert_eq!(a.bone_tracks.len(), tracks.len(), "{path} track count");
    for (t, ft) in a.bone_tracks.iter().zip(tracks) {
        assert_eq!(t.kind as i64, i(&ft["kind"]), "{path} kind");
        assert_eq!(t.target as i64, i(&ft["target"]), "{path} target");
        assert_eq!(t.key_count as i64, i(&ft["key_count"]), "{path} key_count");
        assert_eq!(
            t.times.is_none(),
            ft["uniform"].as_bool().unwrap(),
            "{path} uniform"
        );
    }

    let parents: Vec<i16> = clip["parents"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| i(p) as i16)
        .collect();
    let n = parents.len();
    let frames: Vec<f32> = farr(&clip["frames"]);
    let mut checked = 0;
    if clip["fully_tracked"].as_bool().unwrap() {
        // Python seeds identity → equal to the game's bind seed only here.
        let sk = Skeleton {
            parents,
            bind_world: vec![MAT4_IDENTITY; n],
            inverse_bind: vec![MAT4_IDENTITY; n],
        };
        let seed = vec![Trs::IDENTITY; n];
        let worlds = clip["world"].as_array().unwrap();
        for (fi, frame) in frames.iter().enumerate() {
            let got = evaluate(&a, &bytes, *frame, &sk, &seed);
            let exp = worlds[fi].as_array().unwrap();
            for b in 0..n {
                let e = farr(&exp[b]);
                for k in 0..16 {
                    assert!(
                        close(got[b][k], e[k], WORLD_TOL),
                        "{path} frame {frame} bone {b} [{k}]: {} vs {}",
                        got[b][k],
                        e[k]
                    );
                }
                checked += 1;
            }
        }
    } else {
        let samples = clip["samples"].as_array().unwrap();
        for (fi, frame) in frames.iter().enumerate() {
            let per = samples[fi].as_array().unwrap();
            assert_eq!(per.len(), a.bone_tracks.len());
            for (t, fs) in a.bone_tracks.iter().zip(per) {
                let exp = farr(&fs["value"]);
                let got = sample(&bytes, t, *frame).unwrap();
                match got {
                    Sample::Quat(q) => assert!(
                        quat_close(&q, &exp, SAMPLE_TOL),
                        "{path} f{frame} rot {q:?} vs {exp:?}"
                    ),
                    Sample::Vec3(v) => assert!(
                        v.iter().zip(&exp).all(|(x, y)| close(*x, *y, SAMPLE_TOL)),
                        "{path} f{frame} vec {v:?} vs {exp:?}"
                    ),
                    Sample::Scalar(s) => assert!(close(s, exp[0], SAMPLE_TOL)),
                }
                checked += 1;
            }
            // the pre-chain TRS view agrees with the per-track samples too
            let trs = sampled_trs(&a, &bytes, *frame, n, &vec![Trs::IDENTITY; n]);
            for (t, fs) in a.bone_tracks.iter().zip(per) {
                let exp = farr(&fs["value"]);
                let b = t.target as usize;
                if b >= n {
                    continue;
                }
                match fs["channel"].as_str().unwrap() {
                    "rotation" => assert!(quat_close(&trs[b].q, &exp, SAMPLE_TOL)),
                    "translation" => assert!(trs[b]
                        .t
                        .iter()
                        .zip(&exp)
                        .all(|(x, y)| close(*x, *y, SAMPLE_TOL))),
                    "scale" => assert!(trs[b]
                        .s
                        .iter()
                        .zip(&exp)
                        .all(|(x, y)| close(*x, *y, SAMPLE_TOL))),
                    other => panic!("channel {other}"),
                }
            }
        }
    }
    checked
}

#[test]
fn dance_clips_match_reference() {
    let Some((fx, arcs)) = env("dance_clips_match_reference", "dance_clips.json") else {
        return;
    };
    let clips = fx.as_array().unwrap();
    assert_eq!(clips.len(), 30, "mc_male (16) + mc_female (14)");
    let mut checked = 0;
    for clip in clips {
        assert!(
            clip["fully_tracked"].as_bool().unwrap(),
            "dance clips are fully tracked"
        );
        checked += check_clip(clip, &arcs);
    }
    eprintln!(
        "dance clips: {} clips, {checked} bone matrices compared",
        clips.len()
    );
}

#[test]
fn stage_loops_match_reference() {
    let Some((fx, arcs)) = env("stage_loops_match_reference", "stage_loops.json") else {
        return;
    };
    let loops = fx.as_array().unwrap();
    assert!(
        loops.len() >= 60,
        "expected every mapset _play_loop, got {}",
        loops.len()
    );
    let mut checked = 0;
    let mut partial = 0;
    for clip in loops {
        if !clip["fully_tracked"].as_bool().unwrap() {
            partial += 1;
        }
        checked += check_clip(clip, &arcs);
    }
    eprintln!(
        "stage loops: {} clips ({partial} partial), {checked} comparisons",
        loops.len()
    );
}

#[test]
fn loop_flag_matches_names() {
    let Some((fx, _)) = env("loop_flag_matches_names", "dance_clips.json") else {
        return;
    };
    for clip in fx.as_array().unwrap() {
        let path = clip["path"].as_str().unwrap();
        let loops = clip["loops"].as_bool().unwrap();
        if path.ends_with("_loop.anm") {
            assert!(loops, "{path} should loop");
        } else if path.ends_with("_exec.anm") {
            assert!(!loops, "{path} should not loop");
        }
    }
    let Some((fx, _)) = env("loop_flag_matches_names", "stage_loops.json") else {
        return;
    };
    for clip in fx.as_array().unwrap() {
        assert!(
            clip["loops"].as_bool().unwrap(),
            "{} should loop",
            clip["path"]
        );
    }
}

// ---------------------------------------------------------------------------
// Cameras
// ---------------------------------------------------------------------------

#[test]
fn stage_cameras_match_reference() {
    let Some((fx, arcs)) = env("stage_cameras_match_reference", "stage_cameras.json") else {
        return;
    };
    let cams = fx.as_array().unwrap();
    assert_eq!(cams.len(), 93);
    let arc =
        ArcFile::open(&arcs.join("camera").join("stage_camera.arc")).expect("stage_camera.arc");
    for cam in cams {
        let path = cam["path"].as_str().unwrap();
        let bytes = arc.get(path).unwrap_or_else(|| panic!("missing {path}"));
        let a = parse(&bytes).unwrap_or_else(|e| panic!("{path}: {e}"));
        assert!(a.has_camera(), "{path}");
        assert!(a.bone_tracks.is_empty());
        assert_eq!(a.frame_count as i64, i(&cam["frame_count"]));
        assert_eq!(a.fps, f(&cam["fps"]), "{path} fps");
        assert_eq!(a.loops, cam["loops"].as_bool().unwrap());
        let kinds = cam["slot_kinds"].as_array().unwrap();
        for (slot, k) in kinds.iter().enumerate() {
            match (&a.camera_slots[slot], k.as_i64()) {
                (None, None) => {}
                (Some(t), Some(kind)) => assert_eq!(t.kind as i64, kind, "{path} slot {slot}"),
                (got, exp) => panic!("{path} slot {slot}: {got:?} vs {exp:?}"),
            }
        }
        let frames = farr(&cam["frames"]);
        let rows = cam["slots"].as_array().unwrap();
        for (fi, frame) in frames.iter().enumerate() {
            let s = sample_slots(&a, &bytes, *frame);
            let row = rows[fi].as_array().unwrap();
            for slot in 0..6 {
                if row[slot].is_null() {
                    assert!(!s.present[slot]);
                    continue;
                }
                assert!(s.present[slot], "{path} slot {slot} present");
                match slot {
                    0 => assert!(
                        quat_close(&s.q, &farr(&row[0]), SAMPLE_TOL),
                        "{path} f{frame} q {:?} vs {:?}",
                        s.q,
                        row[0]
                    ),
                    1 => {
                        let e = farr(&row[1]);
                        // centimetres up to ~2500: f32 ulp there is ~2.4e-4
                        assert!(
                            s.pos_cm.iter().zip(&e).all(|(x, y)| close(
                                *x,
                                *y,
                                1e-4 + 1e-6 * y.abs()
                            )),
                            "{path} f{frame} pos {:?} vs {e:?}",
                            s.pos_cm
                        );
                    }
                    2 => assert!(close(s.fov_v_deg, f(&row[2]), 1e-4)),
                    3 => assert!(close(s.near, f(&row[3]), 1e-6)),
                    4 => assert!(
                        close(s.far, f(&row[4]), 1e-1),
                        "{path} far {} vs {}",
                        s.far,
                        row[4]
                    ),
                    _ => assert!(close(s.aspect_file, f(&row[5]), 1e-5)),
                }
            }
            // the recipe's algebra over the sampled slots
            let c = camera_from_slots(&s, 1.0, 1.0);
            for k in 0..3 {
                assert!(close(c.eye[k], s.pos_cm[k] * 0.01, 1e-5));
            }
            let d = [
                c.target[0] - c.eye[0],
                c.target[1] - c.eye[1],
                c.target[2] - c.eye[2],
            ];
            assert!(
                close((d[0] * d[0] + d[1] * d[1] + d[2] * d[2]).sqrt(), 10.0, 1e-3),
                "{path} target distance"
            );
            assert!(close(
                (c.up[0] * c.up[0] + c.up[1] * c.up[1] + c.up[2] * c.up[2]).sqrt(),
                1.0,
                1e-5
            ));
            assert_eq!(c.l, -c.r);
            assert_eq!(c.b, -c.t);
            assert!(close(c.r / c.t, 16.0 / 9.0, 1e-4));
            assert!(c.r > 0.0 && c.r < 2.0, "{path} half-tangent {}", c.r);
            assert_eq!(c.near, s.near);
            assert_eq!(c.far, s.far);
        }
    }
    eprintln!("stage cameras: {} camanms compared", cams.len());
}

// ---------------------------------------------------------------------------
// Tables
// ---------------------------------------------------------------------------

#[test]
fn rlists_match_reference() {
    let Some((fx, arcs)) = env("rlists_match_reference", "rlists.json") else {
        return;
    };
    let arc = ArcFile::open(&arcs.join("startup.arc")).expect("startup.arc");
    let obj = fx.as_object().unwrap();
    assert_eq!(obj.len(), 4);
    for (path, rows_exp) in obj {
        let bytes = arc.get(path).unwrap_or_else(|| panic!("missing {path}"));
        let rows = rlist::parse(&bytes).unwrap_or_else(|e| panic!("{path}: {e}"));
        let exp = rows_exp.as_array().unwrap();
        assert_eq!(rows.len(), exp.len(), "{path} row count");
        for (r, e) in rows.iter().zip(exp) {
            let e = e.as_array().unwrap();
            assert_eq!(r.0, e[0].as_str().unwrap(), "{path} key");
            let fields: Vec<&str> = e[1]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_str().unwrap())
                .collect();
            assert_eq!(r.1, fields, "{path} fields of {}", r.0);
        }
    }
    // the rows the design leans on
    let chara = rlist::parse(&arc.get("data/chara/chara_resources.rlist").unwrap()).unwrap();
    assert_eq!(chara.len(), 26);
    let (row, (_, fields)) = rlist::find(&chara, "emi00").unwrap();
    assert_eq!(row, 21);
    assert_eq!(fields[..3], ["pl", "F", "A"].map(String::from));
    let map = rlist::parse(&arc.get("data/map/map_resources.rlist").unwrap()).unwrap();
    assert_eq!(map.len(), 34);
    assert_eq!(map[0].0, "boom00");
    assert_eq!(map[32].0, "boom00");
    assert!(map[32].1.iter().any(|f| f == "footpanel"));
    assert_eq!(map.iter().filter(|(k, _)| k == "dummy00").count(), 7);
}

#[test]
fn pl_emi00_b2it_and_bone_table_match_reference() {
    let Some((fx, arcs)) = env(
        "pl_emi00_b2it_and_bone_table_match_reference",
        "pl_emi00.json",
    ) else {
        return;
    };
    let arc = ArcFile::open(&arcs.join("pl_emi00.arc")).expect("pl_emi00.arc");
    let b2 = b2it::parse(&arc.get("data/chara/pl_emi00/pl_emi00.b2it").unwrap()).unwrap();
    let exp = fx["b2it"].as_array().unwrap();
    assert_eq!(b2.len(), exp.len());
    assert_eq!(b2.len(), 33);
    for (got, e) in b2.iter().zip(exp) {
        let e = e.as_array().unwrap();
        assert_eq!(got.0, e[0].as_str().unwrap());
        assert_eq!(got.1 as i64, i(&e[1]));
    }
    // sorted ordinally → binary search works on the file order
    assert!(b2.windows(2).all(|w| w[0].0.as_bytes() < w[1].0.as_bytes()));
    assert_eq!(b2it::index_of(&b2, "Head"), Some(16));
    assert_eq!(b2it::index_of(&b2, "Hips"), Some(1));
    assert_eq!(b2it::index_of(&b2, "Spine2"), Some(8));
    assert_eq!(b2it::index_of(&b2, "LeftForeArmRoll"), Some(29));
    assert_eq!(b2it::index_of(&b2, "RightForeArmRoll"), Some(30));
    assert_eq!(b2it::index_of(&b2, "nope"), None);

    let model = arc.get("data/chara/pl_emi00/pl_emi00.model").unwrap();
    let sk = ktmdl::bone_table(&model).unwrap();
    let bones = &fx["bones"];
    let parents: Vec<i16> = bones["parents"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| i(p) as i16)
        .collect();
    assert_eq!(sk.parents, parents);
    assert_eq!(sk.bone_count(), 33);
    let bind = bones["bind"].as_array().unwrap();
    let inverse = bones["inverse"].as_array().unwrap();
    for b in 0..33 {
        let eb = farr(&bind[b]);
        let ei = farr(&inverse[b]);
        for k in 0..16 {
            assert!(close(sk.bind_world[b][k], eb[k], 1e-6), "bind {b}[{k}]");
            assert!(
                close(sk.inverse_bind[b][k], ei[k], 1e-6),
                "inverse {b}[{k}]"
            );
        }
        // bind · inverse ≈ I
        let p = mat_mul(&sk.bind_world[b], &sk.inverse_bind[b]);
        for k in 0..16 {
            assert!(
                close(p[k], MAT4_IDENTITY[k], 1e-4),
                "bind·inv {b}[{k}] = {}",
                p[k]
            );
        }
        // topological order
        assert!(sk.parents[b] < b as i16);
    }
    // Hips at y ≈ 0.97 m (docs §3.2)
    assert!(
        close(sk.bind_world[1][13], 0.97, 0.05),
        "hips y {}",
        sk.bind_world[1][13]
    );

    // The A3 seed reproduces the real rig's bind pose with no tracks.
    let seed = seed_local_trs(&sk);
    let empty = super::build_anm(1, 0, 1, false, &[], None);
    let a = parse(&empty).unwrap();
    let world: Vec<Mat4> = evaluate(&a, &empty, 0.0, &sk, &seed);
    for b in 0..33 {
        for k in 0..16 {
            assert!(
                close(world[b][k], sk.bind_world[b][k], 1e-4),
                "seeded world {b}[{k}]: {} vs {}",
                world[b][k],
                sk.bind_world[b][k]
            );
        }
    }
}
