//! The RANDOM badge (FR-9, design §4.6 "preview/badge.rs"): while one of
//! our rows is focused with the RANDOM value the preview box has no 3D to
//! show, so a static badge (`data_mods/background_dancers/tex/preview_random.png`,
//! 170×150, generated by `scripts/gen_preview_random_badge.py`) is drawn
//! over the box instead — one native `ImageWidget` per side, the
//! `training_mode::scrub_indicator` model: the PNG is requested through
//! `asset_loader` ONCE and never released (process-lifetime chrome), the
//! widget is created lazily once the texture resolves and is shown / hidden
//! from the preview driver's per-frame step. Every failure is fail-open (no
//! badge, one WARN per class): the rows keep working, the box keeps its chrome.

use std::sync::atomic::{AtomicBool, Ordering};

use crate::log_warn;
use crate::services::{asset_loader, widget_renderer};
use crate::widgets::image_widget::{ImageWidget, ImageWidgetConfig};

use super::layout::CanvasRect;

const TEX_PATH: &str = "./data_mods/background_dancers/tex/preview_random.png";
/// Unique in the ResourceManager namespace.
const TEX_STEM: &str = "preview_random";

/// One-shot WARN latches (process-wide — both sides share the texture).
static WARN_LOADER: AtomicBool = AtomicBool::new(false);
static WARN_WIDGET: AtomicBool = AtomicBool::new(false);
/// The asset load has been requested (once per process).
static LOAD_REQUESTED: AtomicBool = AtomicBool::new(false);
static LOAD_FAILED: AtomicBool = AtomicBool::new(false);

pub struct Badge {
    widget: Option<ImageWidget>,
    texture: Option<i32>,
    shown: bool,
    rect: Option<CanvasRect>,
    widget_failed: bool,
}

impl Badge {
    pub const fn new() -> Badge {
        Badge {
            widget: None,
            texture: None,
            shown: false,
            rect: None,
            widget_failed: false,
        }
    }

    pub fn is_shown(&self) -> bool {
        self.shown
    }

    /// Game thread (the driver's per-frame step). `on` ⇒ make sure the
    /// texture is requested / resolved and the widget exists at `rect`, then
    /// show it; `!on` ⇒ hide. Idempotent — no work when nothing changed.
    pub fn set_visible(&mut self, side: usize, on: bool, rect: CanvasRect) {
        if !on {
            if self.shown {
                if let Some(w) = self.widget.as_ref() {
                    w.hide();
                }
                self.shown = false;
            }
            return;
        }
        if self.widget_failed || LOAD_FAILED.load(Ordering::Acquire) {
            return;
        }
        if !widget_renderer::is_available() {
            return;
        }
        // Texture: request once, then poll until the engine registered it.
        if !LOAD_REQUESTED.swap(true, Ordering::AcqRel) {
            if !asset_loader::is_available() || asset_loader::load(TEX_PATH, TEX_STEM).is_none() {
                LOAD_FAILED.store(true, Ordering::Release);
                if !WARN_LOADER.swap(true, Ordering::AcqRel) {
                    log_warn!(
                        "BackgroundDancers: preview -- RANDOM badge {} could not be loaded (asset loader unavailable or the PNG is missing) -- no badge",
                        TEX_PATH
                    );
                }
                return;
            }
        }
        if self.texture.is_none() {
            self.texture = asset_loader::resolve(TEX_STEM).map(|t| t.handle as i32);
            if self.texture.is_none() {
                return; // not registered yet — next frame
            }
        }
        if self.widget.is_none() {
            let Some(texture) = self.texture else { return };
            match widget_renderer::create_image_widget(&ImageWidgetConfig {
                x: rect.x,
                y: rect.y,
                width: rect.w,
                height: rect.h,
                texture_name: None,
                ..Default::default()
            }) {
                Some(w) => {
                    w.set_texture_id(texture);
                    w.hide();
                    self.widget = Some(w);
                    self.rect = Some(rect);
                }
                None => {
                    self.widget_failed = true;
                    if !WARN_WIDGET.swap(true, Ordering::AcqRel) {
                        log_warn!(
                            "BackgroundDancers: preview P{} -- RANDOM badge widget could not be created -- no badge",
                            side + 1
                        );
                    }
                    return;
                }
            }
        }
        let Some(w) = self.widget.as_ref() else {
            return;
        };
        if self.rect != Some(rect) {
            w.set_position(rect.x, rect.y);
            w.set_size(rect.w, rect.h);
            self.rect = Some(rect);
        }
        if !self.shown {
            w.show();
            self.shown = true;
        }
    }

    /// Mod disable: hide + retire the widget (render-list nodes are never
    /// reclaimed; a re-enable creates a fresh one).
    pub fn destroy(&mut self) {
        if let Some(mut w) = self.widget.take() {
            w.destroy();
        }
        self.shown = false;
        self.rect = None;
    }
}
