//! Decorative Option Headers Mod — owns the non-selectable group-heading
//! rows on the MODS options tab.
//!
//! Pure cosmetics: each header is a stateless [`UiKind::Header`] row
//! (`RegisterSpec::header`) whose entire visible art is its label texture
//! (`seop_item_<id>.png`, generated by `scripts/gen_option_labels.py` —
//! an opaque full-width bar; the header renderer hides the row's value
//! box). Headers carry no values, no persistence, and no wire fields.
//!
//! Placement stays operator-owned (R10 of the training-mode design, where
//! the header mechanism landed): a registered header renders ONLY when
//! the operator lists it in `custom_options.option_menu_settings`,
//! positioned above
//! the functional rows it groups. Registration alone injects nothing, so
//! enabling this mod with no settings listing is a clean no-op — and
//! disabling it removes every heading (the rows themselves are untouched
//! and simply render ungrouped).
//!
//! The TRAINING OPTIONS header originally shipped inside the
//! training-mode mod (Step 8 of
//! `.agents/planning/2026-08-13-training-mode/`); it was lifted here once
//! the concept proved out so all headings share one owner and one toggle.

use std::sync::atomic::{AtomicBool, Ordering};

use crate::mods::mod_trait::{Mod, ModContext};
use crate::services::custom_options::{self, RegisterSpec};
use crate::{log_info, log_warn};

/// Every header row this mod owns, in no particular order (display order
/// is `custom_options.option_menu_settings`'s job). Each id needs a matching
/// `seop_item_<id>.png` under `data_mods/custom_options/.../tex/` — see
/// `HEADER_LABELS` in `scripts/gen_option_labels.py`.
const HEADER_IDS: [(&str, &str, &str); 4] = [
    (
        "header_power_user_options",
        "POWER USER OPTIONS",
        "Options group heading",
    ),
    (
        "header_playfield_styling_options",
        "PLAYFIELD STYLING OPTIONS",
        "Options group heading",
    ),
    (
        "header_training_options",
        "TRAINING OPTIONS",
        "Options group heading",
    ),
    (
        "header_profile_customization_options",
        "PROFILE CUSTOMIZATION OPTIONS",
        "Options group heading",
    ),
];

/// Whether the mod enabled successfully this boot (at least one header
/// registered or re-availed).
static ACTIVE: AtomicBool = AtomicBool::new(false);

pub struct DecorativeOptionHeadersMod;

impl DecorativeOptionHeadersMod {
    pub fn new() -> Self {
        Self
    }
}

impl Mod for DecorativeOptionHeadersMod {
    fn id(&self) -> &str {
        "decorative-option-headers"
    }
    fn name(&self) -> &str {
        "Decorative Option Headers"
    }
    fn description(&self) -> &str {
        "Group-heading rows on the options MODS tab (placement via custom_options.option_menu_settings)"
    }
    fn required_signatures(&self) -> &[&str] {
        // Purely a custom_options consumer; readiness is gated live in
        // enable() like every other row-registering mod.
        &[]
    }

    fn init(&mut self, _ctx: &ModContext) -> bool {
        true
    }

    fn enable(&mut self) {
        if !custom_options::is_available() {
            log_warn!("DecorativeOptionHeaders: custom_options unavailable -- refusing to enable");
            return;
        }

        // Best-effort per header: a failure drops that one heading (its
        // rows render ungrouped) and never blocks the others. Duplicate is
        // the normal re-enable path — registration survives disable(), so
        // flip availability back on for the next form rebuild.
        let mut registered = 0usize;
        for (id, display, desc) in HEADER_IDS {
            match custom_options::register_option(
                RegisterSpec::header(id)
                    .display_name(display)
                    .description(desc),
            ) {
                Ok(_) | Err(custom_options::RegisterError::Duplicate { .. }) => {
                    custom_options::set_option_available(id, true);
                    registered += 1;
                }
                Err(error) => {
                    log_warn!(
                        "DecorativeOptionHeaders: {id} registration failed ({error:?}) -- heading absent"
                    );
                }
            }
        }

        if registered == 0 {
            log_warn!("DecorativeOptionHeaders: no header registered -- self-disabling");
            return;
        }
        ACTIVE.store(true, Ordering::Release);
        log_info!(
            "DecorativeOptionHeaders: enabled -- {registered}/{} headers available (render only when listed in custom_options.option_menu_settings)",
            HEADER_IDS.len()
        );
    }

    fn disable(&mut self) {
        // Hide every heading at the next form rebuild. Registration and
        // the label atlas entries persist for a later re-enable; unknown
        // ids (never-registered due to an enable() failure) WARN inside
        // set_option_available and no-op, which is fine here.
        for (id, _, _) in HEADER_IDS {
            custom_options::set_option_available(id, false);
        }
        ACTIVE.store(false, Ordering::Release);
        log_info!("DecorativeOptionHeaders: disabled -- rows render ungrouped");
    }

    fn is_active(&self) -> bool {
        ACTIVE.load(Ordering::Acquire)
    }
}
