//! Per-Song Judgement Offsets (`per-song-judgement-offsets`, default ON) —
//! per-player overrides of the stock JUDGEMENT OFFSET
//! (`ddr::player::Option+0x24`, `timing_music`) that follow the song wheel:
//! highlight a song and its own offset is shown and edited; play it and that
//! offset governs the song, then the player's stock value comes back.
//!
//! ## Data model
//!
//! - **CSV baseline** — `judgement_offsets.csv` beside `mod-config.json`
//!   (`code,p1_offset,p2_offset`, `code` = musicdb basename, blank = unset,
//!   ±100 ms). At boot a background thread crawls the musicdb from disk
//!   (stock `startup.arc` or a whole-file mod override, plus every mod's
//!   `musicdb.merged.xml` fragment) and appends rows for missing songs;
//!   existing rows are never modified. Only explicit menu edits write cells.
//! - **Community pre-seed** — the repo-root `judgement_offsets.csv` ships in
//!   the release archive, generated by `scripts/gen_judgement_offsets_csv.py`
//!   from a community sync list (same value for P1 and P2). That list records
//!   each song's sync ERROR; the CSV stores the COMPENSATING offset, so the
//!   script negates every incoming value.
//! - **Session maps** — one per side, seeded from the CSV baseline. A profile
//!   load replaces the side's map; card-in resets it to the baseline first.
//!
//! ## Submodules
//!
//! - `csv` / `store` / `musicdb_scan` — pure layers (CSV grammar, baseline +
//!   session merge rules and the `code|offset|...` wire codec, basename scan).
//!   `csv.rs` is also `#[path]`-mounted by the updater's CSV merge.
//! - `bootstrap` — boot crawl + baseline load, then the coalesced background
//!   CSV writer for menu edits.
//! - `ui` — rows `adjust_song_offset` (bool) + `current_song_offset` (scalar
//!   −100..+100 ms), both `PersistMode::None`; a SONG_SELECT frame poll
//!   re-seeds them per side via `set_value_silent`. Edits go to the editing
//!   side only, or to both sides and both CSV columns when the operator sets
//!   `per_song_judgement_offsets.mirror_players` (last writer wins).
//! - `persistence` — the `mod_judge_offsets` kbin `str` field on the
//!   `custom_options_persistence` string-field registry, plus its card-in
//!   callback. An empty map encodes as `""`, the server-clear signal.
//! - `override_hook` — the safety-critical write/restore lifecycle.
//!
//! ## Override lifecycle (detail and rationale in `override_hook.rs`)
//!
//! - Identity: the wheel code latched at scene 26, overwritten by the
//!   SSQ-open observer (`avs_layeredfs` `avs_fs_open`) and the dance-bank
//!   create observer (`song_rate` wavebank hook). The bank create is the
//!   per-stage source for courses, which batch-preload their SSQs. Normal
//!   play, Training Mode and Course/Dan all apply overrides.
//! - Write: armed at GAMEPLAY entry, applied at the side's first judge
//!   dispatch through a `judge_hook` pre at **`Priority::Early`**. The
//!   priority is load-bearing: assist-tick reads `Option+0x24` on that same
//!   dispatch at `Normal` and must see the override. The stock value is
//!   cached, and a stock value outside ±100 aborts the write.
//! - Restore: on the scene change with `prev == GAMEPLAY`, a full loader scene
//!   before the per-stage save marshal. A restore inside the save trampoline
//!   would be too late because the marshal has already copied PlayerWork. A
//!   SONG_SELECT-entry sweep restores and WARNs if anything survived. In-place
//!   restarts never leave GAMEPLAY, so the override correctly persists.
//! - Save-tree rewrite: `custom_options_persistence` asks
//!   [`override_hook::leaked_stock`] at save-build time and, on a leak,
//!   rewrites `<timing_music>` in the built tree to the cached stock value
//!   (`replace_option_s32`), so a profile is never saved with an override.
//!
//! ## Degradation
//!
//! Requires `player_option_table` and `selectmusic_model`; either missing ⇒
//! mod unregistered. Everything is gated on
//! `custom_options::row_injection_available()` at `enable()`: without the
//! option rows (or if row registration fails) the mod is fully inert. A
//! failed musicdb crawl keeps the existing CSV as-is; an unreadable option
//! chain skips the override (stock applies) with one WARN.
//!
//! Host tests: `scripts/validate_judgement_offsets.sh`. RE notes:
//! `docs/per_song_judgement_offsets.md`.

pub mod bootstrap;
pub mod csv;
pub mod musicdb_scan;
pub mod override_hook;
pub mod persistence;
pub mod store;
pub mod ui;

use crate::mods::mod_trait::{Mod, ModContext};
use crate::services::custom_options;
use crate::{log_info, log_warn};
use std::sync::atomic::{AtomicBool, Ordering};

/// Whether `enable()` completed (row injection present, bootstrap spawned).
/// Later steps' hook callbacks gate on this.
static MOD_ACTIVE: AtomicBool = AtomicBool::new(false);

/// True while the mod is enabled and its machinery is live.
pub fn is_active() -> bool {
    MOD_ACTIVE.load(Ordering::Acquire)
}

pub struct PerSongJudgementOffsetsMod;

impl PerSongJudgementOffsetsMod {
    pub fn new() -> Self {
        Self
    }
}

impl Default for PerSongJudgementOffsetsMod {
    fn default() -> Self {
        Self::new()
    }
}

impl Mod for PerSongJudgementOffsetsMod {
    fn id(&self) -> &str {
        "per-song-judgement-offsets"
    }

    fn name(&self) -> &str {
        "Per-Song Judgement Offsets"
    }

    fn description(&self) -> &str {
        "Per-player judgement offsets that follow the selected song, overriding the stock JUDGEMENT OFFSET for that song only"
    }

    fn required_signatures(&self) -> &[&str] {
        // player_option_table: the Option+0x24 write target (Step 5).
        // selectmusic_model: the wheel-selection poll anchor (Step 4).
        &["player_option_table", "selectmusic_model"]
    }

    fn init(&mut self, ctx: &ModContext) -> bool {
        ui::init(ctx);
        override_hook::init(ctx);
        true
    }

    fn enable(&mut self) {
        // Design requirement 9 / register D20: no UI ⇒ fully inert.
        if !custom_options::row_injection_available() {
            log_warn!(
                "PerSongJudgementOffsets: option-row injection unavailable -- mod fully inert"
            );
            return;
        }
        if !ui::enable() {
            return; // row registration failed — inert (WARN already logged)
        }
        bootstrap::start();
        override_hook::enable();
        persistence::register();
        MOD_ACTIVE.store(true, Ordering::Release);
        log_info!("PerSongJudgementOffsets: enabled (rows registered, bootstrap crawl started)");
    }

    fn disable(&mut self) {
        MOD_ACTIVE.store(false, Ordering::Release);
        override_hook::on_mod_disable();
        log_info!("PerSongJudgementOffsets: disabled");
    }

    fn is_active(&self) -> bool {
        is_active()
    }
}
