//! SMX touch-overlay rendering + shared button state.
//!
//! Buttons render NATIVELY as textured command-list quads (decision D4 —
//! no separate transparent window), emitted TOPMOST via
//! `overlay_draw::set_topmost_emitter`: post-dispatcher appends to the
//! widget layer's private CommandList draw after (= above) everything —
//! the mod menu, loading art, all game UI. The touch overlay stands in
//! for physical cabinet hardware, so it always wins z (deploy #18
//! feedback: the mod menu occluded the old widget-based labels).
//!
//! Art: one atlas PNG generated by `scripts/gen_smx_overlay_atlas.py`
//! (Gold-cab-styled: silver convex menu diffusers with near-black rounded
//! bevels + a warm LIT variant, Kokushin-style charcoal pinpad keycaps
//! with baked legends, wide utility buttons) loaded through
//! `asset_loader` and referenced by the generated `overlay_atlas` UV
//! table. TextWidgets are gone entirely — legends are baked into the art.
//!
//! **Lit menu buttons:** the game's menu-button lamps are dimlamps
//! `player*8 + button` (P1 Start/Up/Down/Left/Right = 0..4, P2 = 8..12 —
//! decoded from the ark's staging triple-table 0x1800f7a60 + the
//! 21-pair slot map 0x180115c90 + spice2x's BI2A LED table, and
//! cross-validated against the Step 2 woofer ids 19/20). The emitter
//! reads them straight off the live MdxHWIO object (`+0x14C8 + id*4`,
//! the exact poll the transport's LAMP CHECK path does) and crossfades
//! the LIT cell over the base face by lamp value.
//!
//! Pressed feedback: a translucent grey rounded-highlight cell composited
//! over the face (lit or unlit) while touched, with a ≥150 ms minimum
//! flash. Fallback ladder: atlas unresolved ⇒ flat bordered quads (no
//! legends); topmost unavailable ⇒ overlay not drawn, one WARN.

use std::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, Ordering};
use std::sync::Mutex;
use std::time::Instant;

use once_cell::sync::{Lazy, OnceCell};

use crate::services::asset_loader;
use crate::services::input_manager;
use crate::services::overlay_draw::{
    self,
    encode::{Quad, RecordWriter, TexQuad},
};
use crate::{log_info, log_warn};

use super::overlay_atlas as atlas;
use super::overlay_model::{self, Button, ButtonKind, BIT_COUNT};

// ── Shared state ─────────────────────────────────────────────────────

/// Master gate (the mod's enable/disable + `overlay_enabled` config).
static ENABLED: AtomicBool = AtomicBool::new(false);
/// Per-player held-button bitmask (bit = `Button::bit`).
static HELD: [AtomicU32; 2] = [AtomicU32::new(0), AtomicU32::new(0)];
/// Per-player overlay visibility (toggle button; starts visible).
static VISIBLE: [AtomicBool; 2] = [AtomicBool::new(true), AtomicBool::new(true)];
/// Per-(player, bit) last-press epoch millis for the pressed flash.
static PRESS_MS: [[AtomicU64; BIT_COUNT]; 2] = {
    #[allow(clippy::declare_interior_mutable_const)]
    const Z: AtomicU64 = AtomicU64::new(0);
    [[Z; BIT_COUNT], [Z; BIT_COUNT]]
};
/// Quad alpha 0..=255 (derived from the opacity percent; render path).
static ALPHA: AtomicU32 = AtomicU32::new(153);
/// Opacity percent 10..=100 — the persistence/UI source of truth (the
/// ALPHA byte round-trip would drift, e.g. 25% → 24%).
static OPACITY_PCT: AtomicU32 = AtomicU32::new(60);
/// Overlay scale percent 50..=150 (100 = authored layout). Applied about
/// each cluster's screen-corner anchor (render AND hit-test).
static SCALE_PCT: AtomicU32 = AtomicU32::new(100);

/// The live overlay scale factor (hit-testing + rendering).
pub fn scale() -> f32 {
    SCALE_PCT.load(Ordering::Relaxed) as f32 / 100.0
}

/// Live-set the overlay opacity percent (mod-menu row).
pub fn set_opacity_percent(pct: i32) {
    let pct = pct.clamp(10, 100) as u32;
    OPACITY_PCT.store(pct, Ordering::Relaxed);
    ALPHA.store(pct * 255 / 100, Ordering::Relaxed);
}

/// The live opacity percent (persistence snapshot).
pub fn opacity_percent() -> i32 {
    OPACITY_PCT.load(Ordering::Relaxed) as i32
}

/// Live-set the overlay scale percent (mod-menu row).
pub fn set_scale_percent(pct: i32) {
    SCALE_PCT.store(pct.clamp(50, 150) as u32, Ordering::Relaxed);
}

/// The live scale percent (persistence snapshot).
pub fn scale_percent() -> i32 {
    SCALE_PCT.load(Ordering::Relaxed) as i32
}

/// Monotonic epoch for the flash timestamps.
static EPOCH: Lazy<Instant> = Lazy::new(Instant::now);

fn now_ms() -> u64 {
    EPOCH.elapsed().as_millis() as u64
}

/// Shared monotonic ms clock (touch.rs debounce deadlines use the same
/// epoch as the press-flash timestamps).
pub(super) fn clock_ms() -> u64 {
    now_ms()
}

/// Minimum visual pressed duration so sub-frame taps still flash.
const FLASH_MS: u64 = 150;

/// The built button set (built once at enable; read-only after).
static BUTTONS: OnceCell<Vec<Button>> = OnceCell::new();

// ── Atlas loading (tick pump, render thread) ─────────────────────────

/// Resolved atlas texture id (0 = unresolved).
static ATLAS_TEX: AtomicU32 = AtomicU32::new(0);
/// In-flight load: the pending name hash (0 = none). The AssetHandle is
/// parked in [`ATLAS_HANDLE`] and intentionally never released (the
/// overlay lives for the process).
static ATLAS_PENDING_HASH: AtomicU32 = AtomicU32::new(0);
static ATLAS_HANDLE: Mutex<Option<asset_loader::AssetHandle>> = Mutex::new(None);
static ATLAS_STARTED: AtomicBool = AtomicBool::new(false);
static ATLAS_WARNED: AtomicBool = AtomicBool::new(false);
static ATLAS_LOGGED: AtomicBool = AtomicBool::new(false);
/// Resolve-poll counter for the self-diagnosing timeout.
static ATLAS_POLLS: AtomicU32 = AtomicU32::new(0);
/// One-shot INFO on the first topmost emission (cabinet validation aid).
static FIRST_EMIT_LOGGED: AtomicBool = AtomicBool::new(false);

// ── Lamp reads (lit menu buttons) ────────────────────────────────────

/// Dimlamp array offset in the MdxHWIO object (id 0..28, u32 each —
/// the LAMP CHECK poll's layout, Step 1 RE).
const DIMLAMP_OFFSET: usize = 0x14C8;

/// The live 0..255 lamp value for a player's menu button (dimlamp id =
/// `player*8 + button` — see the module docs). `obj` is the MdxHWIO
/// object address, resolved once per frame (0 ⇒ 0).
fn menu_lamp(obj: usize, player: usize, button: usize) -> u32 {
    if obj == 0 {
        return 0;
    }
    let id = player * 8 + button;
    let v = unsafe { std::ptr::read_volatile((obj + DIMLAMP_OFFSET + id * 4) as *const u32) };
    v.min(255)
}

// ── Colors / fallback look ───────────────────────────────────────────

const FILL_MENU: u32 = 0x00E8E8F0;
const FILL_PINPAD: u32 = 0x00566073;
const FILL_UTILITY: u32 = 0x0020242C;
const FILL_PRESSED: u32 = 0x00FFB040;
const BORDER_NORMAL: u32 = 0x00101014;
const BORDER_PRESSED: u32 = 0x00FF4040;
const BORDER_PX: f32 = 2.0;

/// Compose a quad color: RGB from `rgb`, alpha = base alpha scaled by
/// `scale` percent (clamped).
fn color(rgb: u32, scale: u32) -> u32 {
    let a = (ALPHA.load(Ordering::Relaxed) * scale / 100).min(255);
    (a << 24) | (rgb & 0x00FF_FFFF)
}

/// White-modulate color with an explicit alpha byte (textured cells).
fn white_alpha(a: u32) -> u32 {
    (a.min(255) << 24) | 0x00FF_FFFF
}

// ── Public API (mod lifecycle + touch + injection provider) ──────────

/// Whether a player's overlay buttons are visible (touch hit-testing and
/// rendering both honor this; the toggle is exempt).
pub fn is_visible(player: usize) -> bool {
    VISIBLE[player.min(1)].load(Ordering::Relaxed)
}

/// Injection-provider read: is `bit` held for `player`? Panic-free, O(1).
pub fn bit_held(player: usize, bit: u32) -> bool {
    if player >= 2 || bit as usize >= BIT_COUNT {
        return false;
    }
    HELD[player].load(Ordering::Relaxed) & (1 << bit) != 0
}

/// How long a touch pinpad press reads as "key down" to the game.
/// Physical pinpads are momentary — deploy #16 showed level-based
/// injection reads as a HELD key (visible in the IO test menu), so each
/// touch is converted to one fixed-length pulse; re-pressing requires
/// lifting the finger (the press timestamp only updates on a press edge).
const PINPAD_PULSE_MS: u64 = 120;

/// Injection-provider read for pinpad keys: a fixed-length pulse from
/// the press edge, independent of how long the finger stays down.
pub fn pinpad_pulse_active(player: usize, key: u8) -> bool {
    if player >= 2 || key as usize >= 12 {
        return false;
    }
    let bit = overlay_model::BIT_PINPAD_BASE + key as u32;
    let pressed_at = PRESS_MS[player][bit as usize].load(Ordering::Relaxed);
    pressed_at != 0 && now_ms().saturating_sub(pressed_at) < PINPAD_PULSE_MS
}

/// The built buttons (empty until [`activate`]).
pub fn buttons() -> &'static [Button] {
    BUTTONS.get().map(|v| v.as_slice()).unwrap_or(&[])
}

/// Touch press/release for a button index (from the touch thread).
/// Returns the button plus whether this call was a state EDGE (press
/// while released / release while pressed). IR-frame flutter re-presses
/// a button whose deferred release is still pending — the HELD bit
/// never cleared, so those arrive as `edge == false` and kind-specific
/// press actions (visibility toggle, card-in) must not re-fire.
pub fn set_button_state(index: usize, pressed: bool) -> Option<(&'static Button, bool)> {
    let button = buttons().get(index)?;
    let mask = 1u32 << button.bit;
    let edge;
    if pressed {
        let prev = HELD[button.player].fetch_or(mask, Ordering::AcqRel);
        PRESS_MS[button.player][button.bit as usize].store(now_ms(), Ordering::Relaxed);
        edge = prev & mask == 0;
        if edge && button.kind == ButtonKind::Visibility {
            // Toggle on press edge.
            let v = &VISIBLE[button.player];
            let new = !v.load(Ordering::Relaxed);
            v.store(new, Ordering::Relaxed);
            log_info!(
                "SmxOverlay: P{} overlay {}",
                button.player + 1,
                if new { "shown" } else { "hidden" }
            );
        }
    } else {
        let prev = HELD[button.player].fetch_and(!mask, Ordering::AcqRel);
        edge = prev & mask != 0;
    }
    Some((button, edge))
}

/// Build the button set and arm rendering (the mod's enable). The atlas
/// texture loads lazily from [`tick`] once the asset loader is ready.
pub fn activate(has_card: [bool; 2], opacity: f32, scale_pct: i32) {
    let _ = BUTTONS.set(overlay_model::build_buttons(has_card));
    set_opacity_percent((opacity.clamp(0.0, 1.0) * 100.0).round() as i32);
    SCALE_PCT.store(scale_pct.clamp(50, 150) as u32, Ordering::Relaxed);
    overlay_draw::set_topmost_emitter(emit_topmost);
    ENABLED.store(true, Ordering::Release);
    log_info!(
        "SmxOverlay: activated ({} buttons, alpha={}, scale={}%, topmost_ready={})",
        buttons().len(),
        ALPHA.load(Ordering::Relaxed),
        SCALE_PCT.load(Ordering::Relaxed),
        overlay_draw::topmost_ready()
    );
    if !overlay_draw::topmost_ready() {
        log_warn!("SmxOverlay: topmost emission unavailable -- overlay will not render");
    }
}

/// Disarm rendering + clear all held state (mod disable).
pub fn deactivate() {
    ENABLED.store(false, Ordering::Release);
    overlay_draw::clear_topmost_emitter();
    for p in 0..2 {
        HELD[p].store(0, Ordering::Relaxed);
    }
}

/// Per-frame tick from the mod's `on_frame` callback (render thread):
/// drives the atlas texture load. O(1) once resolved.
pub fn tick() {
    if !ENABLED.load(Ordering::Acquire) || ATLAS_TEX.load(Ordering::Acquire) != 0 {
        return;
    }
    // Issue the load once the loader is up.
    if !ATLAS_STARTED.load(Ordering::Acquire) {
        if !asset_loader::is_available() {
            return;
        }
        match asset_loader::load(atlas::ATLAS_PATH, atlas::ATLAS_STEM) {
            Some(handle) => {
                ATLAS_PENDING_HASH.store(handle.name_hash, Ordering::Release);
                if let Ok(mut slot) = ATLAS_HANDLE.lock() {
                    *slot = Some(handle);
                }
                ATLAS_STARTED.store(true, Ordering::Release);
            }
            None => {
                if !ATLAS_WARNED.swap(true, Ordering::Relaxed) {
                    log_warn!(
                        "SmxOverlay: atlas load refused ({}) -- flat-quad fallback",
                        atlas::ATLAS_PATH
                    );
                }
                ATLAS_STARTED.store(true, Ordering::Release); // don't retry forever
            }
        }
        return;
    }
    // Poll resolution.
    let hash = ATLAS_PENDING_HASH.load(Ordering::Acquire);
    if hash == 0 {
        return;
    }
    if let Some(tex) = asset_loader::resolve_hash(hash) {
        ATLAS_TEX.store(tex.handle, Ordering::Release);
        ATLAS_PENDING_HASH.store(0, Ordering::Release);
        if !ATLAS_LOGGED.swap(true, Ordering::Relaxed) {
            log_info!("SmxOverlay: atlas texture resolved (id={})", tex.handle);
        }
    } else {
        // Self-diagnosing timeout: a normal loose-PNG resolve takes
        // ~43 frames; if it never lands, the registered name doesn't
        // match what we hash (deploy #19: the engine registers the
        // PNG's BASENAME — the stem must equal it) or the file is
        // missing from the game dir.
        let n = ATLAS_POLLS.fetch_add(1, Ordering::Relaxed) + 1;
        if n == 600 && !ATLAS_WARNED.swap(true, Ordering::Relaxed) {
            log_warn!(
                "SmxOverlay: atlas never resolved after {} polls -- is {} deployed? (stem '{}' must equal the PNG basename)",
                n,
                atlas::ATLAS_PATH,
                atlas::ATLAS_STEM
            );
        }
    }
}

// ── The topmost frame emitter ────────────────────────────────────────

/// UV-rect helper: cell `[u0, v0, u1, v1]`.
fn cell_uv(cell: [f32; 4]) -> [f32; 4] {
    cell
}

/// The per-frame topmost emitter (registered with overlay_draw; runs on
/// the render thread right after the layer dispatcher). Builds the whole
/// overlay — textured when the atlas is resolved, flat quads otherwise.
fn emit_topmost() {
    if !ENABLED.load(Ordering::Acquire) {
        return;
    }
    let btns = buttons();
    if btns.is_empty() {
        return;
    }
    let visible = [is_visible(0), is_visible(1)];
    let now = now_ms();
    let atlas_tex = ATLAS_TEX.load(Ordering::Acquire);
    let shader = overlay_draw::default_shader_ptr();
    // The ark IO object, resolved once per frame (lamp reads; the
    // accessor takes a short lock — never per-button).
    let ark_obj = input_manager::io_object_addr();
    let scale = scale();

    let emitted = overlay_draw::with_topmost_writer(|w| {
        w.set_context_2d(1280.0, 720.0, 0.0, 0.0);
        // Deterministic state: the layer's records may have left any
        // shader/blend bound; bind the stock program + the engine's own
        // standard-alpha blend (its list-prefix values).
        if !shader.is_null() {
            w.set_shader(shader as u64, 0);
        }
        w.blend(overlay_draw::encode::BLEND_STANDARD_ALPHA);
        if atlas_tex != 0 && !shader.is_null() {
            w.set_texture(0, atlas_tex, [1.0, 1.0, 0.0, 0.0]);
            let mut quads: Vec<TexQuad> = Vec::with_capacity(btns.len() * 3);
            for b in btns {
                if !visible[b.player] && b.kind != ButtonKind::Visibility {
                    continue;
                }
                build_textured(b, visible, now, ark_obj, scale, &mut quads);
            }
            w.quads_textured(&quads);
        } else {
            let mut quads: Vec<Quad> = Vec::with_capacity(btns.len() * 2);
            for b in btns {
                if !visible[b.player] && b.kind != ButtonKind::Visibility {
                    continue;
                }
                build_flat(b, now, scale, &mut quads);
            }
            w.quads_untextured(&quads);
        }
    });

    if emitted && !FIRST_EMIT_LOGGED.swap(true, Ordering::Relaxed) {
        log_info!(
            "SmxOverlay: topmost overlay emitting (textured={})",
            atlas_tex != 0
        );
    }
}

fn pressed_now(b: &Button, now: u64) -> bool {
    bit_held(b.player, b.bit)
        || now.saturating_sub(PRESS_MS[b.player][b.bit as usize].load(Ordering::Relaxed)) < FLASH_MS
}

/// Textured cells for one button: base face, lamp-lit crossfade (menu
/// buttons), pressed highlight.
fn build_textured(
    b: &Button,
    visible: [bool; 2],
    now: u64,
    ark_obj: usize,
    scale: f32,
    out: &mut Vec<TexQuad>,
) {
    let corners = b.corners(scale, 0.0);
    let base_alpha = ALPHA.load(Ordering::Relaxed);
    let pressed = pressed_now(b, now);

    match b.kind {
        ButtonKind::Menu(btn) => {
            let lamp = menu_lamp(ark_obj, b.player, btn as usize);
            if lamp > 0 {
                // Bloom halo FIRST (behind the face): the glow cell is
                // 2x the button footprint, so inflate the quad by half
                // the button size per side — the halo spills past the
                // bevel and reads through the overlay opacity.
                out.push(TexQuad {
                    corners: b.corners(scale, b.w / 2.0),
                    uv: cell_uv(atlas::MENU_GLOW),
                    color: white_alpha(base_alpha * lamp / 255),
                });
            }
            out.push(TexQuad {
                corners,
                uv: cell_uv(atlas::MENU_OFF),
                color: white_alpha(base_alpha),
            });
            if lamp > 0 {
                // Crossfade the lit face by lamp value (proportional —
                // the real diffuser dims smoothly).
                out.push(TexQuad {
                    corners,
                    uv: cell_uv(atlas::MENU_LIT),
                    color: white_alpha(base_alpha * lamp / 255),
                });
            }
            if pressed {
                out.push(TexQuad {
                    corners,
                    uv: cell_uv(atlas::MENU_PRESSED),
                    color: white_alpha(base_alpha),
                });
            }
        }
        ButtonKind::Pinpad(k) => {
            out.push(TexQuad {
                corners,
                uv: cell_uv(atlas::KEY_CELLS[(k as usize).min(11)]),
                color: white_alpha(base_alpha),
            });
            if pressed {
                out.push(TexQuad {
                    corners,
                    uv: cell_uv(atlas::KEY_PRESSED),
                    color: white_alpha(base_alpha),
                });
            }
        }
        ButtonKind::CardIn | ButtonKind::Visibility => {
            let cell = match b.kind {
                ButtonKind::CardIn => atlas::UTIL_CARD,
                _ if visible[b.player] => atlas::UTIL_HIDE,
                _ => atlas::UTIL_SHOW,
            };
            out.push(TexQuad {
                corners,
                uv: cell_uv(cell),
                color: white_alpha(base_alpha),
            });
            if pressed {
                out.push(TexQuad {
                    corners,
                    uv: cell_uv(atlas::UTIL_PRESSED),
                    color: white_alpha(base_alpha),
                });
            }
        }
    }
}

/// Flat-quad fallback (atlas unresolved): the pre-texture bordered look,
/// legends unavailable.
fn build_flat(b: &Button, now: u64, scale: f32, out: &mut Vec<Quad>) {
    let pressed = pressed_now(b, now);
    let (fill, border) = if pressed {
        (color(FILL_PRESSED, 100), color(BORDER_PRESSED, 100))
    } else {
        let fill_rgb = match b.kind {
            ButtonKind::Menu(_) => FILL_MENU,
            ButtonKind::Pinpad(_) => FILL_PINPAD,
            _ => FILL_UTILITY,
        };
        let fill_alpha = match b.kind {
            ButtonKind::Menu(_) => 60,
            ButtonKind::Pinpad(_) => 80,
            _ => 90,
        };
        (color(fill_rgb, fill_alpha), color(BORDER_NORMAL, 110))
    };
    out.push(Quad {
        corners: b.corners(scale, BORDER_PX),
        color: border,
    });
    out.push(Quad {
        corners: b.corners(scale, 0.0),
        color: fill,
    });
}

// Keep the RecordWriter import tied to the closure signature.
#[allow(unused)]
fn _writer_type_check(w: &mut RecordWriter) {}
