//! GENERATED by scripts/gen_smx_overlay_atlas.py -- do not edit.
//! Normalized UV rects (u0, v0, u1, v1) into the overlay atlas.

/// Atlas texture name stem — MUST equal the PNG basename (the
/// engine's PngFileCallback registers textures under it).
pub const ATLAS_STEM: &str = "smx_overlay_atlas";
/// Atlas path relative to the game working directory.
pub const ATLAS_PATH: &str = "./data_mods/smx_hardware/smx_overlay_atlas.png";

pub const MENU_OFF: [f32; 4] = [0.0, 0.0, 0.25, 0.159204];
pub const MENU_LIT: [f32; 4] = [0.253906, 0.0, 0.503906, 0.159204];
pub const MENU_GLOW: [f32; 4] = [0.0, 0.161692, 0.5, 0.4801];
pub const MENU_PRESSED: [f32; 4] = [0.503906, 0.161692, 0.753906, 0.320896];
pub const KEY_PRESSED: [f32; 4] = [0.757812, 0.161692, 0.945312, 0.281095];
pub const UTIL_PRESSED: [f32; 4] = [0.0, 0.482587, 0.46875, 0.557214];
pub const KEY_7: [f32; 4] = [0.472656, 0.482587, 0.660156, 0.60199];
pub const KEY_8: [f32; 4] = [0.664062, 0.482587, 0.851562, 0.60199];
pub const KEY_9: [f32; 4] = [0.0, 0.604478, 0.1875, 0.723881];
pub const KEY_4: [f32; 4] = [0.191406, 0.604478, 0.378906, 0.723881];
pub const KEY_5: [f32; 4] = [0.382812, 0.604478, 0.570312, 0.723881];
pub const KEY_6: [f32; 4] = [0.574219, 0.604478, 0.761719, 0.723881];
pub const KEY_1: [f32; 4] = [0.765625, 0.604478, 0.953125, 0.723881];
pub const KEY_2: [f32; 4] = [0.0, 0.726368, 0.1875, 0.845771];
pub const KEY_3: [f32; 4] = [0.191406, 0.726368, 0.378906, 0.845771];
pub const KEY_0: [f32; 4] = [0.382812, 0.726368, 0.570312, 0.845771];
pub const KEY_00: [f32; 4] = [0.574219, 0.726368, 0.761719, 0.845771];
pub const KEY_BLANK: [f32; 4] = [0.765625, 0.726368, 0.953125, 0.845771];
pub const UTIL_CARD: [f32; 4] = [0.0, 0.848259, 0.46875, 0.922886];
pub const UTIL_HIDE: [f32; 4] = [0.472656, 0.848259, 0.941406, 0.922886];
pub const UTIL_SHOW: [f32; 4] = [0.0, 0.925373, 0.46875, 1.0];

/// Pinpad key cells indexed by the 10-key buffer index
/// (0..=9 digits, 10 = "00", 11 = the blank decimal key).
pub const KEY_CELLS: [[f32; 4]; 12] = [
    KEY_0, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_00, KEY_BLANK,
];
