#!/usr/bin/env python3
"""Extract assets from DDR Ultramix / Dancing Stage Unleashed archive files.

Two core archive formats are supported, both flat and sector-aligned to 0x800:

    x_data bin (textures, charts, song-info files, etc.)
      The table-of-contents comes in one of two forms, per game:

      "xbe"  (Ultramix) — a static array embedded in default.xbe.
             Each 16-byte entry: { name_va, size, size_aligned, offset }.
             `name_va` points at a NUL-terminated Shift-JIS filename in the
             XBE; it is resolved to a file offset via the XBE section headers.

      "hbn"  (Dancing Stage Unleashed 2) — a CRLF text sidecar next to the
             bin (x_data_<region>.hbn, written by Konami's x_bincat tool):
                 Konami Computer Entertainment Hawaii, Inc.
                 !! This file is auto-generated by x_bincat. ... !!
                 <count>
                 <name>,<offset>,<size>,<size_aligned>     (x count)
                 <largest size_aligned>
             Parsed by the XBE's loader (DSU2 default.xbe FUN_00056f90),
             which is what this parser mirrors.

    music sng (audio streams; XBOX-IMA ADPCM, 44.1 kHz stereo, headerless)
      The table-of-contents lives inside the archive itself, at a per-game
      offset: sector 0 for Ultramix; sector 1 (0x800) for DSU2, whose sector 0
      holds only the "Konami Computer Entertainment Hawaii, Inc." magic plus
      packer-tool padding (DSU2 default.xbe FUN_000b8000).
      Layout: u32 count, then `count` 20-byte entries of
      { tag[4], offset, size, loop_offset, loop_size }.
      `loop_*` describes a looping preview stream for song-wheel (zero for
      UI/non-song audio). Main streams are extracted as `{tag}.wavm`,
      loops as `{tag}_loop.wavm`.
      DSU3 uses the DSU2 layout, but one of its entries is a comment line ("// Begin US ")
      from the packer's input list. The game looks streams up by tag and never reads it, so
      the parser skips any entry whose tag starts with "//".

DSU2 and DSU3 also ship two more archive types (both optional per game):

    resource krc/krh (UI/stage textures; DSU2 default.xbe FUN_00095150)
      The .krc is a standard Xbox XPR0 bundle: { "XPR0", total_size,
      header_size }, then one 20-byte D3D resource header per texture
      { common, data, lock, format, size }, terminated by 0xFFFFFFFF. Texture
      bytes live at header_size + data. The .krh text sidecar names the
      resources in order ("#define *_texture_<name>_OFFSET <index*20>UL").
      Only linear DXT textures occur (and the game only accepts textures), so
      each is written as a plain .dds under resource/.

    voice BKT (announcer banks; DSU2 default.xbe FUN_000b6fd0/FUN_000b7030)
      Header { header_size, group_count, clip_count, group_off, clip_off }.
      Groups are { u16 first_clip, u8 play_chance, u8 clip_count }: the game
      plays a random clip of the group when rand_byte <= play_chance (255 =
      always). Clips are { start, end } byte ranges, followed by one kind byte
      per clip selecting the DirectSound voice pool (FUN_000b9f50):
      0 = PCM16 mono 22050 Hz, 1 = PCM16 stereo 22050 Hz, 2 = Xbox ADPCM
      stereo 44100 Hz. Clips are extracted raw (headerless) under
      voice/<bank>/g<group>_<n>.<ext>: `.pcm` for the PCM kinds and `.wavm`
      for Xbox ADPCM, so only true .sng-style streams carry the .wavm name.
      voice_manifest.csv records each clip's codec, channels and sample rate.

Dancing Stage Unleashed 3 (dsu3_eu) uses the same x_data, krc and BKT formats as DSU2.
Only VCLIP_M_e.BKT is in the rip. The XBE also names VCLIP_e and VCLIP_B_e, but those files
are not on the disc. Every DSU3 clip is kind 1 (PCM16 stereo).

DDR ULTRAMIX 4 (ultramix4_us) is the DSU3 layout again, with the files renamed per platform
(`*_XBOX_US.*`). Its music is split over four .sng archives (`music_XBOX_US_1..4.sng`), each
with its own TOC at 0x800; their tags are disjoint, so all streams land in one directory and
sng_manifest.csv records the source archive per stream. The voice bank sits at the disc root
(`VCLIP_M.BKT`).

Usage:
    extract_ultramix_data.py <game> <game_dir> <out_dir>

Examples:
    extract_ultramix_data.py ultramix_us ~/Desktop/ultramix ./extracted
    extract_ultramix_data.py dsu2_eu ~/Desktop/dsu2 ./extracted_dsu2
    extract_ultramix_data.py dsu3_eu ~/Desktop/dsu3 ~/Desktop/dsu3/extracted_full
    extract_ultramix_data.py ultramix4_us ~/Desktop/"DDR ISOs"/ultramix_4 ~/Desktop/"DDR ISOs"/ultramix_4/extracted_full
"""

import argparse
import csv
import struct
import sys
from pathlib import Path

# Per-game parameters, discovered by reverse-engineering default.xbe.
#   xdata_toc:                      "xbe" (static array in default.xbe) or "hbn" (text sidecar)
#   xdata_toc_offset / xdata_count: [xbe only] TOC file offset and entry count in the XBE
#   xdata_hbn:                      [hbn only] TOC sidecar filename in game dir
#   xdata_bin:                      x_data bin filename in game dir
#   sng:                            music .sng filename in game dir, or a list of them (one TOC each)
#   sng_toc_offset:                 file offset of the .sng TOC (u32 count + entries)
#   magic:                          [optional] header the game checks at offset 0 of the
#                                   bin and .sng before trusting them
#   krc:                            [optional] (bundle, name sidecar) texture resource files
#   voice_banks:                    [optional] BKT voice bank paths, relative to game dir
GAMES = {
    "ultramix_us": {
        "xdata_toc": "xbe",
        "xdata_toc_offset": 0x1AD890,
        "xdata_count": 737,
        "xdata_bin": "x_data_US.bin",
        "sng": "music_US.sng",
        "sng_toc_offset": 0,
    },
    "dsu1_eu": {
        "xdata_toc": "xbe",
        "xdata_toc_offset": 0x1B06B0,
        "xdata_count": 737,
        "xdata_bin": "x_data_UK.bin",
        "sng": "music_UK.sng",
        "sng_toc_offset": 0,
    },
    "dsu2_eu": {
        "xdata_toc": "hbn",
        "xdata_hbn": "x_data_EU.hbn",
        "xdata_bin": "x_data_EU.bin",
        "sng": "music_EU.sng",
        "sng_toc_offset": 0x800,
        "magic": b"Konami Computer Entertainment Hawaii, Inc.",
        "krc": ("resource_EU.krc", "resource_EU.krh"),
        "voice_banks": ["voice/VCLIP_e.BKT", "voice/VCLIP_M_e.BKT", "voice/VCLIP_B_e.BKT"],
    },
    "dsu3_eu": {
        "xdata_toc": "hbn",
        "xdata_hbn": "x_data_EU.hbn",
        "xdata_bin": "x_data_EU.bin",
        "sng": "music_EU.sng",
        "sng_toc_offset": 0x800,
        "magic": b"Konami Computer Entertainment Hawaii, Inc.",
        "krc": ("resource_EU.krc", "resource_EU.krh"),
        "voice_banks": ["voice/VCLIP_M_e.BKT"],
    },
    "ultramix4_us": {
        "xdata_toc": "hbn",
        "xdata_hbn": "x_data_XBOX_US.hbn",
        "xdata_bin": "x_data_XBOX_US.bin",
        "sng": [f"music_XBOX_US_{n}.sng" for n in range(1, 5)],
        "sng_toc_offset": 0x800,
        "magic": b"Konami Computer Entertainment Hawaii, Inc.",
        "krc": ("resource_XBOX_US.krc", "resource_XBOX_US.krh"),
        "voice_banks": ["VCLIP_M.BKT"],
    },
}

XBE_SECTION_HEADER_SIZE = 56
SNG_TOC_ENTRY_SIZE = 20

XPR_RESOURCE_HEADER_SIZE = 20
XPR_END_MARKER = 0xFFFFFFFF
D3DCOMMON_TYPE_MASK = 0x70000
D3DCOMMON_TYPE_TEXTURE = 0x40000
# Xbox D3DFORMAT -> (DDS FourCC, bytes per 4x4 block). DXT2/3 and DXT4/5 share
# a format code on Xbox (premultiplied-ness isn't encoded); emit the plain one.
XBOX_DXT_FORMATS = {0x0C: (b"DXT1", 8), 0x0E: (b"DXT3", 16), 0x0F: (b"DXT5", 16)}

BKT_HEADER_SIZE = 20
BKT_GROUP_SIZE = 4
BKT_CLIP_SIZE = 8
# BKT clip kind -> (file extension, codec, channels, sample rate), from the
# DirectSound voice pools the kind selects in FUN_000b9f50 / FUN_000b73c0.
BKT_CLIP_FORMATS = {
    0: ("pcm", "pcm_s16le", 1, 22050),
    1: ("pcm", "pcm_s16le", 2, 22050),
    2: ("wavm", "xbox_adpcm", 2, 44100),
}


class ArchiveError(Exception):
    """An archive or TOC doesn't match what the game config expects."""


def xbe_va_to_file_offset(xbe_bytes):
    """Return a function mapping an XBE virtual address to its offset in the file.

    Each section is loaded at a different VA-to-file delta, so the mapping is
    taken from the section headers rather than hardcoded per game.
    """
    if xbe_bytes[:4] != b"XBEH":
        raise ArchiveError("default.xbe is missing the XBEH magic")
    (base_va,) = struct.unpack_from("<I", xbe_bytes, 0x104)
    section_count, section_headers_va = struct.unpack_from("<II", xbe_bytes, 0x11C)

    sections = []
    for i in range(section_count):
        header_off = section_headers_va - base_va + i * XBE_SECTION_HEADER_SIZE
        _flags, va, _virtual_size, raw_offset, raw_size = struct.unpack_from(
            "<IIIII", xbe_bytes, header_off
        )
        sections.append((va, raw_offset, raw_size))

    def to_file_offset(va):
        for section_va, raw_offset, raw_size in sections:
            if section_va <= va < section_va + raw_size:
                return raw_offset + (va - section_va)
        raise ArchiveError(f"address 0x{va:x} is not inside any XBE section")

    return to_file_offset


def check_output_name(name, source):
    """Reject names that can't safely be used as a file in the output dir.

    A bad name almost always means the TOC location or format is wrong for this
    game, so fail before anything is written rather than emit junk files.
    """
    if not name or name in (".", "..") or any(c in name for c in "/\\:") or not name.isprintable():
        raise ArchiveError(
            f"{source}: implausible filename {name!r}; "
            "the TOC settings in GAMES probably don't match this game's files"
        )


def read_exact(f, offset, size, what):
    f.seek(offset)
    data = f.read(size)
    if len(data) != size:
        raise ArchiveError(f"{what}: expected {size} bytes at 0x{offset:x}, file ends after {len(data)}")
    return data


def parse_xdata_toc(xbe_bytes, toc_offset, count):
    """Yield (name, size, offset) for each non-empty x_data TOC entry."""
    to_file_offset = xbe_va_to_file_offset(xbe_bytes)
    for i in range(count):
        name_va, size, _size_aligned, offset = struct.unpack_from("<IIII", xbe_bytes, toc_offset + i * 16)
        if name_va == 0 and size == 0 and offset == 0:
            continue  # unused slot
        name_off = to_file_offset(name_va)
        end = xbe_bytes.find(b"\x00", name_off)
        if end == -1:
            raise ArchiveError(f"x_data TOC entry {i}: filename at 0x{name_off:x} is not NUL-terminated")
        try:
            name = xbe_bytes[name_off:end].decode("cp932")
        except UnicodeDecodeError:
            raise ArchiveError(f"x_data TOC entry {i}: filename at 0x{name_off:x} is not valid Shift-JIS") from None
        check_output_name(name, f"x_data TOC entry {i}")
        yield name, size, offset


def parse_hbn_toc(hbn_bytes, magic):
    """Yield (name, size, offset) for each entry of an x_bincat .hbn TOC."""
    lines = hbn_bytes.split(b"\r\n")
    if len(lines) < 3 or (magic is not None and lines[0] != magic):
        raise ArchiveError(".hbn is missing the Konami header line")
    try:
        count = int(lines[2])
    except ValueError:
        raise ArchiveError(f".hbn entry count {lines[2]!r} is not a number") from None
    if len(lines) < 3 + count:
        raise ArchiveError(f".hbn declares {count} entries but has only {len(lines) - 3} lines")
    for i, line in enumerate(lines[3 : 3 + count]):
        fields = line.split(b",")
        if len(fields) != 4:
            raise ArchiveError(f".hbn entry {i}: expected name,offset,size,size_aligned, got {line!r}")
        try:
            name = fields[0].decode("cp932")
            offset, size, _size_aligned = (int(v) for v in fields[1:])
        except (UnicodeDecodeError, ValueError):
            raise ArchiveError(f".hbn entry {i}: malformed line {line!r}") from None
        check_output_name(name, f".hbn entry {i}")
        yield name, size, offset


def parse_sng_toc(sng_f, toc_offset, skipped=None):
    """Yield (tag, offset, size, loop_offset, loop_size) for each .sng entry.

    Entries whose tag starts with "//" are comment lines from the packer's input list that leaked
    into the TOC (DSU3 has one: the 20 bytes spell "// Begin US "). The game finds streams by tag,
    so it never reads them; they are skipped, and their text is appended to `skipped` if given.
    """
    (count,) = struct.unpack("<I", read_exact(sng_f, toc_offset, 4, "sng TOC count"))
    toc_bytes = read_exact(sng_f, toc_offset + 4, count * SNG_TOC_ENTRY_SIZE, "sng TOC")
    for i in range(count):
        raw = toc_bytes[i * SNG_TOC_ENTRY_SIZE : (i + 1) * SNG_TOC_ENTRY_SIZE]
        if raw.startswith(b"//"):
            if skipped is not None:
                skipped.append(raw.rstrip(b"\x00").decode("ascii", "replace"))
            continue
        tag, offset, size, loop_offset, loop_size = struct.unpack("<4sIIII", raw)
        try:
            tag = tag.decode("ascii")
        except UnicodeDecodeError:
            raise ArchiveError(f"sng TOC entry {i}: tag {tag!r} is not ASCII") from None
        check_output_name(tag, f"sng TOC entry {i}")
        yield tag, offset, size, loop_offset, loop_size


def parse_krh_names(krh_text):
    """Return texture names from a .krh sidecar, in resource order.

    Mirrors the game: header line, then `#define *_NUM_RESOURCES N`, then one
    `#define *_texture_<name>_OFFSET <index*20>UL` line per resource.
    """
    lines = krh_text.splitlines()
    if not lines or not lines[0].startswith("// Automatically generated by the bundler tool from"):
        raise ArchiveError(".krh is missing the bundler header line")
    count = None
    names = []
    for line in lines[1:]:
        if line.startswith("#define *_NUM_RESOURCES "):
            count = int(line.split()[2].rstrip("UL"))
        elif line.startswith("#define *_texture_"):
            macro, value = line.split()[1:3]
            if not macro.endswith("_OFFSET"):
                raise ArchiveError(f".krh: unexpected define {line!r}")
            name = macro[len("*_texture_") : -len("_OFFSET")]
            offset = int(value.rstrip("UL"))
            if offset != len(names) * XPR_RESOURCE_HEADER_SIZE:
                raise ArchiveError(f".krh: {name} has offset {offset}, expected {len(names) * XPR_RESOURCE_HEADER_SIZE}")
            check_output_name(name, ".krh")
            names.append(name)
    if count is None or count != len(names):
        raise ArchiveError(f".krh declares {count} resources but names {len(names)}")
    return names


def dxt_chain_size(width, height, mips, block_bytes):
    return sum(max(1, (width >> m) // 4) * max(1, (height >> m) // 4) * block_bytes for m in range(mips))


def parse_krc(krc_bytes, names):
    """Yield (name, fourcc, width, height, mips, data) for each XPR0 texture."""
    if len(krc_bytes) < 12:
        raise ArchiveError(".krc is truncated")
    magic, total_size, header_size = struct.unpack_from("<4sII", krc_bytes, 0)
    if magic != b"XPR0" or total_size != len(krc_bytes):
        raise ArchiveError(".krc is not an XPR0 bundle of the expected size")
    headers = []
    pos = 12
    while struct.unpack_from("<I", krc_bytes, pos)[0] != XPR_END_MARKER:
        headers.append(struct.unpack_from("<5I", krc_bytes, pos))
        pos += XPR_RESOURCE_HEADER_SIZE
    if len(headers) != len(names):
        raise ArchiveError(f".krc has {len(headers)} resources but .krh names {len(names)}")

    for name, (common, data, _lock, fmt, size) in zip(names, headers):
        if common & D3DCOMMON_TYPE_MASK != D3DCOMMON_TYPE_TEXTURE:
            raise ArchiveError(f".krc {name}: resource is not a texture (common=0x{common:x})")
        d3dfmt = (fmt >> 8) & 0xFF
        if d3dfmt not in XBOX_DXT_FORMATS or size != 0 or fmt & 0x4 or (fmt >> 4) & 0xF != 2:
            raise ArchiveError(f".krc {name}: unsupported texture format 0x{fmt:x} (only 2D DXT)")
        fourcc, block_bytes = XBOX_DXT_FORMATS[d3dfmt]
        mips = (fmt >> 16) & 0xF
        width, height = 1 << ((fmt >> 20) & 0xF), 1 << ((fmt >> 24) & 0xF)
        start = header_size + data
        end = start + dxt_chain_size(width, height, mips, block_bytes)
        if end > len(krc_bytes):
            raise ArchiveError(f".krc {name}: texture data runs past end of file")
        yield name, fourcc, width, height, mips, krc_bytes[start:end]


def dds_header(fourcc, width, height, mips, block_bytes):
    """Build a DDS header for a linear DXT texture."""
    DDSD_CAPS, DDSD_HEIGHT, DDSD_WIDTH, DDSD_PIXELFORMAT = 0x1, 0x2, 0x4, 0x1000
    DDSD_MIPMAPCOUNT, DDSD_LINEARSIZE = 0x20000, 0x80000
    DDSCAPS_COMPLEX, DDSCAPS_TEXTURE, DDSCAPS_MIPMAP = 0x8, 0x1000, 0x400000
    flags = DDSD_CAPS | DDSD_HEIGHT | DDSD_WIDTH | DDSD_PIXELFORMAT | DDSD_LINEARSIZE
    caps = DDSCAPS_TEXTURE
    if mips > 1:
        flags |= DDSD_MIPMAPCOUNT
        caps |= DDSCAPS_COMPLEX | DDSCAPS_MIPMAP
    linear_size = dxt_chain_size(width, height, 1, block_bytes)
    pixel_format = struct.pack("<II4s5I", 32, 0x4, fourcc, 0, 0, 0, 0, 0)  # DDPF_FOURCC
    return (
        b"DDS "
        + struct.pack("<7I", 124, flags, height, width, linear_size, 0, mips)
        + b"\x00" * 44
        + pixel_format
        + struct.pack("<5I", caps, 0, 0, 0, 0)
    )


def parse_bkt(bkt_f, what):
    """Yield (group, play_chance, index_in_group, clip, kind, start, end) for a voice bank."""
    header_size, group_count, clip_count, group_off, clip_off = struct.unpack(
        "<5I", read_exact(bkt_f, 0, BKT_HEADER_SIZE, f"{what} header")
    )
    if group_off + group_count * BKT_GROUP_SIZE != clip_off or clip_off + clip_count * BKT_CLIP_SIZE != header_size:
        raise ArchiveError(f"{what}: header tables don't line up; not a BKT voice bank?")
    table = read_exact(bkt_f, 0, header_size + clip_count, f"{what} tables")
    kinds = table[header_size : header_size + clip_count]
    clips = [struct.unpack_from("<II", table, clip_off + i * BKT_CLIP_SIZE) for i in range(clip_count)]
    bkt_f.seek(0, 2)
    file_size = bkt_f.tell()

    for group in range(group_count):
        first, play_chance, count = struct.unpack_from("<HBB", table, group_off + group * BKT_GROUP_SIZE)
        if first + count > clip_count:
            raise ArchiveError(f"{what}: group {group} references clips past the clip table")
        for n in range(count):
            clip = first + n
            start, end = clips[clip]
            if not start <= end <= file_size:
                raise ArchiveError(f"{what}: clip {clip} range 0x{start:x}-0x{end:x} is outside the file")
            if kinds[clip] not in BKT_CLIP_FORMATS:
                raise ArchiveError(f"{what}: clip {clip} has unknown kind {kinds[clip]}")
            yield group, play_chance, n, clip, kinds[clip], start, end


def extract_xdata(entries, bin_path, out_dir):
    """Extract x_data bin contents and write a manifest. Returns file count."""
    written = 0
    with open(bin_path, "rb") as bin_f, open(out_dir / "xdata_manifest.csv", "w", newline="") as mf:
        w = csv.writer(mf)
        w.writerow(["name", "size", "offset"])
        for name, size, offset in entries:
            w.writerow([name, size, f"0x{offset:x}"])
            if size == 0:
                continue
            (out_dir / name).write_bytes(read_exact(bin_f, offset, size, name))
            written += 1
    return written


def extract_sng(archives, out_dir):
    """Extract .sng audio streams as {tag}.wavm and {tag}_loop.wavm. Returns file count.

    `archives` is a list of (sng_path, entries); the manifest names each stream's archive.
    """
    written = 0
    with open(out_dir / "sng_manifest.csv", "w", newline="") as mf:
        w = csv.writer(mf)
        w.writerow(["tag", "stream", "size", "offset", "archive"])
        for sng_path, entries in archives:
            with open(sng_path, "rb") as sng_f:
                for tag, offset, size, loop_offset, loop_size in entries:
                    for suffix, off, sz in [("", offset, size), ("_loop", loop_offset, loop_size)]:
                        if sz == 0:
                            continue
                        out_name = f"{tag}{suffix}.wavm"
                        (out_dir / out_name).write_bytes(read_exact(sng_f, off, sz, out_name))
                        w.writerow([tag, suffix.lstrip("_") or "main", sz, f"0x{off:x}", sng_path.name])
                        written += 1
    return written


def extract_krc(textures, out_dir):
    """Write krc textures as resource/<name>.dds and a manifest. Returns file count."""
    tex_dir = out_dir / "resource"
    tex_dir.mkdir(exist_ok=True)
    written = 0
    with open(out_dir / "resource_manifest.csv", "w", newline="") as mf:
        w = csv.writer(mf)
        w.writerow(["name", "format", "width", "height", "mips"])
        for name, fourcc, width, height, mips, data in textures:
            block_bytes = 8 if fourcc == b"DXT1" else 16
            (tex_dir / f"{name}.dds").write_bytes(dds_header(fourcc, width, height, mips, block_bytes) + data)
            w.writerow([name, fourcc.decode(), width, height, mips])
            written += 1
    return written


def extract_voice(banks, out_dir):
    """Extract raw BKT clips under voice/<bank>/ and a manifest. Returns file count."""
    written = 0
    with open(out_dir / "voice_manifest.csv", "w", newline="") as mf:
        w = csv.writer(mf)
        w.writerow(["bank", "group", "play_chance", "clip", "file", "codec", "channels", "sample_rate", "size", "offset"])
        for bank_path, entries in banks:
            bank = bank_path.stem
            bank_dir = out_dir / "voice" / bank
            bank_dir.mkdir(parents=True, exist_ok=True)
            with open(bank_path, "rb") as bkt_f:
                for group, play_chance, n, clip, kind, start, end in entries:
                    ext, codec, channels, rate = BKT_CLIP_FORMATS[kind]
                    out_name = f"g{group:03d}_{n:02d}.{ext}"
                    (bank_dir / out_name).write_bytes(read_exact(bkt_f, start, end - start, f"{bank} clip {clip}"))
                    w.writerow([bank, group, play_chance, clip, f"voice/{bank}/{out_name}", codec, channels, rate,
                                end - start, f"0x{start:x}"])
                    written += 1
    return written


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("game", choices=sorted(GAMES), help="game identifier")
    ap.add_argument("game_dir", type=Path, help="game rip directory (default.xbe or x_data .hbn, x_data bin, music .sng(s), and any per-game extras)")
    ap.add_argument("out_dir", type=Path, help="output directory for extracted files")
    args = ap.parse_args()

    cfg = GAMES[args.game]
    xbe_path = args.game_dir / "default.xbe"
    bin_path = args.game_dir / cfg["xdata_bin"]
    sng_names = [cfg["sng"]] if isinstance(cfg["sng"], str) else cfg["sng"]
    sng_paths = [args.game_dir / n for n in sng_names]
    toc_path = xbe_path if cfg["xdata_toc"] == "xbe" else args.game_dir / cfg["xdata_hbn"]
    krc_paths = [args.game_dir / p for p in cfg.get("krc", ())]
    bank_paths = [args.game_dir / p for p in cfg.get("voice_banks", ())]
    for p in (toc_path, bin_path, *sng_paths, *krc_paths, *bank_paths):
        if not p.is_file():
            sys.exit(f"error: {p} not found")

    try:
        # Parse and validate every TOC up front so a bad config writes nothing.
        magic = cfg.get("magic")
        if magic is not None:
            for p in (bin_path, *sng_paths):
                with open(p, "rb") as f:
                    if f.read(len(magic)) != magic:
                        raise ArchiveError(f"{p.name} is missing the Konami header; wrong game/region?")
        if cfg["xdata_toc"] == "xbe":
            xdata_entries = list(
                parse_xdata_toc(toc_path.read_bytes(), cfg["xdata_toc_offset"], cfg["xdata_count"])
            )
        else:
            xdata_entries = list(parse_hbn_toc(toc_path.read_bytes(), magic))
        sng_skipped = []
        sng_archives = []
        sng_tags = {}
        for sng_path in sng_paths:
            with open(sng_path, "rb") as sng_f:
                sng_entries = list(parse_sng_toc(sng_f, cfg["sng_toc_offset"], sng_skipped))
                sng_f.seek(0, 2)
                sng_size = sng_f.tell()
            for tag, offset, size, loop_offset, loop_size in sng_entries:
                if offset + size > sng_size or loop_offset + loop_size > sng_size:
                    raise ArchiveError(f"sng TOC entry {tag!r} points past the end of {sng_path.name}")
                if tag in sng_tags:
                    raise ArchiveError(f"sng tag {tag!r} is in both {sng_tags[tag]} and {sng_path.name}")
                sng_tags[tag] = sng_path.name
            sng_archives.append((sng_path, sng_entries))
        textures = []
        if krc_paths:
            krc_path, krh_path = krc_paths
            names = parse_krh_names(krh_path.read_text(encoding="ascii"))
            textures = list(parse_krc(krc_path.read_bytes(), names))
        banks = []
        for p in bank_paths:
            with open(p, "rb") as bkt_f:
                banks.append((p, list(parse_bkt(bkt_f, p.name))))

        args.out_dir.mkdir(parents=True, exist_ok=True)
        xdata_count = extract_xdata(xdata_entries, bin_path, args.out_dir)
        sng_count = extract_sng(sng_archives, args.out_dir)
        krc_count = extract_krc(textures, args.out_dir) if krc_paths else None
        voice_count = extract_voice(banks, args.out_dir) if banks else None
    except ArchiveError as e:
        sys.exit(f"error: {e}")

    print(f"x_data:  {xdata_count} files (manifest: xdata_manifest.csv)")
    print(f"sng:     {sng_count} files from {len(sng_archives)} archive(s) (manifest: sng_manifest.csv)")
    for text in sng_skipped:
        print(f"         skipped TOC comment entry {text!r}")
    if krc_count is not None:
        print(f"krc:     {krc_count} textures (manifest: resource_manifest.csv)")
    if voice_count is not None:
        print(f"voice:   {voice_count} clips from {len(banks)} banks (manifest: voice_manifest.csv)")
    print(f"output:  {args.out_dir}")


if __name__ == "__main__":
    main()
