#!/usr/bin/env bash
# Offline validation for the S-Marvelous pure layers (implementation plan
# `.agents/planning/2026-08-29-s-marvelous-judgement/implementation/plan.md`
# — the classification state machine and the core/ap2 AFP editor).
#
# Usage:
#   ./scripts/validate_s_marvelous.sh
#
# Always-on: the synthetic host-test suite (state machine + core/ap2
# round-trip/model tests) in a throwaway temp-dir cargo crate — plain
# `cargo test` cannot run on non-x86 hosts (the `retour` dependency only
# compiles for x86/x86_64), so the harness mounts the feature's
# dependency-free modules via `#[path]` and runs their `#[cfg(test)]`
# suites there.
#
# Optional DEV LEGS (skipped with a notice when prerequisites are absent;
# never required for CI/other machines):
#   Leg A — real-template round-trip: extracts AFP templates from the game
#     install (env `DDR_WORLD_INSTALL` = game contents root containing
#     `data/`), descrambles them (BSI + string-table cipher), and asserts
#     `serialize(parse(x)) == x` byte-identically per template.
#   Leg B — bemaniutils cross-check: parses the same descrambled templates
#     with bemaniutils `afputils parseafp` (env `BEMANIUTILS_DIR`, default
#     sibling `../bemaniutils`) and compares structural invariants
#     (exported name, frame count, per-frame tag spans).
# Both legs run entirely in temp dirs and write nothing into the
# repository; no Konami bytes are ever committed.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }
skip() { echo "[skip] $*"; }

# module name -> repo-relative source path. Names must be unique.
declare -a MODULE_NAMES=(s_marvelous_state)
declare -a MODULE_PATHS=("src/mods/s_marvelous/state.rs")
# avs_layeredfs/afplist_ext (std-only afplist <geo> list transform — the
# deploy-#4 geo-registration fix; mounted for its test suite).
if [[ -r "$REPO_ROOT/src/services/avs_layeredfs/afplist_ext.rs" ]]; then
  MODULE_NAMES+=(afplist_ext)
  MODULE_PATHS+=("src/services/avs_layeredfs/afplist_ext.rs")
fi
# core/geo (GE2D label primitives — std-only, mounted for its test suite
# and consumed by the ap2check dev binary's geo-rewrite mode).
if [[ -r "$REPO_ROOT/src/core/geo.rs" ]]; then
  MODULE_NAMES+=(geo)
  MODULE_PATHS+=("src/core/geo.rs")
fi
# core/ap2 mounts here when plan Step 2 lands.
HAVE_AP2=0
if [[ -r "$REPO_ROOT/src/core/ap2/mod.rs" ]]; then
  MODULE_NAMES+=(ap2)
  MODULE_PATHS+=("src/core/ap2/mod.rs")
  HAVE_AP2=1
fi

for p in "${MODULE_PATHS[@]}"; do
  [[ -r "$REPO_ROOT/$p" ]] || die "module source missing: $p"
done

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<EOF
[package]
name = "s-marvelous-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ap2check"
path = "src/main.rs"

[workspace]
EOF

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness — generated by"
  echo "//! scripts/validate_s_marvelous.sh; never committed."
  echo "#![allow(dead_code)]"
  for i in "${!MODULE_NAMES[@]}"; do
    echo "#[path = \"$REPO_ROOT/${MODULE_PATHS[$i]}\"]"
    echo "pub mod ${MODULE_NAMES[$i]};"
  done
} >"$TMP/src/lib.rs"

# The ap2check dev binary (Legs A/B). Compiled unconditionally (cheap, keeps
# the mounts honest) but only EXECUTED by the dev legs.
if [[ "$HAVE_AP2" == 1 ]]; then
  cat >"$TMP/src/main.rs" <<EOF
//! ap2check — dev-leg binary for validate_s_marvelous.sh. Never committed.
#![allow(dead_code)]
#[path = "$REPO_ROOT/src/core/ap2/mod.rs"]
mod ap2;
#[path = "$REPO_ROOT/src/core/afp.rs"]
mod afp;
#[path = "$REPO_ROOT/src/core/geo.rs"]
mod geo;

/// BSI byteswap + string-table cipher removal — the same "fully
/// descrambled" shape the game's afp_patcher seam sees (docs/afp_system.md
/// §1). String table region: offset @48, size @52 (u32 LE).
fn descramble(afp_path: &str, bsi_path: &str) -> Option<Vec<u8>> {
    let mut data = std::fs::read(afp_path).ok()?;
    let bsi = std::fs::read(bsi_path).ok()?;
    afp::apply_bsi(&mut data, &bsi);
    let st_off = u32::from_le_bytes(data.get(48..52)?.try_into().ok()?) as usize;
    let st_size = u32::from_le_bytes(data.get(52..56)?.try_into().ok()?) as usize;
    let table = data.get(st_off..st_off.checked_add(st_size)?)?.to_vec();
    let plain = ap2::decode_string_table(&table);
    data[st_off..st_off + st_size].copy_from_slice(&plain);
    Some(data)
}

fn file_name(p: &str) -> String {
    std::path::Path::new(p)
        .file_name()
        .map(|f| f.to_string_lossy().into_owned())
        .unwrap_or_else(|| p.to_string())
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mode = args.first().map(String::as_str).unwrap_or("");
    if mode == "edit-demo" {
        if args.len() != 5 {
            eprintln!("usage: ap2check edit-demo <afp> <bsi> <out_afp> <out_bsi>");
            std::process::exit(2);
        }
        std::process::exit(edit_demo(&args[1], &args[2], &args[3], &args[4]));
    }
    if mode == "smarv-patch" {
        if args.len() != 5 {
            eprintln!("usage: ap2check smarv-patch <afp> <bsi> <geo_dir> <out_afp>");
            std::process::exit(2);
        }
        std::process::exit(smarv_patch(&args[1], &args[2], &args[3], &args[4]));
    }
    if mode == "geo-rewrite" {
        if args.len() != 5 {
            eprintln!("usage: ap2check geo-rewrite <geo_in> <old_label> <new_label> <geo_out>");
            std::process::exit(2);
        }
        std::process::exit(geo_rewrite(&args[1], &args[2], &args[3], &args[4]));
    }
    let pairs = &args[1..];
    if !matches!(mode, "roundtrip" | "info") || pairs.len() % 2 != 0 {
        eprintln!("usage: ap2check roundtrip|info <afp> <bsi> [<afp> <bsi> ...]");
        std::process::exit(2);
    }
    let mut fail = 0u32;
    for pair in pairs.chunks(2) {
        let name = file_name(&pair[0]);
        let Some(data) = descramble(&pair[0], &pair[1]) else {
            println!("FAIL {name}: descramble");
            fail += 1;
            continue;
        };
        let Some(doc) = ap2::Ap2Doc::parse(&data) else {
            println!("FAIL {name}: parse -> None");
            fail += 1;
            continue;
        };
        match mode {
            "roundtrip" => {
                let Some(out) = doc.serialize() else {
                    println!("FAIL {name}: serialize -> None");
                    fail += 1;
                    continue;
                };
                if out == data {
                    println!(
                        "PASS {name}: {} bytes, exported '{}'",
                        data.len(),
                        doc.exported_name()
                    );
                } else {
                    let first = out.iter().zip(data.iter()).position(|(a, b)| a != b);
                    println!(
                        "FAIL {name}: byte mismatch (len {} vs {}, first diff @ {:?})",
                        out.len(),
                        data.len(),
                        first
                    );
                    fail += 1;
                }
            }
            "info" => {
                // Normalized structural lines — must match what Leg B
                // derives from bemaniutils parseafp JSON.
                println!("file={name}");
                println!("exported_name={}", doc.exported_name());
                println!("frames={}", doc.root.frames.len());
                for (i, f) in doc.root.frames.iter().enumerate() {
                    println!("frame[{i}]={},{}", f.start_tag, f.tag_count);
                }
            }
            _ => unreachable!(),
        }
    }
    std::process::exit(if fail > 0 { 1 } else { 0 });
}

/// Source character ids referenced by the PlaceObjects of the labeled
/// segment (label frame .. next label / section end).
fn segment_source_ids(sec: &ap2::TagSection, label: &str) -> Vec<u16> {
    let Some(start) = sec.label_frame(label) else {
        return Vec::new();
    };
    let start = start as usize;
    let end = sec
        .labels
        .iter()
        .map(|l| l.frame as usize)
        .filter(|f| *f > start)
        .min()
        .unwrap_or(sec.frames.len());
    let mut ids = Vec::new();
    for f in &sec.frames[start..end.min(sec.frames.len())] {
        for i in f.start_tag..(f.start_tag + f.tag_count) {
            if let Some(ap2::Tag::PlaceObject(po)) = sec.tags.get(i as usize) {
                if let Some(v) = po.view() {
                    if let Some(id) = v.source_tag_id {
                        if !ids.contains(&id) {
                            ids.push(id);
                        }
                    }
                }
            }
        }
    }
    ids
}

/// Step-4 task-02 (Leg D): run the REAL word-segment recipe — the same
/// core/ap2 fn the DLL's dance_judge patch calls — on a real template and
/// write the patched file (string table re-scrambled) for bemaniutils
/// consumption. Prints the resolved/allocated ids + segment geometry.
fn smarv_patch(afp: &str, bsi: &str, geo_dir: &str, out_afp: &str) -> i32 {
    let Some(data) = descramble(afp, bsi) else {
        println!("FAIL smarv-patch: descramble");
        return 1;
    };
    let Some(mut doc) = ap2::Ap2Doc::parse(&data) else {
        println!("FAIL smarv-patch: parse");
        return 1;
    };
    // Resolve the word shape through the SHARED geo-first resolver — the
    // exact code path the DLL's assets.rs staging runs (deploy #3 fix: a
    // parallel harness-only resolution masked the DLL resolver's v3 break).
    let Some((word_shape_id, donor_region)) =
        doc.find_word_shape_by_geo("in_marvelous", "marvelous", |geo_name| {
            let bytes = std::fs::read(format!("{geo_dir}/{geo_name}")).ok()?;
            geo::labels(&bytes)
        })
    else {
        println!("FAIL smarv-patch: word chain unresolved (shared resolver)");
        return 1;
    };
    println!("word_shape_id={word_shape_id}");
    println!("donor_region={donor_region}");
    let Some(ids) =
        doc.clone_word_segment_with_new_shape("in_marvelous", "in_smarvelous", word_shape_id)
    else {
        println!("FAIL smarv-patch: recipe returned None");
        return 1;
    };
    let Some(mut out) = doc.serialize() else {
        println!("FAIL smarv-patch: serialize");
        return 1;
    };
    let Some(re) = ap2::Ap2Doc::parse(&out) else {
        println!("FAIL smarv-patch: re-parse");
        return 1;
    };
    let Some(path) = re.find_sprite_by_label("in_smarvelous") else {
        println!("FAIL smarv-patch: in_smarvelous missing");
        return 1;
    };
    let Some(sec) = re.section(&path) else {
        println!("FAIL smarv-patch: section");
        return 1;
    };
    let Some(label_frame) = sec.label_frame("in_smarvelous") else {
        println!("FAIL smarv-patch: label frame");
        return 1;
    };
    println!("word_sprite_id={}", ids.word_sprite_id);
    println!("new_shape_id={}", ids.new_shape_id);
    println!("new_sprite_id={}", ids.new_sprite_id);
    println!("label_frame={label_frame}");
    println!("section_frames={}", sec.frames.len());

    // Re-scramble the string table for bemaniutils consumption (its SWF
    // parser always runs the cipher).
    let st_off = u32::from_le_bytes(out[48..52].try_into().unwrap()) as usize;
    let st_size = u32::from_le_bytes(out[52..56].try_into().unwrap()) as usize;
    let scrambled = ap2::encode_string_table(&out[st_off..st_off + st_size]);
    out[st_off..st_off + st_size].copy_from_slice(&scrambled);
    if std::fs::write(out_afp, &out).is_err() {
        println!("FAIL smarv-patch: write {out_afp}");
        return 1;
    }
    println!("smarv-patch OK: wrote {out_afp} ({} bytes)", out.len());
    0
}

/// Step-4 task-02 (Leg D): run the REAL GE2D label rewriter — the same
/// core/geo fn the DLL's asset staging calls — on a real geo file.
fn geo_rewrite(input: &str, old_label: &str, new_label: &str, output: &str) -> i32 {
    let Ok(data) = std::fs::read(input) else {
        println!("FAIL geo-rewrite: read {input}");
        return 1;
    };
    let Some(out) = geo::rewrite_labels(&data, |l| {
        if l == old_label {
            Some(new_label.to_string())
        } else {
            None
        }
    }) else {
        println!("FAIL geo-rewrite: rewrite (is '{old_label}' present?)");
        return 1;
    };
    if std::fs::write(output, &out).is_err() {
        println!("FAIL geo-rewrite: write {output}");
        return 1;
    }
    println!(
        "geo-rewrite OK: {} -> {} bytes, '{old_label}' -> '{new_label}'",
        data.len(),
        out.len()
    );
    0
}

/// Step 3 demo: clone `in_marvelous` -> `in_smarvelous` on the REAL
/// dance_judge template. Remapped variant validated structurally; identity
/// variant written out (string table re-scrambled, empty BSI) for
/// bemaniutils parseafp + render consumption.
fn edit_demo(afp: &str, bsi: &str, out_afp: &str, out_bsi: &str) -> i32 {
    let Some(data) = descramble(afp, bsi) else {
        println!("FAIL edit-demo: descramble");
        return 1;
    };

    // ── Remapped variant (structural) ───────────────────────────────
    let Some(mut doc) = ap2::Ap2Doc::parse(&data) else {
        println!("FAIL edit-demo: parse");
        return 1;
    };
    let Some(path) = doc.find_sprite_by_label("in_marvelous") else {
        println!("FAIL edit-demo: in_marvelous label not found");
        return 1;
    };
    let unknown = doc
        .section(&path)
        .into_iter()
        .flat_map(|s| s.tags.iter())
        .find_map(|t| match t {
            ap2::Tag::Shape(s) => Some(s.unknown),
            _ => None,
        })
        .unwrap_or(0);
    let Some(new_id) = doc.add_shape(&path, 0, unknown) else {
        println!("FAIL edit-demo: add_shape");
        return 1;
    };
    // Inserts shift tag indices: re-resolve the path before cloning.
    let Some(path) = doc.find_sprite_by_label("in_marvelous") else {
        println!("FAIL edit-demo: re-resolve after add_shape");
        return 1;
    };
    let src_ids = doc
        .section(&path)
        .map(|s| segment_source_ids(s, "in_marvelous"))
        .unwrap_or_default();
    let Some(&remap_from) = src_ids.first() else {
        println!("FAIL edit-demo: no placeable ids in segment");
        return 1;
    };
    let mut remap = ap2::TagRemap::new();
    remap.insert(remap_from, new_id);
    if doc
        .clone_labeled_segment(&path, "in_marvelous", "in_smarvelous", &remap)
        .is_none()
    {
        println!("FAIL edit-demo: clone (remapped)");
        return 1;
    }
    let Some(out) = doc.serialize() else {
        println!("FAIL edit-demo: serialize (remapped)");
        return 1;
    };
    let Some(re) = ap2::Ap2Doc::parse(&out) else {
        println!("FAIL edit-demo: re-parse (remapped)");
        return 1;
    };
    let Some(re_path) = re.find_sprite_by_label("in_smarvelous") else {
        println!("FAIL edit-demo: in_smarvelous missing (remapped)");
        return 1;
    };
    let cloned_ids = re
        .section(&re_path)
        .map(|s| segment_source_ids(s, "in_smarvelous"))
        .unwrap_or_default();
    if !cloned_ids.contains(&new_id) {
        println!("FAIL edit-demo: clone does not reference new shape id {new_id}");
        return 1;
    }
    println!(
        "remapped variant OK: new_shape_id={new_id} remapped_from={remap_from} ({} bytes)",
        out.len()
    );

    // ── Identity variant (rendered by Leg C) ────────────────────────
    let Some(mut doc) = ap2::Ap2Doc::parse(&data) else {
        println!("FAIL edit-demo: parse (identity)");
        return 1;
    };
    let path = doc.find_sprite_by_label("in_marvelous").unwrap();
    if doc
        .clone_labeled_segment(&path, "in_marvelous", "in_smarvelous", &ap2::TagRemap::new())
        .is_none()
    {
        println!("FAIL edit-demo: clone (identity)");
        return 1;
    }
    let Some(mut out) = doc.serialize() else {
        println!("FAIL edit-demo: serialize (identity)");
        return 1;
    };
    let Some(re) = ap2::Ap2Doc::parse(&out) else {
        println!("FAIL edit-demo: re-parse (identity)");
        return 1;
    };
    let re_path = match re.find_sprite_by_label("in_smarvelous") {
        Some(p) => p,
        None => {
            println!("FAIL edit-demo: in_smarvelous missing (identity)");
            return 1;
        }
    };
    let sec = re.section(&re_path).unwrap();
    let label_frame = sec.label_frame("in_smarvelous").unwrap();
    // The clone appends at the section end: segment = label_frame..len.
    println!("label_frame={label_frame}");
    println!("segment_len={}", sec.frames.len() - label_frame as usize);
    println!("section_frames={}", sec.frames.len());
    println!("root_frames={}", re.root.frames.len());

    // Re-scramble the string table for bemaniutils consumption (its SWF
    // parser always runs the cipher); empty (0-byte) BSI = no byteswaps.
    let st_off = u32::from_le_bytes(out[48..52].try_into().unwrap()) as usize;
    let st_size = u32::from_le_bytes(out[52..56].try_into().unwrap()) as usize;
    let scrambled = ap2::encode_string_table(&out[st_off..st_off + st_size]);
    out[st_off..st_off + st_size].copy_from_slice(&scrambled);
    if std::fs::write(out_afp, &out).is_err() || std::fs::write(out_bsi, b"").is_err() {
        println!("FAIL edit-demo: write outputs");
        return 1;
    }
    println!("identity variant OK: wrote {out_afp}");
    0
}
EOF
else
  # No ap2 module yet: satisfy the [[bin]] target with a stub.
  echo 'fn main() {}' >"$TMP/src/main.rs"
fi

note "running pure module tests (${MODULE_NAMES[*]})"
(cd "$TMP" && cargo test --quiet)
note "synthetic suite OK"

# ── Dev legs (optional) ─────────────────────────────────────────────

if [[ "$HAVE_AP2" != 1 ]]; then
  exit 0
fi
if [[ -z "${DDR_WORLD_INSTALL:-}" || ! -d "${DDR_WORLD_INSTALL:-}/data/arc/bm2d" ]]; then
  skip "dev legs: DDR_WORLD_INSTALL not set or has no data/arc/bm2d"
  exit 0
fi
BEMANIUTILS_DIR="${BEMANIUTILS_DIR:-$REPO_ROOT/../bemaniutils}"
if [[ ! -x "$BEMANIUTILS_DIR/arcutils" || ! -x "$BEMANIUTILS_DIR/ifsutils" || ! -x "$BEMANIUTILS_DIR/afputils" ]]; then
  skip "dev legs: bemaniutils CLIs not found at $BEMANIUTILS_DIR (set BEMANIUTILS_DIR)"
  exit 0
fi

note "building ap2check dev binary"
(cd "$TMP" && cargo build --quiet --bin ap2check)
AP2CHECK="$TMP/target/debug/ap2check"

# The feature's patch targets: gameplay flash, FC splash, results scene.
# The LIVE default packages (cabinet-observed: the game loads the
# UNSUFFIXED _v3 arcs; NNNN_vN arcs are skin/revision variants).
DEV_ARCS=(dance_judge_v3 dance_fullcombo_v3 scene_result_v3)

extract_arc() { # <arc basename> -> echoes the extracted afp/ dir
  local arc="$1" out="$TMP/dev/$1"
  mkdir -p "$out"
  (cd "$BEMANIUTILS_DIR" && ./arcutils "$DDR_WORLD_INSTALL/data/arc/bm2d/$arc.arc" -d "$out") >/dev/null 2>&1 || return 1
  local ifs_file
  ifs_file=$(find "$out" -name "*.ifs" | head -1)
  [[ -n "$ifs_file" ]] || return 1
  (cd "$BEMANIUTILS_DIR" && ./ifsutils "$ifs_file" -d "$out/x") >/dev/null 2>&1 || return 1
  [[ -d "$out/x/afp" ]] || return 1
  echo "$out/x/afp"
}

note "Leg A: real-template round-trip (${DEV_ARCS[*]})"
LEGA_TOTAL=0
for arc in "${DEV_ARCS[@]}"; do
  AFP_DIR=$(extract_arc "$arc") || die "Leg A: extraction failed for $arc"
  FILES=()
  for f in "$AFP_DIR"/*; do
    if [[ -f "$f" && "$f" != *.xml ]]; then
      b="$AFP_DIR/bsi/$(basename "$f")"
      [[ -f "$b" ]] || die "Leg A: missing BSI for $(basename "$f") in $arc"
      FILES+=("$f" "$b")
    fi
  done
  [[ ${#FILES[@]} -gt 0 ]] || die "Leg A: no templates found in $arc"
  "$AP2CHECK" roundtrip "${FILES[@]}" | sed "s/^/    [$arc] /"
  LEGA_TOTAL=$((LEGA_TOTAL + ${#FILES[@]} / 2))
done
note "Leg A OK ($LEGA_TOTAL templates byte-identical)"

note "Leg B: bemaniutils parseafp cross-check"
LEGB_TEMPLATES=(
  "dance_judge_v3:dance_judge"
  "dance_judge_v3:dance_marvelous"
  "scene_result_v3:body_tab_detail_result"
)
for entry in "${LEGB_TEMPLATES[@]}"; do
  arc="${entry%%:*}" tpl="${entry##*:}"
  AFP_DIR="$TMP/dev/$arc/x/afp" # extracted by Leg A
  afp="$AFP_DIR/$tpl" bsi="$AFP_DIR/bsi/$tpl"
  [[ -f "$afp" && -f "$bsi" ]] || die "Leg B: template $tpl not found in $arc"
  # Ours -> normalized lines (drop the file= header).
  "$AP2CHECK" info "$afp" "$bsi" | grep -v '^file=' >"$TMP/dev/ours.txt"
  # Theirs: parseafp JSON -> the same normalized lines.
  (cd "$BEMANIUTILS_DIR" && ./afputils parseafp "$afp" "$bsi") >"$TMP/dev/theirs.json" 2>/dev/null \
    || die "Leg B: afputils parseafp failed for $tpl"
  python3 - "$TMP/dev/theirs.json" >"$TMP/dev/theirs.txt" <<'PYEOF'
import json, sys
d = json.load(open(sys.argv[1]))
print(f"exported_name={d['exported_name']}")
frames = d["frames"]
print(f"frames={len(frames)}")
for i, f in enumerate(frames):
    print(f"frame[{i}]={f['start_tag_offset']},{f['num_tags']}")
PYEOF
  if diff -u "$TMP/dev/theirs.txt" "$TMP/dev/ours.txt" >"$TMP/dev/diff.txt"; then
    echo "    [$arc/$tpl] structural match"
  else
    cat "$TMP/dev/diff.txt"
    die "Leg B: structural mismatch on $arc/$tpl"
  fi
done
note "Leg B OK"

# ── Leg C: real-template edit demo + render preview ────────────────
# Clones in_marvelous -> in_smarvelous on the REAL dance_judge template
# (Step 3's editing primitives), cross-checks the edited file with
# bemaniutils, and renders the cloned segment so a human can eyeball it.
note "Leg C: real-template edit demo (dance_judge)"
DJ_AFP_DIR="$TMP/dev/dance_judge_v3/x/afp" # extracted by Leg A
DJ_IFS=$(find "$TMP/dev/dance_judge_v3" -name "*.ifs" | head -1)
EDIT_DIR="$TMP/dev/edited"
mkdir -p "$EDIT_DIR"
"$AP2CHECK" edit-demo "$DJ_AFP_DIR/dance_judge" "$DJ_AFP_DIR/bsi/dance_judge" \
  "$EDIT_DIR/dance_judge" "$EDIT_DIR/dance_judge.bsi" | tee "$EDIT_DIR/demo.txt" | sed 's/^/    /'
LABEL_FRAME=$(grep -oE '^label_frame=[0-9]+' "$EDIT_DIR/demo.txt" | cut -d= -f2)
SECTION_FRAMES=$(grep -oE '^section_frames=[0-9]+' "$EDIT_DIR/demo.txt" | cut -d= -f2)
[[ -n "$LABEL_FRAME" && -n "$SECTION_FRAMES" ]] || die "Leg C: edit-demo did not report frames"

# Cross-check: bemaniutils must parse the edited file and see the label.
(cd "$BEMANIUTILS_DIR" && ./afputils parseafp "$EDIT_DIR/dance_judge" "$EDIT_DIR/dance_judge.bsi") \
  >"$EDIT_DIR/edited.json" 2>/dev/null || die "Leg C: afputils parseafp rejected the edited file"
python3 - "$EDIT_DIR/edited.json" <<'PYEOF' || die "Leg C: in_smarvelous label not visible to bemaniutils"
import json, sys
d = json.load(open(sys.argv[1]))
def find_labels(node):
    found = {}
    if isinstance(node, dict):
        if "labels" in node and isinstance(node["labels"], dict):
            found.update(node["labels"])
        for v in node.values():
            found.update(find_labels(v))
    elif isinstance(node, list):
        for v in node:
            found.update(find_labels(v))
    return found
labels = find_labels(d)
assert "in_smarvelous" in labels, f"labels seen: {sorted(labels)}"
print(f"    [cross-check] in_smarvelous @ frame {labels['in_smarvelous']} (bemaniutils)")
PYEOF

# Render the cloned segment (identity remap: it should look exactly like
# the stock MARVELOUS flash, played from the new label). Preview lands
# OUTSIDE the repo at a stable path.
PREVIEW_DIR="${TMPDIR:-/tmp}/s_marvelous_preview"
mkdir -p "$PREVIEW_DIR"
python3 - "$BEMANIUTILS_DIR" "$DJ_IFS" "$EDIT_DIR/dance_judge" "$LABEL_FRAME" "$SECTION_FRAMES" \
  "$PREVIEW_DIR/in_smarvelous_identity.gif" <<'PYEOF' || die "Leg C: render failed"
import io, os, sys
bemaniutils_dir, ifs_path, edited_afp, label_frame, section_frames, out_gif = sys.argv[1:7]
sys.path.insert(0, bemaniutils_dir)
from PIL import Image
from bemani.format import IFS
from bemani.format.afp import SWF, Shape, AFPRenderer

ifs = IFS(open(ifs_path, "rb").read(), decode_textures=True)
shapes, textures, swfs = {}, {}, {}
sep = os.sep
for fname in ifs.filenames:
    if fname.startswith(f"geo{sep}"):
        name = fname[4:]
        shape = Shape(name, ifs.read_file(fname))
        shape.parse()
        shapes[name] = shape
    elif fname.startswith(f"tex{sep}") and fname.endswith(".png"):
        textures[fname[4:-4]] = Image.open(io.BytesIO(ifs.read_file(fname)))
    elif fname.startswith(f"afp{sep}") and not fname.startswith(f"afp{sep}bsi{sep}") and not fname.endswith(".xml"):
        name = fname[4:]
        if name == "dance_judge":
            continue  # replaced by the edited template below
        bsi = ifs.read_file(f"afp{sep}bsi{sep}{name}")
        swf = SWF(name, ifs.read_file(fname), bsi)
        swf.parse()
        swfs[name] = swf

edited = SWF("dance_judge", open(edited_afp, "rb").read(), b"")
edited.parse()
swfs["dance_judge"] = edited
assert "in_smarvelous" in edited.labels, f"labels: {edited.labels}"

# The root timeline carries stop() bytecode (in-game the clip is driven by
# label jumps, not free playback). Neutralize DoAction bytecodes on the
# parsed RENDER COPY (index-stable: the tag objects stay in place) so the
# timeline free-runs through the cloned segment. File on disk untouched.
def blank_actions(tags):
    for t in tags:
        if hasattr(t, "bytecode") and t.bytecode is not None:
            t.bytecode.actions = []
        if hasattr(t, "tags"):
            blank_actions(t.tags)

blank_actions(edited.tags)

renderer = AFPRenderer(shapes=shapes, textures=textures, swfs=swfs, single_threaded=True)
# only_frames is 1-based (CLI semantics); the cloned segment occupies the
# appended tail of the section.
start, total = int(label_frame), int(section_frames)
wanted = list(range(start + 1, total + 1))
frames = list(renderer.render_path("dance_judge", only_frames=wanted))
if not frames:
    frames = list(renderer.render_path("dance_judge"))
    print(f"    [render] only_frames empty; fell back to full render ({len(frames)} frames)")
else:
    print(f"    [render] cloned segment frames {start + 1}..{total} rendered")
frames[0].save(out_gif, save_all=True, append_images=frames[1:], duration=1000 // 60, loop=0)
print(f"    [render] {len(frames)} frames -> {out_gif}")
PYEOF
note "Leg C OK — open the preview: ${TMPDIR:-/tmp}/s_marvelous_preview/in_smarvelous_identity.gif"

# ── Leg D: dance_judge REAL patch + render proof ────────────────────
# Step-4 task-02: resolve the §10 word chain from the real geo files,
# run the REAL patch recipe (core/ap2) and the REAL geo rewriter
# (core/geo) on the real template, then render the in_smarvelous segment
# with the renderer's texture dict carrying the mod's word art under the
# NEW region name — the patched preview must show the recolored word.
note "Leg D: dance_judge patched-template render proof (real recipe + geo rewrite)"
GEO_DIR="$TMP/dev/dance_judge_v3/x/geo"
SMARV_DIR="$TMP/dev/smarv"
mkdir -p "$SMARV_DIR"
WORD_PNG="$REPO_ROOT/data_mods/s_marvelous/dance_judge/smarvelous.png"
[[ -f "$WORD_PNG" ]] || die "Leg D: word art missing at $WORD_PNG"

# bemaniutils oracle scan — CROSS-CHECK ONLY (the authoritative resolution
# runs inside smarv-patch via the SHARED core/ap2+core/geo resolver, the
# same code path the DLL's assets.rs stages through).
CHAIN=$(python3 - "$BEMANIUTILS_DIR" "$GEO_DIR" <<'PYEOF'
import os, re, sys
bemaniutils_dir, geo_dir = sys.argv[1:3]
sys.path.insert(0, bemaniutils_dir)
from bemani.format.afp import Shape
for name in sorted(os.listdir(geo_dir)):
    m = re.fullmatch(r"dance_judge_shape(\d+)", name)
    if not m:
        continue
    s = Shape(name, open(os.path.join(geo_dir, name), "rb").read())
    s.parse()
    for d in s.draw_params:
        region = getattr(d, "region", None)
        if region and region.endswith("_marvelous"):
            print(m.group(1), region)
            sys.exit(0)
sys.exit(1)
PYEOF
) || die "Leg D: word chain unresolved (no dance_judge_shape* references a *_marvelous region)"
ORACLE_SHAPE_ID=$(echo "$CHAIN" | awk '{print $1}')
ORACLE_REGION=$(echo "$CHAIN" | awk '{print $2}')

# The REAL AP2 transform + the SHARED word-shape resolution (the same
# core/ap2 recipe and geo-first resolver the DLL patch fn / staging runs).
"$AP2CHECK" smarv-patch "$DJ_AFP_DIR/dance_judge" "$DJ_AFP_DIR/bsi/dance_judge" \
  "$GEO_DIR" "$SMARV_DIR/dance_judge" | tee "$SMARV_DIR/patch.txt" | sed 's/^/    /'
WORD_SHAPE_ID=$(grep -oE '^word_shape_id=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
DONOR_REGION=$(grep -oE '^donor_region=.*' "$SMARV_DIR/patch.txt" | cut -d= -f2)
NEW_REGION="${DONOR_REGION%marvelous}smarvelous"
[[ "$WORD_SHAPE_ID" == "$ORACLE_SHAPE_ID" && "$DONOR_REGION" == "$ORACLE_REGION" ]] \
  || die "Leg D: shared resolver ($WORD_SHAPE_ID/$DONOR_REGION) disagrees with the bemaniutils oracle ($ORACLE_SHAPE_ID/$ORACLE_REGION)"
echo "    [chain] word shape $WORD_SHAPE_ID, region $DONOR_REGION -> $NEW_REGION (oracle agrees)"
NEW_SHAPE_ID=$(grep -oE '^new_shape_id=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
D_LABEL_FRAME=$(grep -oE '^label_frame=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
D_SECTION_FRAMES=$(grep -oE '^section_frames=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
[[ -n "$NEW_SHAPE_ID" && -n "$D_LABEL_FRAME" && -n "$D_SECTION_FRAMES" ]] \
  || die "Leg D: smarv-patch did not report ids"

# The REAL geo rewrite (same core/geo fn the DLL asset staging runs).
"$AP2CHECK" geo-rewrite "$GEO_DIR/dance_judge_shape${WORD_SHAPE_ID}" \
  "$DONOR_REGION" "$NEW_REGION" "$SMARV_DIR/dance_judge_shape${NEW_SHAPE_ID}" | sed 's/^/    /'

# Render the patched segment with the new region mapped to the mod's art.
python3 - "$BEMANIUTILS_DIR" "$DJ_IFS" "$SMARV_DIR/dance_judge" \
  "$SMARV_DIR/dance_judge_shape${NEW_SHAPE_ID}" "dance_judge_shape${NEW_SHAPE_ID}" \
  "$NEW_REGION" "$WORD_PNG" "$D_LABEL_FRAME" "$D_SECTION_FRAMES" \
  "$PREVIEW_DIR/in_smarvelous_patched.gif" <<'PYEOF' || die "Leg D: render failed"
import io, os, sys
(bemaniutils_dir, ifs_path, patched_afp, new_geo_path, new_geo_name,
 new_region, word_png, label_frame, section_frames, out_gif) = sys.argv[1:11]
sys.path.insert(0, bemaniutils_dir)
from PIL import Image
from bemani.format import IFS
from bemani.format.afp import SWF, Shape, AFPRenderer

ifs = IFS(open(ifs_path, "rb").read(), decode_textures=True)
shapes, textures, swfs = {}, {}, {}
sep = os.sep
for fname in ifs.filenames:
    if fname.startswith(f"geo{sep}"):
        name = fname[4:]
        shape = Shape(name, ifs.read_file(fname))
        shape.parse()
        shapes[name] = shape
    elif fname.startswith(f"tex{sep}") and fname.endswith(".png"):
        textures[fname[4:-4]] = Image.open(io.BytesIO(ifs.read_file(fname)))
    elif fname.startswith(f"afp{sep}") and not fname.startswith(f"afp{sep}bsi{sep}") and not fname.endswith(".xml"):
        name = fname[4:]
        if name == "dance_judge":
            continue  # replaced by the patched template below
        bsi = ifs.read_file(f"afp{sep}bsi{sep}{name}")
        swf = SWF(name, ifs.read_file(fname), bsi)
        swf.parse()
        swfs[name] = swf

# The REWRITTEN geo, registered under the name the new shape id demands.
# (Shape.parse validates the GE2D filesize field — a real oracle for the
# length-changing label rebuild.)
new_shape = Shape(new_geo_name, open(new_geo_path, "rb").read())
new_shape.parse()
shapes[new_geo_name] = new_shape
regions = [getattr(d, "region", None) for d in new_shape.draw_params]
assert new_region in regions, f"rewritten geo references {regions}, wanted {new_region}"

# The new region name maps to the mod's word art (what the donor-anchored
# atlas clone serves in-game).
textures[new_region] = Image.open(word_png)

patched = SWF("dance_judge", open(patched_afp, "rb").read(), b"")
patched.parse()
swfs["dance_judge"] = patched
assert "in_smarvelous" in patched.labels, f"labels: {patched.labels}"

# Neutralize DoAction bytecodes on the render copy (Leg C precedent) so
# the timeline free-runs through the cloned segment.
def blank_actions(tags):
    for t in tags:
        if hasattr(t, "bytecode") and t.bytecode is not None:
            t.bytecode.actions = []
        if hasattr(t, "tags"):
            blank_actions(t.tags)

blank_actions(patched.tags)

renderer = AFPRenderer(shapes=shapes, textures=textures, swfs=swfs, single_threaded=True)
start, total = int(label_frame), int(section_frames)
wanted = list(range(start + 1, total + 1))
frames = list(renderer.render_path("dance_judge", only_frames=wanted))
assert frames, "patched segment rendered no frames"
assert any(f.getbbox() for f in frames), "patched segment rendered fully blank"
print(f"    [render] patched segment frames {start + 1}..{total} rendered ({len(frames)} frames, non-blank)")
frames[0].save(out_gif, save_all=True, append_images=frames[1:], duration=1000 // 60, loop=0)
print(f"    [render] preview -> {out_gif}")
PYEOF
note "Leg D OK — open the patched preview: ${TMPDIR:-/tmp}/s_marvelous_preview/in_smarvelous_patched.gif"
note "OK"
