#!/usr/bin/env bash
# Offline validation for improved_song_title_sorting's pure layout model
# (src/mods/improved_song_title_sorting/layout.rs): display order, cell
# templates, the flow-layout rows the game will produce, label keys and the
# identity range table the stock predicate / chip summary read.
#
# Usage:
#   ./scripts/validate_improved_song_title_sorting.sh
#
# Why a harness: plain `cargo test` cannot run on non-x86 hosts (the `retour`
# dependency only compiles for x86/x86_64), so -- like
# validate_series_expansion.sh -- this builds a throwaway HOST cargo crate in
# a temp directory that mounts the dependency-free model via `#[path]` and
# runs its `#[cfg(test)]` suite there. It also runs the label generator's
# host tests (scripts/test_gen_title_labels.py) when Pillow is available.
#
# Requires: cargo (host toolchain); python3 + Pillow for the generator leg.
# Validation only -- writes nothing into the repository.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }

MODEL="src/mods/improved_song_title_sorting/layout.rs"
[[ -r "$REPO_ROOT/$MODEL" ]] || die "module source missing: $MODEL"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<TOML
[package]
name = "improved-song-title-sorting-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[workspace]
TOML

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness -- generated by"
  echo "//! scripts/validate_improved_song_title_sorting.sh; never committed."
  echo "#![allow(dead_code)]"
  echo "#[path = \"$REPO_ROOT/$MODEL\"]"
  echo "pub mod layout;"
} >"$TMP/src/lib.rs"

note "running pure layout tests (layout)"
(cd "$TMP" && cargo test --quiet -- --nocapture 2>&1 | grep -vE "^$")

if python3 -c "import PIL" 2>/dev/null; then
  note "running label generator tests (scripts/test_gen_title_labels.py)"
  (cd scripts && PYTHONDONTWRITEBYTECODE=1 python3 -m unittest -q test_gen_title_labels)
else
  note "Pillow not installed -- skipping the label generator tests"
fi
note "OK"
