#!/usr/bin/env bash
# Offline validation for the custom_options pure layers
# (`src/services/custom_options/` — the overlay-menu rewrite's ordering/
# placement core; growing as later Step 5 tasks add mountable modules:
# api.rs, registry.rs, observers.rs).
#
# Usage:
#   ./scripts/validate_custom_options.sh
#
# Why a harness: plain `cargo test` cannot run on non-x86 hosts (the `retour`
# dependency only compiles for x86/x86_64), so — like validate_mod_menu.sh —
# this builds a throwaway HOST cargo crate in a temp directory that mounts
# the feature's modules via `#[path]` and runs their `#[cfg(test)]` suites
# there. Mounted files may `use crate::log_warn;` etc. — the generated
# lib.rs defines no-op stub macros for the DLL's logging front-end.
#
# Requires: cargo (host toolchain). Nothing else; no game install, no Windows
# toolchain. This script is validation only — it writes nothing into the
# repository.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }

MOD_SRC="$REPO_ROOT/src/services/custom_options"
MODULES=(api.rs observers.rs ordering.rs registry.rs)
for f in "${MODULES[@]}"; do
  [[ -r "$MOD_SRC/$f" ]] || die "module source missing: src/services/custom_options/$f"
done

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<EOF
[package]
name = "custom-options-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
once_cell = "1"

[workspace]
EOF

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness — generated by"
  echo "//! scripts/validate_custom_options.sh; never committed."
  echo "#![allow(dead_code)]"
  echo ""
  echo "// No-op stubs for the DLL's logging macros (the real ones route to"
  echo "// OutputDebugStringA); mounted modules import them via crate::log_*."
  echo '#[macro_export] macro_rules! log_warn { ($($t:tt)*) => {{ let _ = format!($($t)*); }} }'
  echo '#[macro_export] macro_rules! log_info { ($($t:tt)*) => {{ let _ = format!($($t)*); }} }'
  echo '#[macro_export] macro_rules! log_debug { ($($t:tt)*) => {{ let _ = format!($($t)*); }} }'
  echo '#[macro_export] macro_rules! log_error { ($($t:tt)*) => {{ let _ = format!($($t)*); }} }'
  echo ""
  for f in "${MODULES[@]}"; do
    name="${f%.rs}"
    echo "#[path = \"$MOD_SRC/$f\"]"
    echo "pub mod $name;"
  done
} >"$TMP/src/lib.rs"

note "running pure module tests (${MODULES[*]})"
(cd "$TMP" && cargo test --quiet)
note "OK"

# ── Display-string lint (Step 9 sweep guard) ──────────────────────────────
# Every custom-option registration in src/mods/ must carry explicit
# .display_name(…) and .description(…) (no prettified-id fallbacks), and
# registrants must never construct bare EnumValue::new (no display label) —
# use with_display / with_preview(..).display_label(..). Textual lint (the
# harness can't mount mod code): for each register_option call site, scan
# the ~60 lines ABOVE it (the spec builder chain) for the two builders.
note "linting registration display strings (src/mods/)"
python3 - <<'PY'
import re, sys, pathlib

fails = []
for path in pathlib.Path("src/mods").rglob("*.rs"):
    text = path.read_text()
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if "register_option(" not in line or "//" in line.split("register_option")[0]:
            continue
        # The spec chain may precede the call OR span the call's argument
        # lines below it (rustfmt splits long chains) — scan both directions.
        window = "\n".join(lines[max(0, i - 60) : i + 8])
        if ".display_name(" not in window:
            fails.append(f"{path}:{i+1}: register_option without .display_name in the preceding chain")
        if ".description(" not in window:
            fails.append(f"{path}:{i+1}: register_option without .description in the preceding chain")
    for m in re.finditer(r"EnumValue::new\(", text):
        ln = text[: m.start()].count("\n") + 1
        fails.append(f"{path}:{ln}: bare EnumValue::new — use with_display or with_preview(..).display_label(..)")

if fails:
    print("display-string lint FAILED:", file=sys.stderr)
    for f in fails:
        print("  " + f, file=sys.stderr)
    sys.exit(1)
print("display-string lint OK")
PY
note "OK"
