#!/usr/bin/env bash
# Offline cross-build signature sweep.
#
# Runs the DLL's REAL `SignatureStore::resolve_all` + `resolve_derived`
# (src/core/signatures.rs + src/core/scanner.rs, mounted verbatim) against
# every `gamemdx*.dll` in a directory, mapped the way the Windows loader maps
# it (sections at virtual addresses, relocations applied). Then joins the
# per-build resolved/missing sets against the crate's own consumer graph
# (`required_signatures()` lists + `get_address`/`require_address` call
# sites) and prints which mods/services lose which addresses on which build.
#
# Usage:
#   ./scripts/validate_signatures.sh ~/Desktop/ddr_modules            # all gamemdx*.dll there
#     (drop ONE libafp-win64*.dll of any build alongside them so the
#      IAT-target derivations can run; every arkmdxbio2*.dll there is
#      checked by the ark_check.py leg — input_manager's vtable-slot
#      derivation mirrored in Python)
#   ./scripts/validate_signatures.sh ~/Desktop/ddr_modules --json out.json
#   ./scripts/validate_signatures.sh ~/Desktop/ddr_modules --raw      # also dump raw harness logs
#
# The build name is taken from the file name: `gamemdx_20260721.dll` ->
# `20260721`; a bare `gamemdx.dll` is named after its parent directory.
#
# Requires: a host cargo toolchain (the harness is a plain std-only crate —
# no Windows target, no retour) and python3. Writes nothing into the repo.
#
# Exit status: 0 when every signature/derivation that resolves on ANY build
# resolves on EVERY build; 1 otherwise (the report shows the gaps).

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*" >&2; }

[[ $# -ge 1 ]] || die "usage: $0 <dir-with-gamemdx*.dll> [--json out.json] [--raw]"
MOD_DIR="${1/#\~/$HOME}"
shift
[[ -d "$MOD_DIR" ]] || die "not a directory: $MOD_DIR"

JSON_OUT=""
RAW=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --json) JSON_OUT="$2"; shift 2 ;;
    --raw) RAW=1; shift ;;
    *) die "unknown arg: $1" ;;
  esac
done

CORE="$REPO_ROOT/src/core"
for f in scanner.rs signatures.rs profiling.rs; do
  [[ -r "$CORE/$f" ]] || die "missing $CORE/$f"
done

# Persistent harness dir so incremental rebuilds are fast across runs.
HARNESS="${SIG_HARNESS_DIR:-$REPO_ROOT/target/sig_harness}"
mkdir -p "$HARNESS/src/core" "$HARNESS/out"

cat >"$HARNESS/Cargo.toml" <<EOF
[package]
name = "sig_harness"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "sig_harness"
path = "src/main.rs"

[workspace]

[dependencies]
# Must track the DLL's own scanner dependency (Cargo.toml: aho-corasick = "1").
aho-corasick = "1"

[profile.release]
debug = 1
EOF

cat >"$HARNESS/src/lib.rs" <<EOF
//! Throwaway offline signature harness — generated by
//! scripts/validate_signatures.sh; never committed.
#![allow(dead_code, unused_imports, unused_unsafe, clippy::all)]
pub mod core {
    pub mod logger;
    pub mod module_resolver;
    #[path = "$CORE/profiling.rs"]
    pub mod profiling;
    #[path = "$CORE/scanner.rs"]
    pub mod scanner;
    #[path = "$CORE/signatures.rs"]
    pub mod signatures;
}
pub use core::logger::*;
EOF

cat >"$HARNESS/src/core/module_resolver.rs" <<'EOF'
//! Host stub of the DLL's module resolver — only the fields signatures.rs reads.
pub struct GameModule {
    pub name: String,
    pub base: *const u8,
    pub size: usize,
}
unsafe impl Send for GameModule {}
unsafe impl Sync for GameModule {}
EOF

cat >"$HARNESS/src/core/logger.rs" <<'EOF'
//! Host stub logger: same macro surface as the DLL, prints to stdout.
#[derive(Clone, Copy)]
pub enum LogLevel { Debug = 0, Info = 1, Warn = 2, Error = 3 }
pub fn log(level: LogLevel, message: &str) {
    let tag = match level {
        LogLevel::Debug => "DEBUG", LogLevel::Info => "INFO",
        LogLevel::Warn => "WARN", LogLevel::Error => "ERROR",
    };
    println!("[{}] {}", tag, message);
}
#[macro_export]
macro_rules! log_info { ($($arg:tt)*) => { $crate::core::logger::log($crate::core::logger::LogLevel::Info, &format!($($arg)*)) }; }
#[macro_export]
macro_rules! log_warn { ($($arg:tt)*) => { $crate::core::logger::log($crate::core::logger::LogLevel::Warn, &format!($($arg)*)) }; }
#[macro_export]
macro_rules! log_error { ($($arg:tt)*) => { $crate::core::logger::log($crate::core::logger::LogLevel::Error, &format!($($arg)*)) }; }
#[macro_export]
macro_rules! log_debug { ($($arg:tt)*) => { $crate::core::logger::log($crate::core::logger::LogLevel::Debug, &format!($($arg)*)) }; }
EOF

cp "$REPO_ROOT/scripts/sig_harness/main.rs" "$HARNESS/src/main.rs"

note "building harness in $HARNESS"
(cd "$HARNESS" && cargo build --release --quiet 2>&1 | grep -v "^warning" || true)
BIN="$HARNESS/target/release/sig_harness"
[[ -x "$BIN" ]] || die "harness build failed (run: cd $HARNESS && cargo build --release)"

shopt -s nullglob
DLLS=("$MOD_DIR"/gamemdx*.dll "$MOD_DIR"/*/gamemdx*.dll)
[[ ${#DLLS[@]} -gt 0 ]] || die "no gamemdx*.dll under $MOD_DIR"

# libafp export table (gamemdx imports it by ORDINAL; the color-twin
# derivation compares IAT targets against exports resolved by NAME, so the
# harness needs the ordinal->name map). One copy of any build suffices —
# the ordinals signatures.rs cares about are stable across builds.
LIBAFP=""
for cand in "$MOD_DIR"/libafp-win64*.dll "$MOD_DIR"/*/libafp-win64*.dll; do
  LIBAFP="$cand"; break
done
[[ -n "$LIBAFP" ]] && note "libafp export table: $LIBAFP" || note "no libafp-win64*.dll found — IAT-compare derivations will report unavailable"

rm -f "$HARNESS"/out/*.log
for dll in "${DLLS[@]}"; do
  fname="$(basename "$dll" .dll)"
  build="${fname#gamemdx}"
  build="${build#_}"
  [[ -n "$build" ]] || build="$(basename "$(dirname "$dll")")"
  note "scanning $build  ($dll)"
  # One process per build: a bad derivation that derefs junk on a foreign
  # build must not take the other builds' results down with it.
  if ! "$BIN" "$build" "$dll" ${LIBAFP:+"$LIBAFP"} >"$HARNESS/out/$build.log" 2>&1; then
    echo "### harness-crashed build=$build" >>"$HARNESS/out/$build.log"
    note "  !! harness exited non-zero for $build (see $HARNESS/out/$build.log)"
  fi
  if [[ $RAW -eq 1 ]]; then cat "$HARNESS/out/$build.log"; fi
done

ARGS=(--src "$REPO_ROOT/src" --logs "$HARNESS/out")
[[ -n "$JSON_OUT" ]] && ARGS+=(--json "$JSON_OUT")
STATUS=0
python3 "$REPO_ROOT/scripts/sig_harness/report.py" "${ARGS[@]}" || STATUS=$?

# arkmdxbio2 leg: input_manager's export-wrapper vtable-slot derivation has
# no Rust host harness, so a byte-for-byte Python mirror runs here over every
# arkmdxbio2*.dll in the same directory (see ark_check.py's header).
echo
python3 "$REPO_ROOT/scripts/sig_harness/ark_check.py" --dir "$MOD_DIR" || STATUS=1
exit $STATUS
