#!/usr/bin/env bash
# Offline validation for the S-Marvelous pure layers (implementation plan
# `.agents/planning/2026-08-29-s-marvelous-judgement/implementation/plan.md`
# — the classification state machine and the core/ap2 AFP editor).
#
# Usage:
#   ./scripts/validate_s_marvelous.sh
#
# Always-on: the synthetic host-test suite (state machine + core/ap2
# round-trip/model tests) in a throwaway temp-dir cargo crate — plain
# `cargo test` cannot run on non-x86 hosts (the `retour` dependency only
# compiles for x86/x86_64), so the harness mounts the feature's
# dependency-free modules via `#[path]` and runs their `#[cfg(test)]`
# suites there.
#
# Optional DEV LEGS (skipped with a notice when prerequisites are absent;
# never required for CI/other machines):
#   Leg A — real-template round-trip: extracts AFP templates from the game
#     install (env `DDR_WORLD_INSTALL` = game contents root containing
#     `data/`), descrambles them (BSI + string-table cipher), and asserts
#     `serialize(parse(x)) == x` byte-identically per template.
#   Leg B — bemaniutils cross-check: parses the same descrambled templates
#     with bemaniutils `afputils parseafp` (env `BEMANIUTILS_DIR`, default
#     sibling `../bemaniutils`) and compares structural invariants
#     (exported name, frame count, per-frame tag spans).
# Both legs run entirely in temp dirs and write nothing into the
# repository; no Konami bytes are ever committed.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }
skip() { echo "[skip] $*"; }

# module name -> repo-relative source path. Names must be unique.
declare -a MODULE_NAMES=(s_marvelous_state)
declare -a MODULE_PATHS=("src/mods/s_marvelous/state.rs")
# s_marvelous/records (std-only record-stream recompute — Step 7) +
# s_marvelous/upload (std-only score-upload payload builder — server-upload
# Step 2; `use super::records`). Both mount NESTED under one `s_marvelous`
# namespace (see the lib.rs generator below) so `super::records` resolves.
HAVE_SMARV_RECORDS=0
HAVE_SMARV_UPLOAD=0
if [[ -r "$REPO_ROOT/src/mods/s_marvelous/records.rs" ]]; then
  HAVE_SMARV_RECORDS=1
  if [[ -r "$REPO_ROOT/src/mods/s_marvelous/upload.rs" ]]; then
    HAVE_SMARV_UPLOAD=1
  fi
fi
# avs_layeredfs/afplist_ext (std-only afplist <geo> list transform — the
# deploy-#4 geo-registration fix; mounted for its test suite).
if [[ -r "$REPO_ROOT/src/services/avs_layeredfs/afplist_ext.rs" ]]; then
  MODULE_NAMES+=(afplist_ext)
  MODULE_PATHS+=("src/services/avs_layeredfs/afplist_ext.rs")
fi
# core/geo (GE2D label primitives — std-only, mounted for its test suite
# and consumed by the ap2check dev binary's geo-rewrite mode).
if [[ -r "$REPO_ROOT/src/core/geo.rs" ]]; then
  MODULE_NAMES+=(geo)
  MODULE_PATHS+=("src/core/geo.rs")
fi
# core/ap2 mounts here when plan Step 2 lands.
HAVE_AP2=0
if [[ -r "$REPO_ROOT/src/core/ap2/mod.rs" ]]; then
  MODULE_NAMES+=(ap2)
  MODULE_PATHS+=("src/core/ap2/mod.rs")
  HAVE_AP2=1
fi

for p in "${MODULE_PATHS[@]}"; do
  [[ -r "$REPO_ROOT/$p" ]] || die "module source missing: $p"
done
[[ "$HAVE_SMARV_RECORDS" == 1 ]] || die "module source missing: src/mods/s_marvelous/records.rs"
[[ -r "$REPO_ROOT/src/mods/s_marvelous/targets.rs" ]] || die "module source missing: src/mods/s_marvelous/targets.rs"

TMP=$(mktemp -d)
trap 'if [[ -z "${KEEP_TMP:-}" ]]; then rm -rf "$TMP"; fi' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<EOF
[package]
name = "s-marvelous-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ap2check"
path = "src/main.rs"

[workspace]
EOF

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness — generated by"
  echo "//! scripts/validate_s_marvelous.sh; never committed."
  echo "#![allow(dead_code)]"
  for i in "${!MODULE_NAMES[@]}"; do
    echo "#[path = \"$REPO_ROOT/${MODULE_PATHS[$i]}\"]"
    echo "pub mod ${MODULE_NAMES[$i]};"
  done
  if [[ "$HAVE_SMARV_RECORDS" == 1 ]]; then
    echo "pub mod s_marvelous {"
    echo "    #[path = \"$REPO_ROOT/src/mods/s_marvelous/records.rs\"]"
    echo "    pub mod records;"
    if [[ "$HAVE_SMARV_UPLOAD" == 1 ]]; then
      echo "    #[path = \"$REPO_ROOT/src/mods/s_marvelous/upload.rs\"]"
      echo "    pub mod upload;"
      if [[ -r "$REPO_ROOT/src/mods/s_marvelous/lamp_codec.rs" ]]; then
        echo "    #[path = \"$REPO_ROOT/src/mods/s_marvelous/lamp_codec.rs\"]"
        echo "    pub mod lamp_codec;"
      fi
    fi
    # s_marvelous/receptor_color (std-only receptor-burst recolour +
    # discriminator — 2026-09-12; mounted for its test suite).
    if [[ -r "$REPO_ROOT/src/mods/s_marvelous/receptor_color.rs" ]]; then
      echo "    #[path = \"$REPO_ROOT/src/mods/s_marvelous/receptor_color.rs\"]"
      echo "    pub mod receptor_color;"
    fi
    # s_marvelous/targets (std-only art-target names — World + DDR
    # SELECTION's legacy skins; also mounted by ap2check for Leg H).
    echo "    #[path = \"$REPO_ROOT/src/mods/s_marvelous/targets.rs\"]"
    echo "    pub mod targets;"
    echo "}"
  fi
} >"$TMP/src/lib.rs"

# The ap2check dev binary (Legs A/B). Compiled unconditionally (cheap, keeps
# the mounts honest) but only EXECUTED by the dev legs.
if [[ "$HAVE_AP2" == 1 ]]; then
  cat >"$TMP/src/main.rs" <<EOF
//! ap2check — dev-leg binary for validate_s_marvelous.sh. Never committed.
#![allow(dead_code)]
#[path = "$REPO_ROOT/src/core/ap2/mod.rs"]
mod ap2;
#[path = "$REPO_ROOT/src/core/afp.rs"]
mod afp;
#[path = "$REPO_ROOT/src/core/geo.rs"]
mod geo;
#[path = "$REPO_ROOT/src/mods/s_marvelous/targets.rs"]
mod targets;

/// BSI byteswap + string-table cipher removal — the same "fully
/// descrambled" shape the game's afp_patcher seam sees (docs/afp_system.md
/// §1). String table region: offset @48, size @52 (u32 LE).
fn descramble(afp_path: &str, bsi_path: &str) -> Option<Vec<u8>> {
    let mut data = std::fs::read(afp_path).ok()?;
    let bsi = std::fs::read(bsi_path).ok()?;
    afp::apply_bsi(&mut data, &bsi);
    let st_off = u32::from_le_bytes(data.get(48..52)?.try_into().ok()?) as usize;
    let st_size = u32::from_le_bytes(data.get(52..56)?.try_into().ok()?) as usize;
    let table = data.get(st_off..st_off.checked_add(st_size)?)?.to_vec();
    let plain = ap2::decode_string_table(&table);
    data[st_off..st_off + st_size].copy_from_slice(&plain);
    Some(data)
}

fn file_name(p: &str) -> String {
    std::path::Path::new(p)
        .file_name()
        .map(|f| f.to_string_lossy().into_owned())
        .unwrap_or_else(|| p.to_string())
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mode = args.first().map(String::as_str).unwrap_or("");
    if mode == "edit-demo" {
        if args.len() != 5 {
            eprintln!("usage: ap2check edit-demo <afp> <bsi> <out_afp> <out_bsi>");
            std::process::exit(2);
        }
        std::process::exit(edit_demo(&args[1], &args[2], &args[3], &args[4]));
    }
    if mode == "smarv-patch" {
        if args.len() != 5 {
            eprintln!("usage: ap2check smarv-patch <afp> <bsi> <geo_dir> <out_afp>");
            std::process::exit(2);
        }
        std::process::exit(smarv_patch(&args[1], &args[2], &args[3], &args[4]));
    }
    if mode == "smarv-fc" {
        if args.len() != 4 && args.len() != 5 {
            eprintln!("usage: ap2check smarv-fc <afp> <bsi> <geo_dir> [<skin 0..5>]");
            std::process::exit(2);
        }
        let skin: u8 = args.get(4).and_then(|s| s.parse().ok()).unwrap_or(0);
        std::process::exit(smarv_fc(&args[1], &args[2], &args[3], skin));
    }
    if mode == "smarv-legacy-word" {
        if args.len() != 6 {
            eprintln!("usage: ap2check smarv-legacy-word <afp> <bsi> <geo_dir> <skin 1..5> <out_afp>");
            std::process::exit(2);
        }
        let skin: u8 = args[4].parse().unwrap_or(0);
        std::process::exit(smarv_legacy_word(&args[1], &args[2], &args[3], skin, &args[5]));
    }
    if mode == "smarv-emblem" {
        if args.len() != 5 {
            eprintln!("usage: ap2check smarv-emblem <afp> <bsi> <geo_dir> <out_afp>");
            std::process::exit(2);
        }
        std::process::exit(smarv_emblem(&args[1], &args[2], &args[3], &args[4]));
    }
    if mode == "smarv-rows" {
        if args.len() != 6 {
            eprintln!("usage: ap2check smarv-rows <afp> <bsi> <rows d:ty:dy,..> <expected_each> <out_afp>");
            std::process::exit(2);
        }
        std::process::exit(smarv_rows(&args[1], &args[2], &args[3], &args[4], &args[5]));
    }
    if mode == "geo-rewrite" {
        if args.len() != 5 {
            eprintln!("usage: ap2check geo-rewrite <geo_in> <old_label> <new_label> <geo_out>");
            std::process::exit(2);
        }
        std::process::exit(geo_rewrite(&args[1], &args[2], &args[3], &args[4]));
    }
    let pairs = &args[1..];
    if !matches!(mode, "roundtrip" | "info") || pairs.len() % 2 != 0 {
        eprintln!("usage: ap2check roundtrip|info <afp> <bsi> [<afp> <bsi> ...]");
        std::process::exit(2);
    }
    let mut fail = 0u32;
    for pair in pairs.chunks(2) {
        let name = file_name(&pair[0]);
        let Some(data) = descramble(&pair[0], &pair[1]) else {
            println!("FAIL {name}: descramble");
            fail += 1;
            continue;
        };
        let Some(doc) = ap2::Ap2Doc::parse(&data) else {
            println!("FAIL {name}: parse -> None");
            fail += 1;
            continue;
        };
        match mode {
            "roundtrip" => {
                let Some(out) = doc.serialize() else {
                    println!("FAIL {name}: serialize -> None");
                    fail += 1;
                    continue;
                };
                if out == data {
                    println!(
                        "PASS {name}: {} bytes, exported '{}'",
                        data.len(),
                        doc.exported_name()
                    );
                } else {
                    let first = out.iter().zip(data.iter()).position(|(a, b)| a != b);
                    println!(
                        "FAIL {name}: byte mismatch (len {} vs {}, first diff @ {:?})",
                        out.len(),
                        data.len(),
                        first
                    );
                    fail += 1;
                }
            }
            "info" => {
                // Normalized structural lines — must match what Leg B
                // derives from bemaniutils parseafp JSON.
                println!("file={name}");
                println!("exported_name={}", doc.exported_name());
                println!("frames={}", doc.root.frames.len());
                for (i, f) in doc.root.frames.iter().enumerate() {
                    println!("frame[{i}]={},{}", f.start_tag, f.tag_count);
                }
            }
            _ => unreachable!(),
        }
    }
    std::process::exit(if fail > 0 { 1 } else { 0 });
}

/// Source character ids referenced by the PlaceObjects of the labeled
/// segment (label frame .. next label / section end).
fn segment_source_ids(sec: &ap2::TagSection, label: &str) -> Vec<u16> {
    let Some(start) = sec.label_frame(label) else {
        return Vec::new();
    };
    let start = start as usize;
    let end = sec
        .labels
        .iter()
        .map(|l| l.frame as usize)
        .filter(|f| *f > start)
        .min()
        .unwrap_or(sec.frames.len());
    let mut ids = Vec::new();
    for f in &sec.frames[start..end.min(sec.frames.len())] {
        for i in f.start_tag..(f.start_tag + f.tag_count) {
            if let Some(ap2::Tag::PlaceObject(po)) = sec.tags.get(i as usize) {
                if let Some(v) = po.view() {
                    if let Some(id) = v.source_tag_id {
                        if !ids.contains(&id) {
                            ids.push(id);
                        }
                    }
                }
            }
        }
    }
    ids
}

/// Step-4 task-02 (Leg D): run the REAL word-segment recipe — the same
/// core/ap2 fn the DLL's dance_judge patch calls — on a real template and
/// write the patched file (string table re-scrambled) for bemaniutils
/// consumption. Prints the resolved/allocated ids + segment geometry.
fn smarv_patch(afp: &str, bsi: &str, geo_dir: &str, out_afp: &str) -> i32 {
    let Some(data) = descramble(afp, bsi) else {
        println!("FAIL smarv-patch: descramble");
        return 1;
    };
    let Some(mut doc) = ap2::Ap2Doc::parse(&data) else {
        println!("FAIL smarv-patch: parse");
        return 1;
    };
    // Resolve the word shape through the SHARED geo-first resolver — the
    // exact code path the DLL's assets.rs staging runs (deploy #3 fix: a
    // parallel harness-only resolution masked the DLL resolver's v3 break).
    let Some((word_shape_id, donor_region)) =
        doc.find_word_shape_by_geo("in_marvelous", "marvelous", |geo_name| {
            let bytes = std::fs::read(format!("{geo_dir}/{geo_name}")).ok()?;
            geo::labels(&bytes)
        })
    else {
        println!("FAIL smarv-patch: word chain unresolved (shared resolver)");
        return 1;
    };
    println!("word_shape_id={word_shape_id}");
    println!("donor_region={donor_region}");
    // The DLL's SHIPPED options (assets::word_clone_opts(true) — the first
    // rung of run_word_clone's ladder): mute the additive marvelous_ef
    // self-glow in the cloned chain AND in the stock Marvelous word (the
    // stock pulse is always muted since 2026-09-13; the "Marvelous Shimmer"
    // row is retired). Muted-or-nothing here — the harness must prove both
    // mutes apply on the REAL template (the DLL's runtime fallback rungs are
    // for unknown skins).
    let Some(ids) = doc.clone_word_segment_with_new_shape_ex(
        "in_marvelous",
        "in_smarvelous",
        word_shape_id,
        ap2::WordCloneOpts {
            mute_additive_glow: true,
            mute_source_additive_glow: true,
        },
    ) else {
        println!("FAIL smarv-patch: recipe returned None");
        return 1;
    };
    println!("muted_records={}", ids.muted_records);
    println!("stock_muted_records={}", ids.muted_source_records);

    // Second pass on a fresh parse: the FALLBACK rung (word_clone_opts(false)
    // — S-Marv mute only) must ALSO apply on the real template with the same
    // ids and clone mute count, leave the stock pulse alone (proving the
    // pulse is real and the source mute is what silences it), and produce
    // the same output size (in-place edits only).
    {
        let Some(mut doc2) = ap2::Ap2Doc::parse(&data) else {
            println!("FAIL smarv-patch: parse (fallback pass)");
            return 1;
        };
        let Some(ids2) = doc2.clone_word_segment_with_new_shape_ex(
            "in_marvelous",
            "in_smarvelous",
            word_shape_id,
            ap2::WordCloneOpts {
                mute_additive_glow: true,
                mute_source_additive_glow: false,
            },
        ) else {
            println!("FAIL smarv-patch: fallback recipe returned None");
            return 1;
        };
        if (ids2.new_shape_id, ids2.new_sprite_id, ids2.muted_records)
            != (ids.new_shape_id, ids.new_sprite_id, ids.muted_records)
        {
            println!("FAIL smarv-patch: fallback pass changed the allocated ids / clone mute count");
            return 1;
        }
        if ids2.muted_source_records != 0 {
            println!("FAIL smarv-patch: fallback pass muted stock records with the source mute off");
            return 1;
        }
        let Some(out2) = doc2.serialize() else {
            println!("FAIL smarv-patch: fallback serialize");
            return 1;
        };
        let Some(re2) = ap2::Ap2Doc::parse(&out2) else {
            println!("FAIL smarv-patch: fallback re-parse");
            return 1;
        };
        let stock2 = re2
            .find_sprite_by_label("in_smarvelous")
            .and_then(|p| re2.section(&p).map(|s| s.clone()))
            .and_then(|sec| {
                let sp = sec.tags.iter().find_map(|t| match t {
                    ap2::Tag::DefineSprite(s) if s.id == ids2.word_sprite_id => Some(s),
                    _ => None,
                })?;
                let mut keys: Vec<(u16, u16)> = Vec::new();
                let mut alphas = Vec::new();
                for t in &sp.section.tags {
                    let ap2::Tag::PlaceObject(po) = t else { continue };
                    let v = po.view()?;
                    let key = (v.object_id, v.depth);
                    if v.flags & 0x1 == 0 && v.blend == Some(8) {
                        keys.push(key);
                    }
                    if keys.contains(&key) {
                        if let Some(m) = v.mult_color {
                            alphas.push(m.alpha);
                        }
                    }
                }
                Some(alphas)
            })
            .unwrap_or_default();
        println!("fallback_stock_additive_alphas={stock2:?}");
        if !stock2.iter().any(|&a| a != 0) {
            println!("FAIL smarv-patch: fallback pass altered the stock additive glow (or it is absent — nothing for the shipped mute to silence)");
            return 1;
        }
        // Size parity with the shipped output is asserted after that
        // output is serialized below.
        println!("fallback_out_len={}", out2.len());
    }
    let Some(mut out) = doc.serialize() else {
        println!("FAIL smarv-patch: serialize");
        return 1;
    };
    println!("shipped_out_len={}", out.len());
    let Some(re) = ap2::Ap2Doc::parse(&out) else {
        println!("FAIL smarv-patch: re-parse");
        return 1;
    };
    let Some(path) = re.find_sprite_by_label("in_smarvelous") else {
        println!("FAIL smarv-patch: in_smarvelous missing");
        return 1;
    };
    let Some(sec) = re.section(&path) else {
        println!("FAIL smarv-patch: section");
        return 1;
    };
    let Some(label_frame) = sec.label_frame("in_smarvelous") else {
        println!("FAIL smarv-patch: label frame");
        return 1;
    };
    println!("word_sprite_id={}", ids.word_sprite_id);
    println!("new_shape_id={}", ids.new_shape_id);
    println!("new_sprite_id={}", ids.new_sprite_id);
    println!("label_frame={label_frame}");
    println!("section_frames={}", sec.frames.len());

    // Mute proof on the serialized SHIPPED output: every additive-blend
    // object in BOTH the CLONED top sprite and the STOCK word sprite has
    // mult alpha 0 on all its records (the fallback pass above proved the
    // stock pulse is real — non-zero before the source mute).
    let additive_alphas = |sprite_id: u16| -> Option<Vec<i32>> {
        let sp = sec.tags.iter().find_map(|t| match t {
            ap2::Tag::DefineSprite(s) if s.id == sprite_id => Some(s),
            _ => None,
        })?;
        let mut keys: Vec<(u16, u16)> = Vec::new();
        let mut alphas = Vec::new();
        for t in &sp.section.tags {
            let ap2::Tag::PlaceObject(po) = t else { continue };
            let v = po.view()?;
            let key = (v.object_id, v.depth);
            if v.flags & 0x1 == 0 && v.blend == Some(8) {
                keys.push(key);
            }
            if keys.contains(&key) {
                if let Some(m) = v.mult_color {
                    alphas.push(m.alpha);
                }
            }
        }
        Some(alphas)
    };
    let cloned = additive_alphas(ids.new_sprite_id).unwrap_or_default();
    let stock = additive_alphas(ids.word_sprite_id).unwrap_or_default();
    println!("cloned_additive_alphas={cloned:?}");
    println!("stock_additive_alphas={stock:?}");
    if cloned.is_empty() || cloned.iter().any(|&a| a != 0) {
        println!("FAIL smarv-patch: cloned additive glow not muted");
        return 1;
    }
    if stock.is_empty() || stock.iter().any(|&a| a != 0) {
        println!("FAIL smarv-patch: stock additive glow not muted in the shipped output");
        return 1;
    }

    // Re-scramble the string table for bemaniutils consumption (its SWF
    // parser always runs the cipher).
    let st_off = u32::from_le_bytes(out[48..52].try_into().unwrap()) as usize;
    let st_size = u32::from_le_bytes(out[52..56].try_into().unwrap()) as usize;
    let scrambled = ap2::encode_string_table(&out[st_off..st_off + st_size]);
    out[st_off..st_off + st_size].copy_from_slice(&scrambled);
    if std::fs::write(out_afp, &out).is_err() {
        println!("FAIL smarv-patch: write {out_afp}");
        return 1;
    }
    println!("smarv-patch OK: wrote {out_afp} ({} bytes)", out.len());
    0
}

/// Step-7 (Leg F): the REAL row-repositioning transform — the same
/// core/ap2 method the DLL's body_tab_detail_result patch calls — on a
/// real template. Rows arrive as "depth:ty:dy,..." (extracted by the
/// script from results_score.rs::ROW_MOVES so the table has ONE source of
/// truth). Verifies the shifted counts, serializes, and writes the
/// re-scrambled output for the bemaniutils position cross-check.
fn smarv_rows(afp: &str, bsi: &str, rows: &str, expected: &str, out_afp: &str) -> i32 {
    let Some(data) = descramble(afp, bsi) else {
        println!("FAIL smarv-rows: descramble");
        return 1;
    };
    let Some(mut doc) = ap2::Ap2Doc::parse(&data) else {
        println!("FAIL smarv-rows: parse");
        return 1;
    };
    let mut table: Vec<(u16, i32, i32)> = Vec::new();
    for entry in rows.split(',') {
        let parts: Vec<&str> = entry.split(':').collect();
        let (Some(d), Some(ty), Some(dy)) = (
            parts.first().and_then(|s| s.parse().ok()),
            parts.get(1).and_then(|s| s.parse().ok()),
            parts.get(2).and_then(|s| s.parse().ok()),
        ) else {
            println!("FAIL smarv-rows: bad row entry '{entry}'");
            return 1;
        };
        table.push((d, ty, dy));
    }
    let Ok(expected_each) = expected.parse::<usize>() else {
        println!("FAIL smarv-rows: bad expected_each '{expected}'");
        return 1;
    };
    if doc.shift_row_translates(&table, expected_each).is_none() {
        println!("FAIL smarv-rows: shift_row_translates refused (count mismatch?)");
        return 1;
    }
    let Some(mut out) = doc.serialize() else {
        println!("FAIL smarv-rows: serialize");
        return 1;
    };
    // Re-parse and verify each row now matches at the SHIFTED position
    // (and no longer at the stock one).
    let Some(re) = ap2::Ap2Doc::parse(&out) else {
        println!("FAIL smarv-rows: re-parse");
        return 1;
    };
    fn count_rows(doc: &ap2::Ap2Doc, depth: u16, ty: i32) -> usize {
        fn walk(sec: &ap2::TagSection, depth: u16, ty: i32) -> usize {
            let mut n = 0;
            for tag in &sec.tags {
                match tag {
                    ap2::Tag::PlaceObject(p) => {
                        if let Some(v) = p.view() {
                            if v.depth == depth && v.translate.map(|(_, y)| y) == Some(ty) {
                                n += 1;
                            }
                        }
                    }
                    ap2::Tag::DefineSprite(s) => n += walk(&s.section, depth, ty),
                    _ => {}
                }
            }
            n
        }
        walk(&doc.root, depth, ty)
    }
    for &(depth, ty, dy) in &table {
        let moved = count_rows(&re, depth, ty + dy);
        let stale = count_rows(&re, depth, ty);
        if moved != expected_each || stale != 0 {
            println!(
                "FAIL smarv-rows: d{depth} ty{ty}+{dy}: moved={moved} (want {expected_each}), stale={stale}"
            );
            return 1;
        }
        println!("row d{depth}: ty {ty} -> {} ({moved} records)", ty + dy);
    }
    // Re-scramble the string table for bemaniutils consumption.
    let st_off = u32::from_le_bytes(out[48..52].try_into().unwrap()) as usize;
    let st_size = u32::from_le_bytes(out[52..56].try_into().unwrap()) as usize;
    let scrambled = ap2::encode_string_table(&out[st_off..st_off + st_size]);
    out[st_off..st_off + st_size].copy_from_slice(&scrambled);
    if std::fs::write(out_afp, &out).is_err() {
        println!("FAIL smarv-rows: write {out_afp}");
        return 1;
    }
    println!("smarv-rows OK: wrote {out_afp} ({} bytes)", out.len());
    0
}

/// Step-13 (Leg H): the DLL's word recipe for a DDR SELECTION legacy
/// skin on its REAL `dance_judge000N` template — the shared geo-first
/// resolver, then the S-Marv-only mute rung (`targets::mute_stock_glow` is
/// false for every legacy skin: A3's MARVELOUS keeps its additive pulse).
/// Asserts: the new region follows `targets::word_region`; the cloned
/// chain's additive copy (when the skin has one) is silent; the STOCK
/// word's additive copy is untouched; the new label exists in every section
/// carrying `in_marvelous` with sorted label tables. Writes the patched file
/// (string table re-scrambled) for the render proof.
fn smarv_legacy_word(afp: &str, bsi: &str, geo_dir: &str, skin: u8, out_afp: &str) -> i32 {
    if !(1..=5).contains(&skin) || targets::mute_stock_glow(skin) {
        println!("FAIL smarv-legacy-word: skin {skin} is not a legacy target");
        return 1;
    }
    let Some(data) = descramble(afp, bsi) else {
        println!("FAIL smarv-legacy-word: descramble");
        return 1;
    };
    let Some(mut doc) = ap2::Ap2Doc::parse(&data) else {
        println!("FAIL smarv-legacy-word: parse");
        return 1;
    };
    let Some((word_shape_id, donor_region)) =
        doc.find_word_shape_by_geo("in_marvelous", "marvelous", |geo_name| {
            let bytes = std::fs::read(format!("{geo_dir}/{geo_name}")).ok()?;
            geo::labels(&bytes)
        })
    else {
        println!("FAIL smarv-legacy-word: word chain unresolved (shared resolver)");
        return 1;
    };
    let Some(new_region) = targets::word_region(&donor_region) else {
        println!("FAIL smarv-legacy-word: donor region {donor_region} has no marvelous suffix");
        return 1;
    };
    if donor_region != format!("dance_judge{skin:04}_marvelous") {
        println!("FAIL smarv-legacy-word: donor region {donor_region} is not skin {skin}'s");
        return 1;
    }
    println!("word_shape_id={word_shape_id}");
    println!("donor_region={donor_region}");
    println!("new_region={new_region}");
    let Some(ids) = doc.clone_word_segment_with_new_shape_ex(
        "in_marvelous",
        "in_smarvelous",
        word_shape_id,
        ap2::WordCloneOpts {
            mute_additive_glow: true,
            mute_source_additive_glow: targets::mute_stock_glow(skin),
        },
    ) else {
        println!("FAIL smarv-legacy-word: recipe returned None");
        return 1;
    };
    println!("new_shape_id={}", ids.new_shape_id);
    println!("new_sprite_id={}", ids.new_sprite_id);
    println!("muted_records={}", ids.muted_records);
    if ids.muted_source_records != 0 {
        println!("FAIL smarv-legacy-word: the stock MARVELOUS pulse was muted");
        return 1;
    }
    let Some(mut out) = doc.serialize() else {
        println!("FAIL smarv-legacy-word: serialize");
        return 1;
    };
    let Some(re) = ap2::Ap2Doc::parse(&out) else {
        println!("FAIL smarv-legacy-word: re-parse");
        return 1;
    };
    // Additive-copy alphas of a word sprite (records of objects whose
    // create has blend 8).
    let additive_alphas = |sec: &ap2::TagSection, sprite_id: u16| -> Vec<i32> {
        let Some(sp) = sec.tags.iter().find_map(|t| match t {
            ap2::Tag::DefineSprite(s) if s.id == sprite_id => Some(s),
            _ => None,
        }) else {
            return Vec::new();
        };
        let mut keys: Vec<(u16, u16)> = Vec::new();
        let mut alphas = Vec::new();
        for t in &sp.section.tags {
            let ap2::Tag::PlaceObject(po) = t else { continue };
            let Some(v) = po.view() else { continue };
            let key = (v.object_id, v.depth);
            if v.flags & 0x1 == 0 && v.blend == Some(8) {
                keys.push(key);
            }
            if keys.contains(&key) {
                if let Some(m) = v.mult_color {
                    alphas.push(m.alpha);
                }
            }
        }
        alphas
    };
    let Some(path) = re.find_sprite_by_label("in_smarvelous") else {
        println!("FAIL smarv-legacy-word: in_smarvelous missing");
        return 1;
    };
    let Some(sec) = re.section(&path) else {
        println!("FAIL smarv-legacy-word: section");
        return 1;
    };
    let cloned = additive_alphas(sec, ids.new_sprite_id);
    let stock = additive_alphas(sec, ids.word_sprite_id);
    println!("cloned_additive_alphas={cloned:?}");
    println!("stock_additive_alphas={stock:?}");
    if cloned.iter().any(|&a| a != 0) {
        println!("FAIL smarv-legacy-word: the S-Marvelous copy still pulses");
        return 1;
    }
    if cloned.len() != stock.len() {
        println!("FAIL smarv-legacy-word: cloned / stock additive record counts differ");
        return 1;
    }
    if !stock.is_empty() && !stock.iter().any(|&a| a != 0) {
        println!("FAIL smarv-legacy-word: the stock MARVELOUS pulse is silent");
        return 1;
    }
    fn check(sec: &ap2::TagSection, path: &str, errs: &mut Vec<String>) {
        let has_src = sec.labels.iter().any(|l| l.name == "in_marvelous");
        let has_new = sec.labels.iter().any(|l| l.name == "in_smarvelous");
        if has_src && !has_new {
            errs.push(format!("{path}: in_marvelous without in_smarvelous"));
        }
        let names: Vec<&str> = sec.labels.iter().map(|l| l.name.as_str()).collect();
        let mut sorted = names.clone();
        sorted.sort();
        if names != sorted {
            errs.push(format!("{path}: label table unsorted"));
        }
        for (i, t) in sec.tags.iter().enumerate() {
            if let ap2::Tag::DefineSprite(sp) = t {
                check(&sp.section, &format!("{path}/{i}"), errs);
            }
        }
    }
    let mut errs = Vec::new();
    check(&re.root, "root", &mut errs);
    if !errs.is_empty() {
        for e in &errs {
            println!("FAIL smarv-legacy-word: {e}");
        }
        return 1;
    }
    let label_frame = sec.label_frame("in_smarvelous").unwrap_or(0);
    println!("label_frame={label_frame}");
    println!("section_frames={}", sec.frames.len());
    let st_off = u32::from_le_bytes(out[48..52].try_into().unwrap()) as usize;
    let st_size = u32::from_le_bytes(out[52..56].try_into().unwrap()) as usize;
    let scrambled = ap2::encode_string_table(&out[st_off..st_off + st_size]);
    out[st_off..st_off + st_size].copy_from_slice(&scrambled);
    if std::fs::write(out_afp, &out).is_err() {
        println!("FAIL smarv-legacy-word: write {out_afp}");
        return 1;
    }
    println!("smarv-legacy-word OK: skin {skin}, wrote {out_afp} ({} bytes)", out.len());
    0
}

/// Step-6 (Leg E) / Step-13 (Leg H): geo-first art-shape resolution + the
/// multi-shape recipe on a REAL dance_fullcombo template (the DLL's staging
/// path). `skin` 0 = World's `dance_fullcombo_v3`, 1..=5 = a DDR SELECTION
/// legacy skin (`targets::fc_expected_shapes` gives the shape count the DLL
/// requires).
fn smarv_fc(afp: &str, bsi: &str, geo_dir: &str, skin: u8) -> i32 {
    let Some(data) = descramble(afp, bsi) else {
        println!("FAIL smarv-fc: descramble");
        return 1;
    };
    let Some(mut doc) = ap2::Ap2Doc::parse(&data) else {
        println!("FAIL smarv-fc: parse");
        return 1;
    };
    // Geo-first: shapes whose geo has a region whose last token starts
    // with "mar" (the DLL's fc_region_rename rule).
    let mut shape_ids: Vec<u16> = Vec::new();
    for tag in &doc.root.tags {
        let ap2::Tag::Shape(shape) = tag else { continue };
        let geo_name = format!("{}_shape{}", doc.exported_name(), shape.id);
        let Ok(bytes) = std::fs::read(format!("{geo_dir}/{geo_name}")) else {
            continue;
        };
        let Some(labels) = geo::labels(&bytes) else { continue };
        if labels.iter().any(|l| targets::fc_region_rename(l).is_some()) {
            shape_ids.push(shape.id);
        }
    }
    let want = targets::fc_expected_shapes(skin);
    if shape_ids.len() != want {
        println!("FAIL smarv-fc: resolved {} art shapes (want {want})", shape_ids.len());
        return 1;
    }
    let Some(ids) =
        doc.clone_segment_with_new_shapes("marbelous_in", "s_marbelous_in", &shape_ids)
    else {
        println!("FAIL smarv-fc: recipe returned None");
        return 1;
    };
    let Some(out) = doc.serialize() else {
        println!("FAIL smarv-fc: serialize");
        return 1;
    };
    let Some(re) = ap2::Ap2Doc::parse(&out) else {
        println!("FAIL smarv-fc: re-parse");
        return 1;
    };
    // The new label must exist in EVERY section that carries the source
    // label (root + inner timeline), and every label table stays sorted.
    fn check(sec: &ap2::TagSection, path: &str, errs: &mut Vec<String>) {
        let has_src = sec.labels.iter().any(|l| l.name == "marbelous_in");
        let has_new = sec.labels.iter().any(|l| l.name == "s_marbelous_in");
        if has_src && !has_new {
            errs.push(format!("{path}: source label without clone"));
        }
        let mut names: Vec<&str> = sec.labels.iter().map(|l| l.name.as_str()).collect();
        let mut sorted = names.clone();
        sorted.sort();
        if names != sorted {
            errs.push(format!("{path}: label table unsorted"));
        }
        names.clear();
        for (i, t) in sec.tags.iter().enumerate() {
            if let ap2::Tag::DefineSprite(sp) = t {
                check(&sp.section, &format!("{path}/{i}"), errs);
            }
        }
    }
    let mut errs = Vec::new();
    check(&re.root, "root", &mut errs);
    if !errs.is_empty() {
        for e in &errs {
            println!("FAIL smarv-fc: {e}");
        }
        return 1;
    }
    println!(
        "smarv-fc OK: shapes {:?} -> {:?}, {} sprite clone(s), {} bytes",
        shape_ids,
        ids.shapes.iter().map(|(_, n)| *n).collect::<Vec<_>>(),
        ids.sprites.len(),
        out.len()
    );
    0
}

/// Step-9 (Leg G): the REAL FC-emblem recipe — geo-first word-shape
/// resolution + the multi-shape clone with the emblem options (HSL-update
/// drop + DoAction loop retarget) on the REAL result_root template, the
/// same call shape the DLL's patch fn runs.
fn smarv_emblem(afp: &str, bsi: &str, geo_dir: &str, out_afp: &str) -> i32 {
    let Some(data) = descramble(afp, bsi) else {
        println!("FAIL smarv-emblem: descramble");
        return 1;
    };
    let Some(mut doc) = ap2::Ap2Doc::parse(&data) else {
        println!("FAIL smarv-emblem: parse");
        return 1;
    };
    // Geo-first word-shape resolution (the DLL's fc_region_rename rule);
    // result_root must resolve EXACTLY ONE (shape 202 -> scre_fc_marvelous).
    let mut shape_ids: Vec<u16> = Vec::new();
    for tag in &doc.root.tags {
        let ap2::Tag::Shape(shape) = tag else { continue };
        let geo_name = format!("{}_shape{}", doc.exported_name(), shape.id);
        let Ok(bytes) = std::fs::read(format!("{geo_dir}/{geo_name}")) else {
            continue;
        };
        let Some(labels) = geo::labels(&bytes) else { continue };
        if labels.iter().any(|l| {
            l.rsplit_once('_').map(|(_, t)| t.starts_with("mar")).unwrap_or(false)
        }) {
            shape_ids.push(shape.id);
        }
    }
    if shape_ids.len() != 1 {
        println!("FAIL smarv-emblem: resolved {} word shapes (want 1)", shape_ids.len());
        return 1;
    }
    let opts = ap2::SegmentCloneOpts {
        drop_hsl_updates_on_remapped: true,
        retarget_actions: true,
    };
    let Some(ids) = doc.clone_segment_with_new_shapes_ex("loop_mfc", "loop_smfc", &shape_ids, opts)
    else {
        println!("FAIL smarv-emblem: recipe returned None");
        return 1;
    };
    let Some(out) = doc.serialize() else {
        println!("FAIL smarv-emblem: serialize");
        return 1;
    };
    let Some(re) = ap2::Ap2Doc::parse(&out) else {
        println!("FAIL smarv-emblem: re-parse");
        return 1;
    };
    // Structural checks on every section carrying the source label.
    let new_sprites: Vec<u16> = ids.sprites.iter().map(|(_, n)| *n).collect();
    fn segment_place_stats(
        sec: &ap2::TagSection,
        label: &str,
        cloned_sprites: &[u16],
    ) -> Option<(usize, usize, Vec<u16>)> {
        // (hsl_updates_on_cloned, do_action_count, cloned create object ids)
        let start = sec.label_frame(label)? as usize;
        let end = sec
            .labels
            .iter()
            .map(|l| l.frame as usize)
            .filter(|f| *f > start)
            .min()
            .unwrap_or(sec.frames.len());
        let mut keys: Vec<(u16, u16)> = Vec::new();
        let mut creates: Vec<u16> = Vec::new();
        let mut hsl = 0usize;
        let mut actions = 0usize;
        for f in &sec.frames[start..end.min(sec.frames.len())] {
            let s = f.start_tag as usize;
            for t in sec.tags.get(s..s + f.tag_count as usize)? {
                match t {
                    ap2::Tag::PlaceObject(po) => {
                        let v = po.view()?;
                        if v.flags & 0x1 == 0 {
                            if let Some(src) = v.source_tag_id {
                                if cloned_sprites.contains(&src) {
                                    keys.push((v.object_id, v.depth));
                                    creates.push(v.object_id);
                                }
                            }
                        } else if v.flags & 0x2000_0000 != 0
                            && keys.contains(&(v.object_id, v.depth))
                        {
                            hsl += 1;
                        }
                    }
                    ap2::Tag::Opaque(o) if o.tag_id == 0x7A => actions += 1,
                    _ => {}
                }
            }
        }
        Some((hsl, actions, creates))
    }
    fn walk(
        sec: &ap2::TagSection,
        path: &str,
        re: &ap2::Ap2Doc,
        new_sprites: &[u16],
        errs: &mut Vec<String>,
        stats: &mut Vec<String>,
    ) {
        let has_src = sec.labels.iter().any(|l| l.name == "loop_mfc");
        let has_new = sec.labels.iter().any(|l| l.name == "loop_smfc");
        if has_src && !has_new {
            errs.push(format!("{path}: source label without clone"));
        }
        if has_new {
            // 1) The cloned word object carries NO HSL updates (static
            //    violet), while the stock segment still animates.
            let clone = segment_place_stats(sec, "loop_smfc", new_sprites);
            match clone {
                Some((hsl, actions, creates)) => {
                    if hsl != 0 {
                        errs.push(format!("{path}: {hsl} HSL update(s) survived the drop"));
                    }
                    if actions == 0 {
                        errs.push(format!("{path}: cloned segment lost its DoAction"));
                    }
                    if creates.is_empty() {
                        errs.push(format!("{path}: no cloned-word create in the segment"));
                    }
                    // 3) id==death-frame: cloned creates outlive the label.
                    if let Some(lf) = sec.label_frame("loop_smfc") {
                        for id in &creates {
                            if *id <= lf {
                                errs.push(format!("{path}: create id {id} <= label frame {lf}"));
                            }
                        }
                    }
                    stats.push(format!(
                        "{path}: hsl_dropped_ok, {actions} action(s), creates {creates:?}"
                    ));
                }
                None => errs.push(format!("{path}: cloned segment unreadable")),
            }
            // 2) Every DoAction in the cloned segment referencing a loop
            //    label must point at loop_smfc (the retarget).
            if let Some(start) = sec.label_frame("loop_smfc") {
                let start = start as usize;
                for f in &sec.frames[start..] {
                    let s = f.start_tag as usize;
                    for t in &sec.tags[s..(s + f.tag_count as usize).min(sec.tags.len())] {
                        if let ap2::Tag::Opaque(o) = t {
                            if o.tag_id == 0x7A && o.data.len() >= 6 && o.data[0] == 0xFF
                                && o.data[1] & 1 == 1
                            {
                                let n = u16::from_le_bytes([o.data[2], o.data[3]]) as usize;
                                for i in 0..n {
                                    let at = 4 + i * 2;
                                    if at + 2 > o.data.len() {
                                        break;
                                    }
                                    let off = u16::from_le_bytes([o.data[at], o.data[at + 1]]);
                                    if let Some(s) = re.strings.get(off) {
                                        if s == "loop_mfc" {
                                            errs.push(format!(
                                                "{path}: cloned DoAction still targets loop_mfc"
                                            ));
                                        } else if s == "loop_smfc" {
                                            stats.push(format!("{path}: DoAction -> loop_smfc"));
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        // Label tables stay name-sorted (binary-searched by the engine).
        let names: Vec<&str> = sec.labels.iter().map(|l| l.name.as_str()).collect();
        let mut sorted = names.clone();
        sorted.sort();
        if names != sorted {
            errs.push(format!("{path}: label table unsorted"));
        }
        for (i, t) in sec.tags.iter().enumerate() {
            if let ap2::Tag::DefineSprite(sp) = t {
                walk(&sp.section, &format!("{path}/{i}"), re, new_sprites, errs, stats);
            }
        }
    }
    let mut errs = Vec::new();
    let mut stats = Vec::new();
    walk(&re.root, "root", &re, &new_sprites, &mut errs, &mut stats);
    if !errs.is_empty() {
        for e in &errs {
            println!("FAIL smarv-emblem: {e}");
        }
        return 1;
    }
    // Re-scramble the string table for bemaniutils consumption (its SWF
    // parser always runs the cipher).
    let mut out = out;
    let st_off = u32::from_le_bytes(out[48..52].try_into().unwrap()) as usize;
    let st_size = u32::from_le_bytes(out[52..56].try_into().unwrap()) as usize;
    let scrambled = ap2::encode_string_table(&out[st_off..st_off + st_size]);
    out[st_off..st_off + st_size].copy_from_slice(&scrambled);
    if std::fs::write(out_afp, &out).is_err() {
        println!("FAIL smarv-emblem: write {out_afp}");
        return 1;
    }
    for s in &stats {
        println!("    {s}");
    }
    println!(
        "smarv-emblem OK: shape {:?} -> {:?}, {} sprite clone(s), {} -> {} bytes",
        shape_ids,
        ids.shapes.iter().map(|(_, n)| *n).collect::<Vec<_>>(),
        ids.sprites.len(),
        data.len(),
        out.len()
    );
    0
}

/// Step-4 task-02 (Leg D): run the REAL GE2D label rewriter — the same
/// core/geo fn the DLL's asset staging calls — on a real geo file.
fn geo_rewrite(input: &str, old_label: &str, new_label: &str, output: &str) -> i32 {
    let Ok(data) = std::fs::read(input) else {
        println!("FAIL geo-rewrite: read {input}");
        return 1;
    };
    let Some(out) = geo::rewrite_labels(&data, |l| {
        if l == old_label {
            Some(new_label.to_string())
        } else {
            None
        }
    }) else {
        println!("FAIL geo-rewrite: rewrite (is '{old_label}' present?)");
        return 1;
    };
    if std::fs::write(output, &out).is_err() {
        println!("FAIL geo-rewrite: write {output}");
        return 1;
    }
    println!(
        "geo-rewrite OK: {} -> {} bytes, '{old_label}' -> '{new_label}'",
        data.len(),
        out.len()
    );
    0
}

/// Step 3 demo: clone `in_marvelous` -> `in_smarvelous` on the REAL
/// dance_judge template. Remapped variant validated structurally; identity
/// variant written out (string table re-scrambled, empty BSI) for
/// bemaniutils parseafp + render consumption.
fn edit_demo(afp: &str, bsi: &str, out_afp: &str, out_bsi: &str) -> i32 {
    let Some(data) = descramble(afp, bsi) else {
        println!("FAIL edit-demo: descramble");
        return 1;
    };

    // ── Remapped variant (structural) ───────────────────────────────
    let Some(mut doc) = ap2::Ap2Doc::parse(&data) else {
        println!("FAIL edit-demo: parse");
        return 1;
    };
    let Some(path) = doc.find_sprite_by_label("in_marvelous") else {
        println!("FAIL edit-demo: in_marvelous label not found");
        return 1;
    };
    let unknown = doc
        .section(&path)
        .into_iter()
        .flat_map(|s| s.tags.iter())
        .find_map(|t| match t {
            ap2::Tag::Shape(s) => Some(s.unknown),
            _ => None,
        })
        .unwrap_or(0);
    let Some(new_id) = doc.add_shape(&path, 0, unknown) else {
        println!("FAIL edit-demo: add_shape");
        return 1;
    };
    // Inserts shift tag indices: re-resolve the path before cloning.
    let Some(path) = doc.find_sprite_by_label("in_marvelous") else {
        println!("FAIL edit-demo: re-resolve after add_shape");
        return 1;
    };
    let src_ids = doc
        .section(&path)
        .map(|s| segment_source_ids(s, "in_marvelous"))
        .unwrap_or_default();
    let Some(&remap_from) = src_ids.first() else {
        println!("FAIL edit-demo: no placeable ids in segment");
        return 1;
    };
    let mut remap = ap2::TagRemap::new();
    remap.insert(remap_from, new_id);
    if doc
        .clone_labeled_segment(&path, "in_marvelous", "in_smarvelous", &remap)
        .is_none()
    {
        println!("FAIL edit-demo: clone (remapped)");
        return 1;
    }
    let Some(out) = doc.serialize() else {
        println!("FAIL edit-demo: serialize (remapped)");
        return 1;
    };
    let Some(re) = ap2::Ap2Doc::parse(&out) else {
        println!("FAIL edit-demo: re-parse (remapped)");
        return 1;
    };
    let Some(re_path) = re.find_sprite_by_label("in_smarvelous") else {
        println!("FAIL edit-demo: in_smarvelous missing (remapped)");
        return 1;
    };
    let cloned_ids = re
        .section(&re_path)
        .map(|s| segment_source_ids(s, "in_smarvelous"))
        .unwrap_or_default();
    if !cloned_ids.contains(&new_id) {
        println!("FAIL edit-demo: clone does not reference new shape id {new_id}");
        return 1;
    }
    println!(
        "remapped variant OK: new_shape_id={new_id} remapped_from={remap_from} ({} bytes)",
        out.len()
    );

    // ── Identity variant (rendered by Leg C) ────────────────────────
    let Some(mut doc) = ap2::Ap2Doc::parse(&data) else {
        println!("FAIL edit-demo: parse (identity)");
        return 1;
    };
    let path = doc.find_sprite_by_label("in_marvelous").unwrap();
    if doc
        .clone_labeled_segment(&path, "in_marvelous", "in_smarvelous", &ap2::TagRemap::new())
        .is_none()
    {
        println!("FAIL edit-demo: clone (identity)");
        return 1;
    }
    let Some(mut out) = doc.serialize() else {
        println!("FAIL edit-demo: serialize (identity)");
        return 1;
    };
    let Some(re) = ap2::Ap2Doc::parse(&out) else {
        println!("FAIL edit-demo: re-parse (identity)");
        return 1;
    };
    let re_path = match re.find_sprite_by_label("in_smarvelous") {
        Some(p) => p,
        None => {
            println!("FAIL edit-demo: in_smarvelous missing (identity)");
            return 1;
        }
    };
    let sec = re.section(&re_path).unwrap();
    let label_frame = sec.label_frame("in_smarvelous").unwrap();
    // The clone appends at the section end: segment = label_frame..len.
    println!("label_frame={label_frame}");
    println!("segment_len={}", sec.frames.len() - label_frame as usize);
    println!("section_frames={}", sec.frames.len());
    println!("root_frames={}", re.root.frames.len());

    // Re-scramble the string table for bemaniutils consumption (its SWF
    // parser always runs the cipher); empty (0-byte) BSI = no byteswaps.
    let st_off = u32::from_le_bytes(out[48..52].try_into().unwrap()) as usize;
    let st_size = u32::from_le_bytes(out[52..56].try_into().unwrap()) as usize;
    let scrambled = ap2::encode_string_table(&out[st_off..st_off + st_size]);
    out[st_off..st_off + st_size].copy_from_slice(&scrambled);
    if std::fs::write(out_afp, &out).is_err() || std::fs::write(out_bsi, b"").is_err() {
        println!("FAIL edit-demo: write outputs");
        return 1;
    }
    println!("identity variant OK: wrote {out_afp}");
    0
}
EOF
else
  # No ap2 module yet: satisfy the [[bin]] target with a stub.
  echo 'fn main() {}' >"$TMP/src/main.rs"
fi

note "running pure module tests (${MODULE_NAMES[*]})"
(cd "$TMP" && cargo test --quiet)
note "synthetic suite OK"

# ── Dev legs (optional) ─────────────────────────────────────────────

if [[ "$HAVE_AP2" != 1 ]]; then
  exit 0
fi
if [[ -z "${DDR_WORLD_INSTALL:-}" || ! -d "${DDR_WORLD_INSTALL:-}/data/arc/bm2d" ]]; then
  skip "dev legs: DDR_WORLD_INSTALL not set or has no data/arc/bm2d"
  exit 0
fi
BEMANIUTILS_DIR="${BEMANIUTILS_DIR:-$REPO_ROOT/../bemaniutils}"
if [[ ! -x "$BEMANIUTILS_DIR/arcutils" || ! -x "$BEMANIUTILS_DIR/ifsutils" || ! -x "$BEMANIUTILS_DIR/afputils" ]]; then
  skip "dev legs: bemaniutils CLIs not found at $BEMANIUTILS_DIR (set BEMANIUTILS_DIR)"
  exit 0
fi

note "building ap2check dev binary"
(cd "$TMP" && cargo build --quiet --bin ap2check)
AP2CHECK="$TMP/target/debug/ap2check"

# The feature's patch targets: gameplay flash, FC splash, results scene.
# The LIVE default packages (cabinet-observed: the game loads the
# UNSUFFIXED _v3 arcs; NNNN_vN arcs are skin/revision variants).
DEV_ARCS=(dance_judge_v3 dance_fullcombo_v3 scene_result_v3 dance_effect_v3)

extract_arc() { # <arc basename> -> echoes the extracted afp/ dir
  local arc="$1" out="$TMP/dev/$1"
  mkdir -p "$out"
  (cd "$BEMANIUTILS_DIR" && ./arcutils "$DDR_WORLD_INSTALL/data/arc/bm2d/$arc.arc" -d "$out") >/dev/null 2>&1 || return 1
  local ifs_file
  ifs_file=$(find "$out" -name "*.ifs" | head -1)
  [[ -n "$ifs_file" ]] || return 1
  (cd "$BEMANIUTILS_DIR" && ./ifsutils "$ifs_file" -d "$out/x") >/dev/null 2>&1 || return 1
  [[ -d "$out/x/afp" ]] || return 1
  echo "$out/x/afp"
}

note "Leg A: real-template round-trip (${DEV_ARCS[*]})"
LEGA_TOTAL=0
for arc in "${DEV_ARCS[@]}"; do
  AFP_DIR=$(extract_arc "$arc") || die "Leg A: extraction failed for $arc"
  FILES=()
  for f in "$AFP_DIR"/*; do
    if [[ -f "$f" && "$f" != *.xml ]]; then
      b="$AFP_DIR/bsi/$(basename "$f")"
      [[ -f "$b" ]] || die "Leg A: missing BSI for $(basename "$f") in $arc"
      FILES+=("$f" "$b")
    fi
  done
  [[ ${#FILES[@]} -gt 0 ]] || die "Leg A: no templates found in $arc"
  "$AP2CHECK" roundtrip "${FILES[@]}" | sed "s/^/    [$arc] /"
  LEGA_TOTAL=$((LEGA_TOTAL + ${#FILES[@]} / 2))
done
note "Leg A OK ($LEGA_TOTAL templates byte-identical)"

note "Leg B: bemaniutils parseafp cross-check"
LEGB_TEMPLATES=(
  "dance_judge_v3:dance_judge"
  "dance_judge_v3:dance_marvelous"
  "scene_result_v3:body_tab_detail_result"
)
for entry in "${LEGB_TEMPLATES[@]}"; do
  arc="${entry%%:*}" tpl="${entry##*:}"
  AFP_DIR="$TMP/dev/$arc/x/afp" # extracted by Leg A
  afp="$AFP_DIR/$tpl" bsi="$AFP_DIR/bsi/$tpl"
  [[ -f "$afp" && -f "$bsi" ]] || die "Leg B: template $tpl not found in $arc"
  # Ours -> normalized lines (drop the file= header).
  "$AP2CHECK" info "$afp" "$bsi" | grep -v '^file=' >"$TMP/dev/ours.txt"
  # Theirs: parseafp JSON -> the same normalized lines.
  (cd "$BEMANIUTILS_DIR" && ./afputils parseafp "$afp" "$bsi") >"$TMP/dev/theirs.json" 2>/dev/null \
    || die "Leg B: afputils parseafp failed for $tpl"
  python3 - "$TMP/dev/theirs.json" >"$TMP/dev/theirs.txt" <<'PYEOF'
import json, sys
d = json.load(open(sys.argv[1]))
print(f"exported_name={d['exported_name']}")
frames = d["frames"]
print(f"frames={len(frames)}")
for i, f in enumerate(frames):
    print(f"frame[{i}]={f['start_tag_offset']},{f['num_tags']}")
PYEOF
  if diff -u "$TMP/dev/theirs.txt" "$TMP/dev/ours.txt" >"$TMP/dev/diff.txt"; then
    echo "    [$arc/$tpl] structural match"
  else
    cat "$TMP/dev/diff.txt"
    die "Leg B: structural mismatch on $arc/$tpl"
  fi
done
note "Leg B OK"

# ── Leg C: real-template edit demo + render preview ────────────────
# Clones in_marvelous -> in_smarvelous on the REAL dance_judge template
# (Step 3's editing primitives), cross-checks the edited file with
# bemaniutils, and renders the cloned segment so a human can eyeball it.
note "Leg C: real-template edit demo (dance_judge)"
DJ_AFP_DIR="$TMP/dev/dance_judge_v3/x/afp" # extracted by Leg A
DJ_IFS=$(find "$TMP/dev/dance_judge_v3" -name "*.ifs" | head -1)
EDIT_DIR="$TMP/dev/edited"
mkdir -p "$EDIT_DIR"
"$AP2CHECK" edit-demo "$DJ_AFP_DIR/dance_judge" "$DJ_AFP_DIR/bsi/dance_judge" \
  "$EDIT_DIR/dance_judge" "$EDIT_DIR/dance_judge.bsi" | tee "$EDIT_DIR/demo.txt" | sed 's/^/    /'
LABEL_FRAME=$(grep -oE '^label_frame=[0-9]+' "$EDIT_DIR/demo.txt" | cut -d= -f2)
SECTION_FRAMES=$(grep -oE '^section_frames=[0-9]+' "$EDIT_DIR/demo.txt" | cut -d= -f2)
[[ -n "$LABEL_FRAME" && -n "$SECTION_FRAMES" ]] || die "Leg C: edit-demo did not report frames"

# Cross-check: bemaniutils must parse the edited file and see the label.
(cd "$BEMANIUTILS_DIR" && ./afputils parseafp "$EDIT_DIR/dance_judge" "$EDIT_DIR/dance_judge.bsi") \
  >"$EDIT_DIR/edited.json" 2>/dev/null || die "Leg C: afputils parseafp rejected the edited file"
python3 - "$EDIT_DIR/edited.json" <<'PYEOF' || die "Leg C: in_smarvelous label not visible to bemaniutils"
import json, sys
d = json.load(open(sys.argv[1]))
def find_labels(node):
    found = {}
    if isinstance(node, dict):
        if "labels" in node and isinstance(node["labels"], dict):
            found.update(node["labels"])
        for v in node.values():
            found.update(find_labels(v))
    elif isinstance(node, list):
        for v in node:
            found.update(find_labels(v))
    return found
labels = find_labels(d)
assert "in_smarvelous" in labels, f"labels seen: {sorted(labels)}"
print(f"    [cross-check] in_smarvelous @ frame {labels['in_smarvelous']} (bemaniutils)")
PYEOF

# Render the cloned segment (identity remap: it should look exactly like
# the stock MARVELOUS flash, played from the new label). Preview lands
# OUTSIDE the repo at a stable path.
PREVIEW_DIR="${TMPDIR:-/tmp}/s_marvelous_preview"
mkdir -p "$PREVIEW_DIR"
python3 - "$BEMANIUTILS_DIR" "$DJ_IFS" "$EDIT_DIR/dance_judge" "$LABEL_FRAME" "$SECTION_FRAMES" \
  "$PREVIEW_DIR/in_smarvelous_identity.gif" <<'PYEOF' || die "Leg C: render failed"
import io, os, sys
bemaniutils_dir, ifs_path, edited_afp, label_frame, section_frames, out_gif = sys.argv[1:7]
sys.path.insert(0, bemaniutils_dir)
from PIL import Image
from bemani.format import IFS
from bemani.format.afp import SWF, Shape, AFPRenderer

ifs = IFS(open(ifs_path, "rb").read(), decode_textures=True)
shapes, textures, swfs = {}, {}, {}
sep = os.sep
for fname in ifs.filenames:
    if fname.startswith(f"geo{sep}"):
        name = fname[4:]
        shape = Shape(name, ifs.read_file(fname))
        shape.parse()
        shapes[name] = shape
    elif fname.startswith(f"tex{sep}") and fname.endswith(".png"):
        textures[fname[4:-4]] = Image.open(io.BytesIO(ifs.read_file(fname)))
    elif fname.startswith(f"afp{sep}") and not fname.startswith(f"afp{sep}bsi{sep}") and not fname.endswith(".xml"):
        name = fname[4:]
        if name == "dance_judge":
            continue  # replaced by the edited template below
        bsi = ifs.read_file(f"afp{sep}bsi{sep}{name}")
        swf = SWF(name, ifs.read_file(fname), bsi)
        swf.parse()
        swfs[name] = swf

edited = SWF("dance_judge", open(edited_afp, "rb").read(), b"")
edited.parse()
swfs["dance_judge"] = edited
assert "in_smarvelous" in edited.labels, f"labels: {edited.labels}"

# The root timeline carries stop() bytecode (in-game the clip is driven by
# label jumps, not free playback). Neutralize DoAction bytecodes on the
# parsed RENDER COPY (index-stable: the tag objects stay in place) so the
# timeline free-runs through the cloned segment. File on disk untouched.
def blank_actions(tags):
    for t in tags:
        if hasattr(t, "bytecode") and t.bytecode is not None:
            t.bytecode.actions = []
        if hasattr(t, "tags"):
            blank_actions(t.tags)

blank_actions(edited.tags)

renderer = AFPRenderer(shapes=shapes, textures=textures, swfs=swfs, single_threaded=True)
# only_frames is 1-based (CLI semantics); the cloned segment occupies the
# appended tail of the section.
start, total = int(label_frame), int(section_frames)
wanted = list(range(start + 1, total + 1))
frames = list(renderer.render_path("dance_judge", only_frames=wanted))
if not frames:
    frames = list(renderer.render_path("dance_judge"))
    print(f"    [render] only_frames empty; fell back to full render ({len(frames)} frames)")
else:
    print(f"    [render] cloned segment frames {start + 1}..{total} rendered")
frames[0].save(out_gif, save_all=True, append_images=frames[1:], duration=1000 // 60, loop=0)
print(f"    [render] {len(frames)} frames -> {out_gif}")
PYEOF
note "Leg C OK — open the preview: ${TMPDIR:-/tmp}/s_marvelous_preview/in_smarvelous_identity.gif"

# ── Leg D: dance_judge REAL patch + render proof ────────────────────
# Step-4 task-02: resolve the §10 word chain from the real geo files,
# run the REAL patch recipe (core/ap2) and the REAL geo rewriter
# (core/geo) on the real template, then render the in_smarvelous segment
# with the renderer's texture dict carrying the mod's word art under the
# NEW region name — the patched preview must show the recolored word.
note "Leg D: dance_judge patched-template render proof (real recipe + geo rewrite)"
GEO_DIR="$TMP/dev/dance_judge_v3/x/geo"
SMARV_DIR="$TMP/dev/smarv"
mkdir -p "$SMARV_DIR"
# Both "Judgement Color" variants must ship (assets::JudgementColor); the
# render uses the default (PURPLE SHADOW).
for v in all_purple purple_shadow; do
  [[ -f "$REPO_ROOT/data_mods/s_marvelous/dance_judge/smarvelous_$v.png" ]] \
    || die "Leg D: word art variant missing: smarvelous_$v.png"
done
WORD_PNG="$REPO_ROOT/data_mods/s_marvelous/dance_judge/smarvelous_purple_shadow.png"

# bemaniutils oracle scan — CROSS-CHECK ONLY (the authoritative resolution
# runs inside smarv-patch via the SHARED core/ap2+core/geo resolver, the
# same code path the DLL's assets.rs stages through).
CHAIN=$(python3 - "$BEMANIUTILS_DIR" "$GEO_DIR" <<'PYEOF'
import os, re, sys
bemaniutils_dir, geo_dir = sys.argv[1:3]
sys.path.insert(0, bemaniutils_dir)
from bemani.format.afp import Shape
for name in sorted(os.listdir(geo_dir)):
    m = re.fullmatch(r"dance_judge_shape(\d+)", name)
    if not m:
        continue
    s = Shape(name, open(os.path.join(geo_dir, name), "rb").read())
    s.parse()
    for d in s.draw_params:
        region = getattr(d, "region", None)
        if region and region.endswith("_marvelous"):
            print(m.group(1), region)
            sys.exit(0)
sys.exit(1)
PYEOF
) || die "Leg D: word chain unresolved (no dance_judge_shape* references a *_marvelous region)"
ORACLE_SHAPE_ID=$(echo "$CHAIN" | awk '{print $1}')
ORACLE_REGION=$(echo "$CHAIN" | awk '{print $2}')

# The REAL AP2 transform + the SHARED word-shape resolution (the same
# core/ap2 recipe and geo-first resolver the DLL patch fn / staging runs).
"$AP2CHECK" smarv-patch "$DJ_AFP_DIR/dance_judge" "$DJ_AFP_DIR/bsi/dance_judge" \
  "$GEO_DIR" "$SMARV_DIR/dance_judge" | tee "$SMARV_DIR/patch.txt" | sed 's/^/    /'
WORD_SHAPE_ID=$(grep -oE '^word_shape_id=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
DONOR_REGION=$(grep -oE '^donor_region=.*' "$SMARV_DIR/patch.txt" | cut -d= -f2)
NEW_REGION="${DONOR_REGION%marvelous}smarvelous"
[[ "$WORD_SHAPE_ID" == "$ORACLE_SHAPE_ID" && "$DONOR_REGION" == "$ORACLE_REGION" ]] \
  || die "Leg D: shared resolver ($WORD_SHAPE_ID/$DONOR_REGION) disagrees with the bemaniutils oracle ($ORACLE_SHAPE_ID/$ORACLE_REGION)"
echo "    [chain] word shape $WORD_SHAPE_ID, region $DONOR_REGION -> $NEW_REGION (oracle agrees)"
NEW_SHAPE_ID=$(grep -oE '^new_shape_id=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
D_LABEL_FRAME=$(grep -oE '^label_frame=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
D_SECTION_FRAMES=$(grep -oE '^section_frames=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
[[ -n "$NEW_SHAPE_ID" && -n "$D_LABEL_FRAME" && -n "$D_SECTION_FRAMES" ]] \
  || die "Leg D: smarv-patch did not report ids"
D_MUTED=$(grep -oE '^muted_records=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
[[ -n "$D_MUTED" && "$D_MUTED" -gt 0 ]] \
  || die "Leg D: additive-glow mute edited no records in the cloned chain on the real template (expected the marvelous_ef create + updates)"
D_STOCK_MUTED=$(grep -oE '^stock_muted_records=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
[[ -n "$D_STOCK_MUTED" && "$D_STOCK_MUTED" -gt 0 ]] \
  || die "Leg D: the shipped recipe muted no STOCK Marvelous records on the real template"
echo "    [glow] shipped recipe: $D_MUTED additive-glow records muted in the cloned chain + $D_STOCK_MUTED in the stock Marvelous word (both asserted silent by smarv-patch)"
D_LEN_SHIPPED=$(grep -oE '^shipped_out_len=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
D_LEN_FALLBACK=$(grep -oE '^fallback_out_len=[0-9]+' "$SMARV_DIR/patch.txt" | cut -d= -f2)
[[ -n "$D_LEN_SHIPPED" && "$D_LEN_SHIPPED" == "$D_LEN_FALLBACK" ]] \
  || die "Leg D: shipped/fallback outputs differ in size ($D_LEN_SHIPPED vs $D_LEN_FALLBACK) — the stock mute must be in-place"
echo "    [glow] fallback rung (S-Marv mute only): same ids, stock pulse left alone, same output size"

# The REAL geo rewrite (same core/geo fn the DLL asset staging runs).
"$AP2CHECK" geo-rewrite "$GEO_DIR/dance_judge_shape${WORD_SHAPE_ID}" \
  "$DONOR_REGION" "$NEW_REGION" "$SMARV_DIR/dance_judge_shape${NEW_SHAPE_ID}" | sed 's/^/    /'

# Render the patched segment with the new region mapped to the mod's art.
python3 - "$BEMANIUTILS_DIR" "$DJ_IFS" "$SMARV_DIR/dance_judge" \
  "$SMARV_DIR/dance_judge_shape${NEW_SHAPE_ID}" "dance_judge_shape${NEW_SHAPE_ID}" \
  "$NEW_REGION" "$WORD_PNG" "$D_LABEL_FRAME" "$D_SECTION_FRAMES" \
  "$PREVIEW_DIR/in_smarvelous_patched.gif" <<'PYEOF' || die "Leg D: render failed"
import io, os, sys
(bemaniutils_dir, ifs_path, patched_afp, new_geo_path, new_geo_name,
 new_region, word_png, label_frame, section_frames, out_gif) = sys.argv[1:11]
sys.path.insert(0, bemaniutils_dir)
from PIL import Image
from bemani.format import IFS
from bemani.format.afp import SWF, Shape, AFPRenderer

ifs = IFS(open(ifs_path, "rb").read(), decode_textures=True)
shapes, textures, swfs = {}, {}, {}
sep = os.sep
for fname in ifs.filenames:
    if fname.startswith(f"geo{sep}"):
        name = fname[4:]
        shape = Shape(name, ifs.read_file(fname))
        shape.parse()
        shapes[name] = shape
    elif fname.startswith(f"tex{sep}") and fname.endswith(".png"):
        textures[fname[4:-4]] = Image.open(io.BytesIO(ifs.read_file(fname)))
    elif fname.startswith(f"afp{sep}") and not fname.startswith(f"afp{sep}bsi{sep}") and not fname.endswith(".xml"):
        name = fname[4:]
        if name == "dance_judge":
            continue  # replaced by the patched template below
        bsi = ifs.read_file(f"afp{sep}bsi{sep}{name}")
        swf = SWF(name, ifs.read_file(fname), bsi)
        swf.parse()
        swfs[name] = swf

# The REWRITTEN geo, registered under the name the new shape id demands.
# (Shape.parse validates the GE2D filesize field — a real oracle for the
# length-changing label rebuild.)
new_shape = Shape(new_geo_name, open(new_geo_path, "rb").read())
new_shape.parse()
shapes[new_geo_name] = new_shape
regions = [getattr(d, "region", None) for d in new_shape.draw_params]
assert new_region in regions, f"rewritten geo references {regions}, wanted {new_region}"

# The new region name maps to the mod's word art (what the donor-anchored
# atlas clone serves in-game).
textures[new_region] = Image.open(word_png)

patched = SWF("dance_judge", open(patched_afp, "rb").read(), b"")
patched.parse()
swfs["dance_judge"] = patched
assert "in_smarvelous" in patched.labels, f"labels: {patched.labels}"

# Neutralize DoAction bytecodes on the render copy (Leg C precedent) so
# the timeline free-runs through the cloned segment.
def blank_actions(tags):
    for t in tags:
        if hasattr(t, "bytecode") and t.bytecode is not None:
            t.bytecode.actions = []
        if hasattr(t, "tags"):
            blank_actions(t.tags)

blank_actions(patched.tags)

renderer = AFPRenderer(shapes=shapes, textures=textures, swfs=swfs, single_threaded=True)
start, total = int(label_frame), int(section_frames)
wanted = list(range(start + 1, total + 1))
frames = list(renderer.render_path("dance_judge", only_frames=wanted))
assert frames, "patched segment rendered no frames"
assert any(f.getbbox() for f in frames), "patched segment rendered fully blank"
print(f"    [render] patched segment frames {start + 1}..{total} rendered ({len(frames)} frames, non-blank)")
frames[0].save(out_gif, save_all=True, append_images=frames[1:], duration=1000 // 60, loop=0)
print(f"    [render] preview -> {out_gif}")
PYEOF
note "Leg D OK — open the patched preview: ${TMPDIR:-/tmp}/s_marvelous_preview/in_smarvelous_patched.gif"

# ── Leg E: dance_fullcombo multi-shape recipe on all four templates ──
note "Leg E: dance_fullcombo multi-shape clone (4 templates)"
FC_AFP_DIR="$TMP/dev/dance_fullcombo_v3/x/afp" # extracted by Leg A
FC_GEO_DIR="$TMP/dev/dance_fullcombo_v3/x/geo"
for tpl in 01_fullcombo_single_normal 01_fullcombo_single_reverse \
           02_fullcombo_double_normal 02_fullcombo_double_reverse; do
  OUT=$("$AP2CHECK" smarv-fc "$FC_AFP_DIR/$tpl" "$FC_AFP_DIR/bsi/$tpl" "$FC_GEO_DIR")
  echo "$OUT" | sed "s/^/    [$tpl] /"
  echo "$OUT" | grep -q "smarv-fc OK" || die "Leg E: $tpl failed"
done
note "Leg E OK (4 templates)"

# ── Leg F: results-tab row repositioning on the REAL template ────────
# Runs the DLL's actual transform (Ap2Doc::shift_row_translates with the
# ROW_MOVES table extracted from results_score.rs — one source of truth),
# then cross-checks the six named row instances' new positions with
# bemaniutils.
note "Leg F: body_tab_detail_result row repositioning"
SR_AFP_DIR="$TMP/dev/scene_result_v3/x/afp" # extracted by Leg A
ROWS_SRC="$REPO_ROOT/src/mods/s_marvelous/results_score.rs"
ROWS=$(awk '/pub const ROW_MOVES/,/^\];/' "$ROWS_SRC" \
  | grep -oE '\([0-9]+, [0-9]+, [0-9]+\)' \
  | sed -E 's/\(([0-9]+), ([0-9]+), ([0-9]+)\)/\1:\2:\3/' | paste -sd, -)
EXPECTED=$(grep -oE 'ROW_MOVES_EXPECTED_EACH: usize = [0-9]+' "$ROWS_SRC" | grep -oE '[0-9]+$')
[[ -n "$ROWS" && -n "$EXPECTED" ]] || die "Leg F: could not extract ROW_MOVES from results_score.rs"
note "Leg F rows: $ROWS (expected_each $EXPECTED)"
DETAIL_OUT="$TMP/dev/smarv_rows"
mkdir -p "$DETAIL_OUT"
OUT=$("$AP2CHECK" smarv-rows "$SR_AFP_DIR/body_tab_detail_result" \
  "$SR_AFP_DIR/bsi/body_tab_detail_result" "$ROWS" "$EXPECTED" \
  "$DETAIL_OUT/body_tab_detail_result")
echo "$OUT" | sed 's/^/    /'
echo "$OUT" | grep -q "smarv-rows OK" || die "Leg F: transform failed"
cp "$SR_AFP_DIR/bsi/body_tab_detail_result" "$DETAIL_OUT/bsi_body_tab_detail_result" 2>/dev/null || true
: >"$DETAIL_OUT/empty_bsi"
(cd "$BEMANIUTILS_DIR" && ./afputils parseafp "$DETAIL_OUT/body_tab_detail_result" "$DETAIL_OUT/empty_bsi") \
  >"$DETAIL_OUT/patched.json" 2>/dev/null || die "Leg F: afputils parseafp rejected the patched file"
python3 - "$DETAIL_OUT/patched.json" <<'PYEOF' || die "Leg F: row positions wrong in bemaniutils view"
import json, sys
doc = json.load(open(sys.argv[1]))
# Target grid: 16px pitch from ty 43 (S-MARV slot on top); the six stock
# rows land at 59..139.
want = {
    "marvelous_num_usr": 59.0, "perfect_num_usr": 75.0, "great_num_usr": 91.0,
    "good_num_usr": 107.0, "ok_num_usr": 123.0, "miss_num_usr": 139.0,
}
seen = {}
def walk(tags, where):
    for t in tags:
        ty = t.get("type")
        if ty == "AP2DefineSpriteTag":
            walk(t.get("tags", []), f"sprite{t.get('id')}")
        elif ty == "AP2PlaceObjectTag":
            n = t.get("movie_name")
            if n in want:
                tr = t.get("transform") or {}
                seen.setdefault(n, []).append((where, tr.get("ty")))
walk(doc["tags"], "root")
ok = True
for name, target in want.items():
    got = seen.get(name, [])
    # Named f0 placement exists in root AND the sprite copy, both at target.
    if len(got) != 2 or any(ty != target for _, ty in got):
        print(f"    [F] {name}: want ty {target} x2, got {got}")
        ok = False
    else:
        print(f"    [F] {name}: ty {target} (root + sprite copy)")
sys.exit(0 if ok else 1)
PYEOF
note "Leg F OK"

# ── Leg G: FC-emblem clone on the REAL result_root template ──────────
# Runs the DLL's actual recipe (clone_segment_with_new_shapes_ex with the
# emblem options: HSL-update drop + gotoAndPlay retarget) and verifies the
# cloned segment structurally, then cross-checks bemaniutils accepts the
# patched file.
note "Leg G: result_root FC-emblem clone (loop_mfc -> loop_smfc)"
SR_GEO_DIR="$TMP/dev/scene_result_v3/x/geo"
EMBLEM_OUT="$TMP/dev/smarv_emblem"
mkdir -p "$EMBLEM_OUT"
OUT=$("$AP2CHECK" smarv-emblem "$SR_AFP_DIR/result_root" \
  "$SR_AFP_DIR/bsi/result_root" "$SR_GEO_DIR" "$EMBLEM_OUT/result_root")
echo "$OUT" | sed 's/^/    /'
echo "$OUT" | grep -q "smarv-emblem OK" || die "Leg G: emblem clone failed"
: >"$EMBLEM_OUT/empty_bsi"
(cd "$BEMANIUTILS_DIR" && ./afputils parseafp "$EMBLEM_OUT/result_root" "$EMBLEM_OUT/empty_bsi") \
  >"$EMBLEM_OUT/patched.json" 2>/dev/null || die "Leg G: afputils parseafp rejected the patched file"
python3 - "$EMBLEM_OUT/patched.json" <<'PYEOF' || die "Leg G: loop_smfc missing in bemaniutils view"
import json, sys
doc = json.load(open(sys.argv[1]))
found = []
def walk(tags):
    for t in tags:
        lf = t.get("labels") or {}
        if "loop_smfc" in lf:
            found.append((t.get("id"), lf["loop_smfc"], lf.get("loop_mfc")))
        walk(t.get("tags", []))
walk(doc["tags"])
assert found, "no section carries loop_smfc"
for sid, smfc, mfc in found:
    print(f"    [G] sprite {sid}: loop_smfc @ {smfc} (stock loop_mfc @ {mfc})")
PYEOF
note "Leg G OK"

# ── Leg H: DDR SELECTION legacy skins (Step 13) ─────────────────────
# Per legacy skin 1..5: the DLL's word recipe on dance_judge000N (the
# S-Marv-only mute — A3's MARVELOUS keeps its pulse) + a render proof with
# the shipped legacy art, the multi-shape splash recipe (five Marvelous
# shapes) on the four dance_fullcombo000N templates, and a size check of
# every shipped legacy art file against its donor's imgrect (the
# donor-anchored clone and the per-image serving both place it there).
LEGACY_ART="$REPO_ROOT/data_mods/ddr_selection/s_marvelous"
note "Leg H: DDR SELECTION legacy skins (word, S-MFC splash, art sizes)"
extract_arc_file() { # <arc path> <name> -> echoes the extracted afp/ dir
  local path="$1" out="$TMP/dev/$2"
  mkdir -p "$out"
  (cd "$BEMANIUTILS_DIR" && ./arcutils "$path" -d "$out") >/dev/null 2>&1 || return 1
  local ifs_file
  ifs_file=$(find "$out" -name "*.ifs" | head -1)
  [[ -n "$ifs_file" ]] || return 1
  (cd "$BEMANIUTILS_DIR" && ./ifsutils "$ifs_file" -d "$out/x") >/dev/null 2>&1 || return 1
  [[ -d "$out/x/afp" ]] || return 1
  echo "$out/x/afp"
}
for skin in 1 2 3 4 5; do
  [[ -d "$LEGACY_ART/$skin" ]] || die "Leg H: legacy art missing: data_mods/ddr_selection/s_marvelous/$skin"
  J="dance_judge000${skin}_v0"
  F="dance_fullcombo000${skin}_v0"
  JDIR=$(extract_arc "$J") || die "Leg H: extraction failed for $J"
  FDIR=$(extract_arc "$F") || die "Leg H: extraction failed for $F"
  WOUT="$TMP/dev/$J/smarv"
  mkdir -p "$WOUT"
  OUT=$("$AP2CHECK" smarv-legacy-word "$JDIR/dance_judge" "$JDIR/bsi/dance_judge" \
    "$TMP/dev/$J/x/geo" "$skin" "$WOUT/dance_judge")
  echo "$OUT" | grep -E "OK|FAIL|muted|alphas" | sed "s/^/    [skin $skin] /"
  echo "$OUT" | grep -q "smarv-legacy-word OK" || die "Leg H: skin $skin word recipe failed"
  W_SHAPE=$(echo "$OUT" | grep -oE '^word_shape_id=[0-9]+' | cut -d= -f2)
  W_NEW=$(echo "$OUT" | grep -oE '^new_shape_id=[0-9]+' | cut -d= -f2)
  W_DONOR=$(echo "$OUT" | grep -oE '^donor_region=.*' | cut -d= -f2)
  W_REGION=$(echo "$OUT" | grep -oE '^new_region=.*' | cut -d= -f2)
  W_LABEL=$(echo "$OUT" | grep -oE '^label_frame=[0-9]+' | cut -d= -f2)
  W_FRAMES=$(echo "$OUT" | grep -oE '^section_frames=[0-9]+' | cut -d= -f2)
  "$AP2CHECK" geo-rewrite "$TMP/dev/$J/x/geo/dance_judge_shape${W_SHAPE}" \
    "$W_DONOR" "$W_REGION" "$WOUT/dance_judge_shape${W_NEW}" >/dev/null \
    || die "Leg H: skin $skin geo rewrite failed"
  for v in all_purple purple_shadow; do
    [[ -f "$LEGACY_ART/$skin/dance_judge/smarvelous_$v.png" ]] \
      || die "Leg H: skin $skin word art missing: smarvelous_$v.png"
  done
  python3 - "$BEMANIUTILS_DIR" "$(find "$TMP/dev/$J" -name "*.ifs" | head -1)" "$WOUT/dance_judge" \
    "$WOUT/dance_judge_shape${W_NEW}" "dance_judge_shape${W_NEW}" "$W_REGION" \
    "$LEGACY_ART/$skin/dance_judge/smarvelous_purple_shadow.png" "$W_LABEL" "$W_FRAMES" \
    "$PREVIEW_DIR/legacy_skin${skin}_in_smarvelous.gif" <<'PYEOF' || die "Leg H: skin $skin word render failed"
import io, os, sys
(bemaniutils_dir, ifs_path, patched_afp, new_geo_path, new_geo_name,
 new_region, word_png, label_frame, section_frames, out_gif) = sys.argv[1:11]
sys.path.insert(0, bemaniutils_dir)
from PIL import Image
from bemani.format import IFS
from bemani.format.afp import SWF, Shape, AFPRenderer
ifs = IFS(open(ifs_path, "rb").read(), decode_textures=True)
shapes, textures, swfs = {}, {}, {}
sep = os.sep
for fname in ifs.filenames:
    if fname.startswith(f"geo{sep}"):
        shape = Shape(fname[4:], ifs.read_file(fname)); shape.parse(); shapes[fname[4:]] = shape
    elif fname.startswith(f"tex{sep}") and fname.endswith(".png"):
        textures[fname[4:-4]] = Image.open(io.BytesIO(ifs.read_file(fname)))
    elif fname.startswith(f"afp{sep}") and not fname.startswith(f"afp{sep}bsi{sep}") and not fname.endswith(".xml"):
        name = fname[4:]
        if name == "dance_judge":
            continue
        swf = SWF(name, ifs.read_file(fname), ifs.read_file(f"afp{sep}bsi{sep}{name}")); swf.parse(); swfs[name] = swf
new_shape = Shape(new_geo_name, open(new_geo_path, "rb").read()); new_shape.parse()
shapes[new_geo_name] = new_shape
assert new_region in [getattr(d, "region", None) for d in new_shape.draw_params]
textures[new_region] = Image.open(word_png)
patched = SWF("dance_judge", open(patched_afp, "rb").read(), b""); patched.parse()
swfs["dance_judge"] = patched
assert "in_smarvelous" in patched.labels, patched.labels
def blank_actions(tags):
    for t in tags:
        if hasattr(t, "bytecode") and t.bytecode is not None:
            t.bytecode.actions = []
        if hasattr(t, "tags"):
            blank_actions(t.tags)
blank_actions(patched.tags)
renderer = AFPRenderer(shapes=shapes, textures=textures, swfs=swfs, single_threaded=True)
start, total = int(label_frame), int(section_frames)
frames = list(renderer.render_path("dance_judge", only_frames=list(range(start + 1, total + 1))))
assert frames and any(f.getbbox() for f in frames), "patched segment rendered blank"
frames[0].save(out_gif, save_all=True, append_images=frames[1:], duration=1000 // 60, loop=0)
print(f"    [render] {len(frames)} frames -> {out_gif}")
PYEOF
  for tpl in 01_fullcombo_single_normal 01_fullcombo_single_reverse \
    02_fullcombo_double_normal 02_fullcombo_double_reverse; do
    OUT=$("$AP2CHECK" smarv-fc "$FDIR/$tpl" "$FDIR/bsi/$tpl" "$TMP/dev/$F/x/geo" "$skin")
    echo "$OUT" | sed "s/^/    [skin $skin $tpl] /"
    echo "$OUT" | grep -q "smarv-fc OK" || die "Leg H: skin $skin $tpl splash recipe failed"
  done
done
# Art sizes vs the donors' imgrects. Skin 5's combo reads the A3 import
# (World ships a blanked dance_combo0005), else World's data/, else the A3
# install; skipped with a notice when none is readable.
for skin in 4 5; do
  C="dance_combo000${skin}_v0"
  for cand in "$DDR_WORLD_INSTALL/data_mods/ddr_selection_a3/arc/bm2d/$C.arc" \
    "$DDR_WORLD_INSTALL/data/arc/bm2d/$C.arc" "${DDR_A3_INSTALL:-/nonexistent}/data/arc/bm2d/$C.arc"; do
    [[ -f "$cand" ]] || continue
    rm -rf "$TMP/dev/$C"
    extract_arc_file "$cand" "$C" >/dev/null && [[ -f "$TMP/dev/$C/x/tex/texturelist.xml" ]] && break
    rm -rf "$TMP/dev/$C"
  done
done
if ! python3 -c "import kbinxml" 2>/dev/null; then
  skip "Leg H art sizes: python kbinxml not installed (pip install ifstools)"
else
python3 - "$LEGACY_ART" "$TMP/dev" <<'PYEOF' || die "Leg H: legacy art sizes wrong"
import os, re, sys
from PIL import Image
art, dev = sys.argv[1:3]
def rects(ifs_dir):
    raw = open(os.path.join(ifs_dir, "x", "tex", "texturelist.xml"), "rb").read()
    if raw.lstrip().startswith(b"<"):
        xml = raw.decode("utf-8")
    else:  # binary kbin (what ifsutils writes) — kbinxml ships with ifstools
        from kbinxml import KBinXML
        xml = KBinXML(raw).to_text()
    out = {}
    for m in re.finditer(r'<image name="([^"]+)">(.*?)</image>', xml, re.S):
        r = re.search(r"<imgrect[^>]*>([^<]+)</imgrect>", m.group(2))
        x0, x1, y0, y1 = (int(v) for v in r.group(1).split())
        out[m.group(1)] = ((x1 - x0) // 2, (y1 - y0) // 2)
    return out
def rename(region):
    head, sep, tail = region.rpartition("_")
    return f"{head}_s{tail}" if sep and tail.startswith("mar") else None
bad = checked = 0
def check(path, want):
    global bad, checked
    if not os.path.isfile(path):
        print(f"    [H] MISSING {os.path.relpath(path, art)}"); bad += 1; return
    got = Image.open(path).size
    checked += 1
    if got != want:
        print(f"    [H] SIZE {os.path.relpath(path, art)}: {got} vs donor {want}"); bad += 1
for skin in range(1, 6):
    j = rects(os.path.join(dev, f"dance_judge000{skin}_v0"))
    for v in ("all_purple", "purple_shadow"):
        check(os.path.join(art, str(skin), "dance_judge", f"smarvelous_{v}.png"), j[f"dance_judge000{skin}_marvelous"])
    f = rects(os.path.join(dev, f"dance_fullcombo000{skin}_v0"))
    regions = [(r, rename(r)) for r in f if rename(r)]
    if len(regions) != 5:
        print(f"    [H] skin {skin}: {len(regions)} splash regions (want 5)"); bad += 1
    for donor, new in regions:
        check(os.path.join(art, str(skin), "dance_fullcombo", f"{new}.png"), f[donor])
    if skin in (4, 5):
        cdir = os.path.join(dev, f"dance_combo000{skin}_v0")
        if not os.path.isfile(os.path.join(cdir, "x", "tex", "texturelist.xml")):
            print(f"    [H] skin {skin}: no readable dance_combo000{skin} (A3 import?) -- combo sizes skipped")
            continue
        c = rects(cdir)
        for key in [str(d) for d in range(10)] + ["combo"]:
            check(os.path.join(art, str(skin), "dance_combo", f"smarvelous_{key}.png"), c[f"dance_combo000{skin}_marvelous_{key}"])
    elif os.path.isdir(os.path.join(art, str(skin), "dance_combo")):
        print(f"    [H] skin {skin}: has combo art, but A3 drew one sheet on this skin"); bad += 1
print(f"    [H] {checked} legacy art file(s) match their donors" + ("" if not bad else f", {bad} problem(s)"))
sys.exit(1 if bad else 0)
PYEOF
fi
note "Leg H OK — legacy previews: ${TMPDIR:-/tmp}/s_marvelous_preview/legacy_skin*_in_smarvelous.gif"
note "OK"
