#!/usr/bin/env bash
# Offline validation for `src/services/se_bank_synth` — the assist-tick
# pre-mixed-track synthesis module (implementation plan Step 1's tests).
#
# Usage:
#   ./scripts/validate_se_bank_synth.sh                    # sibling checkout at ../ddr-chart-tools
#   ./scripts/validate_se_bank_synth.sh --chart-tools <p>  # point at the checkout explicitly
#
# What it does: builds a throwaway HOST cargo harness in a temp directory that
# compiles the module's format submodules (adpcm/xsb/xwb/containers — which
# are deliberately free of DLL-crate dependencies) side by side with the
# sibling `ddr-chart-tools` library as a path dependency, then asserts:
#
#   1. XSB byte-identity: our `xsb::build_se` == the sibling `xsb::write_se`
#      for the same name (the generator the shipped banks came from) — checked
#      for both the port-proof name "asti" and the live BANK_NAME.
#   2. The XWB parses with the sibling's container parser and every field the
#      engine's validator checks matches the stock in-memory-bank profile
#      (flags, header_version, element sizes, alignment, rigid segment
#      layout, entry flags/duration/loop rules).
#   3. The sample-segment math: `sample_seg_offset`/`sample_seg_len` equal the
#      header's segment-4 descriptor and run exactly to EOF.
#   4. The mixer places claps SAMPLE-EXACTLY: a known 500 ms test pattern is
#      synthesized with the real committed clap asset, decoded back with the
#      sibling's ADPCM decoder, and each onset's cross-correlation peak must
#      sit at offset 0 (±0 samples).
#   5. Encoder port fidelity: the Assist Tick encoder and shared XACT encoder
#      are byte-identical to the sibling `adpcm::encode` for mono and stereo
#      exact-block input, including encoded silence.
#   6. Determinism: two syntheses of the same input are byte-identical.
#   7. Clip/drop bookkeeping (content_ms < 0 clips to 0; >= capacity drops).
#
# Requires: cargo (host toolchain) and a ddr-chart-tools SOURCE checkout
# (--chart-tools, DDR_CHART_TOOLS, or ../ddr-chart-tools). Nothing else; no
# game install, no Windows toolchain.
#
# This script is validation only — it writes nothing into the repository.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }

CHART_TOOLS="${DDR_CHART_TOOLS:-}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --chart-tools) [[ $# -ge 2 ]] || die "--chart-tools needs a path"; CHART_TOOLS="$2"; shift 2 ;;
    -h|--help)     sed -n '2,/^$/p' "$0"; exit 0 ;;
    *)             die "unknown option: $1" ;;
  esac
done
if [[ -z "$CHART_TOOLS" && -f "$REPO_ROOT/../ddr-chart-tools/Cargo.toml" ]]; then
  CHART_TOOLS="$REPO_ROOT/../ddr-chart-tools"
fi
[[ -n "$CHART_TOOLS" && -f "$CHART_TOOLS/Cargo.toml" ]] \
  || die "need a ddr-chart-tools SOURCE checkout (--chart-tools <path>, DDR_CHART_TOOLS, or ../ddr-chart-tools)"
CHART_TOOLS="$(cd "$CHART_TOOLS" && pwd)"

CLAP_PCM="$REPO_ROOT/data_mods/assist_tick/clap_44k_mono.pcm"
[[ -r "$CLAP_PCM" ]] || die "clap asset missing: data_mods/assist_tick/clap_44k_mono.pcm"

SYNTH_SRC="$REPO_ROOT/src/services/se_bank_synth"
for f in adpcm.rs xsb.rs xwb.rs containers.rs; do
  [[ -r "$SYNTH_SRC/$f" ]] || die "module source missing: src/services/se_bank_synth/$f"
done
XACT_SRC="$REPO_ROOT/src/core/xact"
for f in mod.rs adpcm.rs xwb.rs; do
  [[ -r "$XACT_SRC/$f" ]] || die "module source missing: src/core/xact/$f"
done

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<EOF
[package]
name = "se-bank-synth-validate"
version = "0.0.0"
edition = "2021"

[dependencies]
ddr-chart-tools = { path = "$CHART_TOOLS" }

[workspace]
EOF

mkdir -p "$TMP/src"
cat >"$TMP/src/main.rs" <<EOF
//! Throwaway offline-validation harness — generated by
//! scripts/validate_se_bank_synth.sh; never committed.

mod core {
    #[path = "$XACT_SRC/mod.rs"]
    pub mod xact;
}

mod synth {
    #[path = "$SYNTH_SRC/adpcm.rs"]
    pub mod adpcm;
    #[path = "$SYNTH_SRC/xsb.rs"]
    pub mod xsb;
    #[path = "$SYNTH_SRC/xwb.rs"]
    pub mod xwb;
    #[path = "$SYNTH_SRC/containers.rs"]
    pub mod containers;
}

use ddr_chart_tools::xwb::adpcm::decode as sib_decode;
use ddr_chart_tools::xwb::adpcm::encode as sib_encode;
use ddr_chart_tools::xwb::{container as sib_container, WaveFormat};
use ddr_chart_tools::xsb as sib_xsb;
use core::xact::{adpcm as shared_adpcm, WaveFormat as SharedWaveFormat};
use synth::containers as ours;

const CLAP_PCM: &str = "$CLAP_PCM";
const PATTERN_STEP_MS: i32 = 500;
const PATTERN_TICKS: i32 = 40;

fn check(name: &str, ok: bool, detail: String) -> bool {
    if ok {
        println!("PASS  {name}");
    } else {
        println!("FAIL  {name}: {detail}");
    }
    ok
}

fn read_u32(b: &[u8], off: usize) -> u32 {
    u32::from_le_bytes(b[off..off + 4].try_into().unwrap())
}

fn main() {
    let mut ok = true;

    // ── 1. XSB byte-identity against the sibling generator ──────────
    for name in ["asti", ours::BANK_NAME] {
        let our_xsb = synth::xsb::build_se(name);
        let mut sib = Vec::new();
        sib_xsb::write_se(name, &mut sib).expect("sibling write_se");
        ok &= check(
            &format!("xsb byte-identical to sibling write_se({name:?})"),
            our_xsb == sib,
            format!(
                "ours {} B vs sibling {} B, first diff at {:?}",
                our_xsb.len(),
                sib.len(),
                our_xsb.iter().zip(sib.iter()).position(|(a, b)| a != b)
            ),
        );
    }

    // ── 2 + 3. Container framing + validator rules + segment math ───
    let c = ours::build_tick_containers();
    ok &= check(
        "sample segment runs exactly to EOF",
        c.sample_seg_offset + c.sample_seg_len == c.xwb_bytes.len(),
        format!(
            "{} + {} != {}",
            c.sample_seg_offset,
            c.sample_seg_len,
            c.xwb_bytes.len()
        ),
    );
    // Raw header: 5 segment descriptors from byte 12.
    let seg = |i: usize| {
        (
            read_u32(&c.xwb_bytes, 12 + i * 8) as usize,
            read_u32(&c.xwb_bytes, 12 + i * 8 + 4) as usize,
        )
    };
    ok &= check("segment0 = BANKDATA at 0x34, 96 B", seg(0) == (0x34, 96), format!("{:?}", seg(0)));
    ok &= check("segment1 = ENTRYMETA at 0x94, 24 B", seg(1) == (0x94, 24), format!("{:?}", seg(1)));
    ok &= check("segment2 = SEEKTABLES empty", seg(2).1 == 0, format!("{:?}", seg(2)));
    ok &= check("segment3 = ENTRYNAMES at 0xAC, 64 B", seg(3) == (0xAC, 64), format!("{:?}", seg(3)));
    ok &= check(
        "segment4 descriptor equals sample_seg_offset/len",
        seg(4) == (c.sample_seg_offset, c.sample_seg_len),
        format!("{:?} vs ({}, {})", seg(4), c.sample_seg_offset, c.sample_seg_len),
    );

    let bank = sib_container::parse(&c.xwb_bytes).expect("sibling parser accepts our XWB");
    ok &= check(
        "bank name = BANK_NAME",
        bank.name_str() == ours::BANK_NAME,
        bank.name_str().into(),
    );
    ok &= check("header_version = 42", bank.header_version == 42, bank.header_version.to_string());
    ok &= check(
        "flags = 0x00090000 (TYPE_BUFFER + ENTRYNAMES + bit 19)",
        bank.flags == 0x0009_0000,
        format!("0x{:08X}", bank.flags),
    );
    ok &= check("entry_name_element_size = 64", bank.entry_name_element_size == 64, bank.entry_name_element_size.to_string());
    ok &= check("alignment = 4", bank.alignment == 4, bank.alignment.to_string());
    ok &= check("compact_format = 0", bank.compact_format == 0, bank.compact_format.to_string());
    ok &= check("build_time = 0", bank.build_time == 0, bank.build_time.to_string());
    ok &= check("exactly one entry", bank.entries.len() == 1, bank.entries.len().to_string());

    let e = &bank.entries[0];
    ok &= check(
        "entry name = BANK_NAME",
        e.name_str() == ours::BANK_NAME,
        e.name_str().into(),
    );
    ok &= check("entry flags nibble = 0", e.flags_and_duration & 0xF == 0, format!("0x{:X}", e.flags_and_duration & 0xF));
    ok &= check("codec = 2 (MS-ADPCM)", e.format.codec() == 2, e.format.codec().to_string());
    ok &= check("channels = 1", e.format.channels() == 1, e.format.channels().to_string());
    ok &= check("sample_rate = 44100", e.format.sample_rate() == 44_100, e.format.sample_rate().to_string());
    ok &= check("block_align = 70", e.format.block_align() == 70, e.format.block_align().to_string());
    ok &= check("samples_per_block = 128", e.format.samples_per_block() == 128, e.format.samples_per_block().to_string());
    let duration = e.flags_and_duration >> 4;
    let blocks = e.data.len() / 70;
    ok &= check(
        "data is whole ADPCM blocks",
        blocks * 70 == e.data.len(),
        e.data.len().to_string(),
    );
    ok &= check(
        "declared duration = blocks * 128",
        duration as usize == blocks * 128,
        format!("{} vs {}", duration, blocks * 128),
    );
    ok &= check(
        "duration covers TICK_CAPACITY_MS",
        duration as u64 >= ours::TICK_CAPACITY_MS as u64 * ours::TICK_RATE_HZ as u64 / 1000,
        format!("{duration} samples"),
    );
    ok &= check(
        "duration >= loop_start + loop_length, loop covers entry",
        duration >= e.loop_start + e.loop_length && e.loop_start == 0 && e.loop_length == duration,
        format!("dur={} ls={} ll={}", duration, e.loop_start, e.loop_length),
    );

    // ── 4 + 5 + 6. Synthesis: sample-exact placement, port fidelity ─
    let clap_bytes = std::fs::read(CLAP_PCM).expect("read clap asset");
    let clap: Vec<i16> = clap_bytes
        .chunks_exact(2)
        .map(|c| i16::from_le_bytes([c[0], c[1]]))
        .collect();
    println!("clap: {} samples", clap.len());

    let pattern: Vec<i32> = (0..PATTERN_TICKS).map(|i| i * PATTERN_STEP_MS).collect();
    let s1 = ours::synthesize_track(&clap, &pattern);
    let s2 = ours::synthesize_track(&clap, &pattern);
    ok &= check("synthesis deterministic", s1.encoded == s2.encoded, String::new());
    ok &= check(
        "encoded length = sample_seg_len",
        s1.encoded.len() == c.sample_seg_len,
        format!("{} vs {}", s1.encoded.len(), c.sample_seg_len),
    );
    ok &= check(
        "pattern bookkeeping (mixed=40, clipped=0, dropped=0)",
        s1.mixed == 40 && s1.clipped == 0 && s1.dropped == 0,
        format!("mixed={} clipped={} dropped={}", s1.mixed, s1.clipped, s1.dropped),
    );

    // Port fidelity: rebuild the mix buffer here and encode it with the
    // SIBLING encoder — byte-identical output proves the mono port.
    let padded_samples = duration as usize;
    let mut mix = vec![0i16; padded_samples];
    for &ms in &pattern {
        let pos = ((ms as i64 * 44_100 + 500) / 1000) as usize;
        for (slot, &s) in mix[pos..].iter_mut().zip(clap.iter()) {
            *slot = (*slot as i32 + s as i32).clamp(-32768, 32767) as i16;
        }
    }
    let mono_fmt = WaveFormat::from_packed(2 | (1 << 2) | (44_100 << 5) | (48 << 23));
    let sib_encoded = sib_encode::encode(&mix, &mono_fmt).expect("sibling encode");
    let shared_mono_fmt = SharedWaveFormat::from_packed(
        2 | (1 << 2) | (44_100 << 5) | (48 << 23),
    );
    let shared_encoded = shared_adpcm::encode_interleaved(&mix, shared_mono_fmt)
        .expect("shared mono encode");
    ok &= check(
        "encoder byte-identical to sibling adpcm::encode",
        s1.encoded == sib_encoded,
        format!(
            "ours {} B vs sibling {} B, first diff at {:?}",
            s1.encoded.len(),
            sib_encoded.len(),
            s1.encoded.iter().zip(sib_encoded.iter()).position(|(a, b)| a != b)
        ),
    );
    ok &= check(
        "shared mono encoder byte-identical to Assist Tick and sibling",
        shared_encoded == s1.encoded && shared_encoded == sib_encoded,
        format!(
            "shared {} B, Assist Tick {} B, sibling {} B",
            shared_encoded.len(),
            s1.encoded.len(),
            sib_encoded.len()
        ),
    );
    let shared_silence = shared_adpcm::encode_interleaved(
        &[0; 128],
        shared_mono_fmt,
    )
    .expect("shared silence encode");
    ok &= check(
        "shared encoded silence block is byte-identical",
        shared_silence.as_slice() == synth::adpcm::silence_block(),
        String::new(),
    );

    let shared_stereo_fmt = SharedWaveFormat::from_packed(
        2 | (2 << 2) | (48_000 << 5) | (48 << 23),
    );
    let sibling_stereo_fmt = WaveFormat::from_packed(
        2 | (2 << 2) | (48_000 << 5) | (48 << 23),
    );
    let mut stereo = Vec::with_capacity(128 * 2);
    for frame in 0..128 {
        stereo.push((frame as i16).wrapping_mul(173));
        stereo.push((frame as i16).wrapping_mul(-211));
    }
    let shared_stereo = shared_adpcm::encode_interleaved(&stereo, shared_stereo_fmt)
        .expect("shared stereo encode");
    let sibling_stereo = sib_encode::encode(&stereo, &sibling_stereo_fmt)
        .expect("sibling stereo encode");
    ok &= check(
        "shared stereo encoder byte-identical to sibling",
        shared_stereo == sibling_stereo,
        format!(
            "shared {} B vs sibling {} B, first diff at {:?}",
            shared_stereo.len(),
            sibling_stereo.len(),
            shared_stereo
                .iter()
                .zip(sibling_stereo.iter())
                .position(|(a, b)| a != b)
        ),
    );
    let shared_stereo_pcm = shared_adpcm::decode_interleaved(
        &shared_stereo,
        shared_stereo_fmt,
        128,
    )
    .expect("shared stereo decode");
    let sibling_stereo_pcm = sib_decode::decode(&sibling_stereo, &sibling_stereo_fmt)
        .expect("sibling stereo decode");
    ok &= check(
        "shared stereo decoder byte-identical to sibling",
        shared_stereo_pcm == sibling_stereo_pcm,
        format!(
            "shared {} samples vs sibling {} samples, first diff at {:?}",
            shared_stereo_pcm.len(),
            sibling_stereo_pcm.len(),
            shared_stereo_pcm
                .iter()
                .zip(sibling_stereo_pcm.iter())
                .position(|(a, b)| a != b)
        ),
    );

    // Decode through the sibling decoder and verify each clap onset lands
    // sample-exactly: the cross-correlation of the decoded signal against the
    // clap must peak at lag 0 around every expected position.
    let decoded = sib_decode::decode(&s1.encoded, &mono_fmt).expect("sibling decode");
    ok &= check(
        "decoded length = declared duration",
        decoded.len() == padded_samples,
        format!("{} vs {}", decoded.len(), padded_samples),
    );
    let corr_window = 2048usize.min(clap.len());
    let mut worst_lag = 0i64;
    let mut onsets_ok = true;
    for &ms in &pattern {
        let pos = ((ms as i64 * 44_100 + 500) / 1000) as usize;
        let mut best_lag = 0i64;
        let mut best = i64::MIN;
        for lag in -5i64..=5 {
            let start = pos as i64 + lag;
            if start < 0 {
                continue;
            }
            let mut acc = 0i64;
            for k in 0..corr_window {
                let d = decoded[(start as usize) + k] as i64;
                let c = clap[k] as i64;
                acc += d * c;
            }
            if acc > best {
                best = acc;
                best_lag = lag;
            }
        }
        if best_lag != 0 {
            onsets_ok = false;
            if best_lag.abs() > worst_lag.abs() {
                worst_lag = best_lag;
            }
        }
    }
    ok &= check(
        "all 40 onsets sample-exact (correlation peak at lag 0)",
        onsets_ok,
        format!("worst lag {worst_lag} samples"),
    );

    // The tail past the pattern must be pure encoded silence.
    let tail_start = ((pattern[pattern.len() - 1] as i64 * 44_100 + 500) / 1000) as usize + clap.len() + 128;
    let tail_quiet = decoded[tail_start..].iter().all(|&s| s == 0);
    ok &= check("tail past the last clap decodes to exact silence", tail_quiet, String::new());

    // The pristine container's segment (encoded silence) must decode silent.
    let pristine = sib_decode::decode(&e.data, &mono_fmt).expect("decode pristine segment");
    ok &= check(
        "pristine (pre-rewrite) segment decodes to exact silence",
        pristine.iter().all(|&s| s == 0),
        String::new(),
    );

    // ── 7. Block-shift mechanism (the timeOffset-seek replacement) ───
    // Simulate rewrite_tick_wave's shifted copy host-side: content =
    // encoded[skip..] + repeated silence blocks; decode and confirm every
    // onset moved EARLIER by exactly the shifted block count's samples.
    {
        let shift_ms = 5_000i32;
        let skip = ours::shift_bytes_for_ms(shift_ms);
        ok &= check(
            "shift_bytes_for_ms(5000) is whole blocks, ~5 s",
            skip % 70 == 0 && {
                let blocks = skip / 70;
                let ms = blocks as f64 * 128.0 / 44.1;
                (ms - 5_000.0).abs() < 1.5
            },
            format!("{skip} bytes"),
        );
        ok &= check(
            "shift_bytes_for_ms clamps to the segment",
            ours::shift_bytes_for_ms(i32::MAX) == c.sample_seg_len
                && ours::shift_bytes_for_ms(0) == 0
                && ours::shift_bytes_for_ms(-100) == 0,
            String::new(),
        );

        let mut shifted = Vec::with_capacity(s1.encoded.len());
        shifted.extend_from_slice(&s1.encoded[skip..]);
        while shifted.len() < s1.encoded.len() {
            shifted.extend_from_slice(synth::adpcm::silence_block());
        }
        ok &= check(
            "shifted rewrite stays exactly segment-length",
            shifted.len() == s1.encoded.len(),
            format!("{} vs {}", shifted.len(), s1.encoded.len()),
        );
        let shift_samples = (skip / 70) * 128;
        let dec_shifted = sib_decode::decode(&shifted, &mono_fmt).expect("decode shifted");
        // Onsets 10.. of the pattern (5000 ms shift drops the first 10 at
        // 500 ms spacing... exactly on the boundary; clap 10 sits at ~0).
        let mut shifted_ok = true;
        let mut worst = 0i64;
        for &ms in pattern.iter().filter(|&&ms| {
            let pos = ((ms as i64 * 44_100 + 500) / 1000) as i64 - shift_samples as i64;
            pos >= 0
        }) {
            let pos = (((ms as i64 * 44_100 + 500) / 1000) - shift_samples as i64) as usize;
            let mut best_lag = 0i64;
            let mut best = i64::MIN;
            for lag in -5i64..=5 {
                let start = pos as i64 + lag;
                if start < 0 {
                    continue;
                }
                let mut acc = 0i64;
                for k in 0..corr_window {
                    acc += dec_shifted[(start as usize) + k] as i64 * clap[k] as i64;
                }
                if acc > best {
                    best = acc;
                    best_lag = lag;
                }
            }
            if best_lag != 0 {
                shifted_ok = false;
                if best_lag.abs() > worst.abs() {
                    worst = best_lag;
                }
            }
        }
        ok &= check(
            "shifted rewrite: surviving onsets land shift-exactly",
            shifted_ok,
            format!("worst lag {worst} samples"),
        );
    }

    // ── 8. Clip/drop bookkeeping ─────────────────────────────────────
    // Boundary vectors derived from the constant, never hardcoded: the last
    // in-capacity millisecond mixes, the capacity itself and anything past
    // it drop (the 1200 s truncation boundary — song-rate design req 31).
    let cap = ours::TICK_CAPACITY_MS as i32;
    let s3 = ours::synthesize_track(&clap, &[-100, 0, cap - 1, cap, cap + 100_000]);
    ok &= check(
        "clip/drop bookkeeping at the capacity boundary (mixed=3, clipped=1, dropped=2)",
        s3.mixed == 3 && s3.clipped == 1 && s3.dropped == 2,
        format!("mixed={} clipped={} dropped={}", s3.mixed, s3.clipped, s3.dropped),
    );

    println!();
    if ok {
        println!("ALL CHECKS PASSED");
    } else {
        println!("VALIDATION FAILED");
        std::process::exit(1);
    }
}
EOF

note "building + running the harness (host toolchain)"
( cd "$TMP" && cargo run --quiet )
