#!/usr/bin/env bash
# Offline validation for series_expansion's pure enhanced-layout model
# (src/mods/series_expansion/enhanced/model.rs): config validation, cell cap,
# 16->15 normalisation, group membership, table rows, label names and the
# thumbnail-bound policy.
#
# Usage:
#   ./scripts/validate_series_expansion.sh
#
# Why a harness: plain `cargo test` cannot run on non-x86 hosts (the `retour`
# dependency only compiles for x86/x86_64), so -- like
# validate_ddr_selection.sh -- this builds a throwaway HOST cargo crate in a
# temp directory that mounts the dependency-free model via `#[path]` and runs
# its `#[cfg(test)]` suite there.
#
# Requires: cargo (host toolchain). No game install, no Windows toolchain.
# Validation only -- writes nothing into the repository.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }

MODEL="src/mods/series_expansion/enhanced/model.rs"
[[ -r "$REPO_ROOT/$MODEL" ]] || die "module source missing: $MODEL"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<TOML
[package]
name = "series-expansion-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
serde_json = "1"

[workspace]
TOML

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness -- generated by"
  echo "//! scripts/validate_series_expansion.sh; never committed."
  echo "#![allow(dead_code)]"
  echo "#[path = \"$REPO_ROOT/$MODEL\"]"
  echo "pub mod model;"
} >"$TMP/src/lib.rs"

note "running pure model tests (model)"
(cd "$TMP" && cargo test --quiet -- --nocapture 2>&1 | grep -vE "^$")
note "OK"
