#!/usr/bin/env bash
# Offline validation for the Split SSQ Auto-Discovery pure resolver
# (`src/mods/split_ssq_auto_discovery/resolver.rs`; plan
# `.agents/planning/2026-09-03-split-ssq-auto-discovery/implementation/plan.md`).
#
# Usage:
#   ./scripts/validate_split_ssq.sh
#
# Why a harness: plain `cargo test` cannot run on non-x86 hosts (the `retour`
# dependency only compiles for x86/x86_64), so — like
# validate_judgement_offsets.sh — this builds a throwaway HOST cargo crate in
# a temp directory that mounts the feature's dependency-free modules via
# `#[path]` and runs their `#[cfg(test)]` suites there.
#
# Requires: cargo (host toolchain). Nothing else; no game install, no Windows
# toolchain. This script is validation only — it writes nothing into the
# repository.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }

# module name -> repo-relative source path. Names must be unique.
declare -a MODULE_NAMES=(split_ssq_resolver)
declare -a MODULE_PATHS=("src/mods/split_ssq_auto_discovery/resolver.rs")
# (`discovery.rs` is the impure host-fs layer and is NOT mounted; its pure
# listing filter lives in resolver.rs as `collect_split_candidates`.)

for p in "${MODULE_PATHS[@]}"; do
  [[ -r "$REPO_ROOT/$p" ]] || die "module source missing: $p"
done

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<EOF
[package]
name = "split-ssq-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[workspace]
EOF

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness — generated by"
  echo "//! scripts/validate_split_ssq.sh; never committed."
  echo "#![allow(dead_code)]"
  for i in "${!MODULE_NAMES[@]}"; do
    echo "#[path = \"$REPO_ROOT/${MODULE_PATHS[$i]}\"]"
    echo "pub mod ${MODULE_NAMES[$i]};"
  done
} >"$TMP/src/lib.rs"

note "running pure module tests (${MODULE_NAMES[*]})"
(cd "$TMP" && cargo test --quiet)
note "OK"
