#!/usr/bin/env bash
# Offline validation for the overlay-draw pure layers
# (`src/services/overlay_draw/` — the mod-menu rewrite's command-list record
# encoders; growing as later steps add pure modules).
#
# Usage:
#   ./scripts/validate_overlay_draw.sh
#
# Why a harness: plain `cargo test` cannot run on non-x86 hosts (the `retour`
# dependency only compiles for x86/x86_64), so — like
# validate_judgement_offsets.sh — this builds a throwaway HOST cargo crate in
# a temp directory that mounts the feature's dependency-free modules via
# `#[path]` and runs their `#[cfg(test)]` suites there.
#
# Requires: cargo (host toolchain). Nothing else; no game install, no Windows
# toolchain. This script is validation only — it writes nothing into the
# repository.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }

MOD_SRC="$REPO_ROOT/src/services/overlay_draw"
MODULES=(encode.rs)
for f in "${MODULES[@]}"; do
  [[ -r "$MOD_SRC/$f" ]] || die "module source missing: src/services/overlay_draw/$f"
done
# Pure shader-container layout module (lives beside the impure synthesis
# it feeds; dependency-free like everything mounted here).
LAYOUT_SRC="$REPO_ROOT/src/services/avs_layeredfs/shader_layout.rs"
[[ -r "$LAYOUT_SRC" ]] || die "module source missing: src/services/avs_layeredfs/shader_layout.rs"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<EOF
[package]
name = "overlay-draw-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[workspace]
EOF

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness — generated by"
  echo "//! scripts/validate_overlay_draw.sh; never committed."
  echo "#![allow(dead_code)]"
  for f in "${MODULES[@]}"; do
    name="${f%.rs}"
    echo "#[path = \"$MOD_SRC/$f\"]"
    echo "pub mod $name;"
  done
  echo "#[path = \"$LAYOUT_SRC\"]"
  echo "pub mod shader_layout;"
} >"$TMP/src/lib.rs"

note "running pure module tests (${MODULES[*]} shader_layout.rs)"
(cd "$TMP" && cargo test --quiet)
note "OK"
