#!/usr/bin/env bash
# Offline validation for the always-on software-identity rev override
# (`services/ident_override.rs`): its pure helpers — the soft-id composer,
# the libavs-ea3 rev validity rule, and the rev-sensitive stock-ident table
# that drives the boot WARN.
#
# Usage:
#   ./scripts/validate_ident_override.sh
#
# Why a harness: plain `cargo test` cannot run on non-x86 hosts (the `retour`
# dependency only compiles for x86/x86_64), so — like
# validate_two_player_bpl.sh — this builds a throwaway HOST cargo crate in a
# temp directory that mounts the module via `#[path]` and runs its
# `#[cfg(test)]` suite there. The module's engine-facing half (the ea3_boot
# detour + libavs property calls) is `#[cfg(windows)]` and stays
# cabinet-validated.
#
# Requires: cargo (host toolchain). Nothing else; no game install, no Windows
# toolchain. This script is validation only — it writes nothing into the
# repository.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }

declare -a MODULE_NAMES=(ident_override)
declare -a MODULE_PATHS=("src/services/ident_override.rs")

for p in "${MODULE_PATHS[@]}"; do
  [[ -r "$REPO_ROOT/$p" ]] || die "module source missing: $p"
done

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<EOF
[package]
name = "ident-override-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[workspace]
EOF

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness — generated by"
  echo "//! scripts/validate_ident_override.sh; never committed."
  echo "#![allow(dead_code)]"
  for i in "${!MODULE_NAMES[@]}"; do
    echo "#[path = \"$REPO_ROOT/${MODULE_PATHS[$i]}\"]"
    echo "pub mod ${MODULE_NAMES[$i]};"
  done
} >"$TMP/src/lib.rs"

note "running pure module tests (${MODULE_NAMES[*]})"
(cd "$TMP" && cargo test --quiet)
note "OK"
