#!/usr/bin/env bash
# Offline validation for the Per-Song Judgement Offsets pure layers
# (`src/mods/per_song_judgement_offsets/` — implementation plan Step 1's
# tests, growing as later steps add pure modules).
#
# Usage:
#   ./scripts/validate_judgement_offsets.sh
#
# Why a harness: plain `cargo test` cannot run on non-x86 hosts (the `retour`
# dependency only compiles for x86/x86_64), so — like
# validate_se_bank_synth.sh — this builds a throwaway HOST cargo crate in a
# temp directory that mounts the feature's dependency-free modules via
# `#[path]` and runs their `#[cfg(test)]` suites there.
#
# Requires: cargo (host toolchain). Nothing else; no game install, no Windows
# toolchain. This script is validation only — it writes nothing into the
# repository.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }

MOD_SRC="$REPO_ROOT/src/mods/per_song_judgement_offsets"
MODULES=(csv.rs musicdb_scan.rs)
# store.rs mounts here when Step 1 task 02 lands.
if [[ -r "$MOD_SRC/store.rs" ]]; then
  MODULES+=(store.rs)
fi
for f in "${MODULES[@]}"; do
  [[ -r "$MOD_SRC/$f" ]] || die "module source missing: src/mods/per_song_judgement_offsets/$f"
done

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<EOF
[package]
name = "judgement-offsets-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[workspace]
EOF

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness — generated by"
  echo "//! scripts/validate_judgement_offsets.sh; never committed."
  echo "#![allow(dead_code)]"
  for f in "${MODULES[@]}"; do
    name="${f%.rs}"
    echo "#[path = \"$MOD_SRC/$f\"]"
    echo "pub mod $name;"
  done
} >"$TMP/src/lib.rs"

note "running pure module tests (${MODULES[*]})"
if [[ -r "$REPO_ROOT/judgement_offsets.csv" ]]; then
  export JUDGEMENT_OFFSETS_CSV="$REPO_ROOT/judgement_offsets.csv"
  note "committed pre-seed CSV found — compatibility test armed"
fi
(cd "$TMP" && cargo test --quiet)
note "OK"
