#!/usr/bin/env bash
# Offline validation for the Background Dancers feature's pure layers.
#
# Usage:
#   ./scripts/validate_background_dancers.sh
#
# Why a harness: plain `cargo test` cannot run on non-x86 hosts (the `retour`
# dependency only compiles for x86/x86_64), so — like
# validate_two_player_bpl.sh — this builds a throwaway HOST cargo crate in a
# temp directory that mounts the feature's dependency-free modules via
# `#[path]` and runs their `#[cfg(test)]` suites there.
#
# Mounted modules grow with the plan steps:
#   Step 2  services/scene3d/pure.rs               (arc path resolution, FNV-1 model hash)
#   Step 3  services/scene3d/render_item_layout.rs (item/record/material layout + trailing math)
#           services/scene3d/node_layout.rs        (SceneNode offset_of pins, visible push)
#   Step 7  services/scene3d/frame_board.rs      (seqlocked pose channel game thread → visit(2))
#           mods/background_dancers/{director_math,clock,tempo}.rs (placement/clip-frame math, the song clock latch, the tempo-map dance clock)
#   Step 5  core/anm/mod.rs                        (ANM/CAMANM/B2IT/MRL0/KTMDL codecs — a DIRECTORY
#                                                    module: mount mod.rs, its children resolve beside it)
#   Step 6  mods/background_dancers/{selection,schedule}.rs (picks, playlists, dance/camera timelines;
#                                                    schedule reaches selection::Rng via `super::` — both
#                                                    mount at the crate root, as in the DLL's mod dir)
#   2026-09-21 mods/background_dancers/outline.rs   (scene-outline layer plan: INK / LAYERED widths + palette)
#   2026-09-21 services/scene3d/camera_math.rs      (the engine's LookAtRH view + D3D off-centre projection, row-vector)
#   2026-09-21 services/scene3d/viewport_pass_layout.rs (ClearViewport repr(C) pins, gd Clear record bytes, canvas→RT rect, prio/bit tables)
#   2026-09-21 mods/background_dancers/catalog.rs   (option-row catalog: sorted keys → ≤15-byte labels, load clamp;
#                                                    reaches selection::{StageCandidate,DancerCandidate} via `super::`)
#   2026-09-21 mods/background_dancers/pick.rs      (the Pick — optional stage / empty dancers, arc lists, summary line,
#                                                    ParseOptions; reaches selection via `super::`)
#   2026-09-21 mods/background_dancers/instance_plan.rs (the instance table: build order, slot base/budget, pass-mask
#                                                    override, hull twins; reaches selection::SHADOW_MODEL via `super::`)
#   2026-09-21 mods/background_dancers/preview/layout.rs (preview box geometry, per-side constants, crop / dancer /
#                                                    fallback frustum extents — std only)
#   2026-09-21 mods/background_dancers/preview/state.rs (the per-side focus / wanted / 150 ms settle / live machine)
#   2026-09-22 mods/background_dancers/custom_content.rs (custom dancers/stages from data_mods: arc-name classification,
#                                                    folder/key labels, text-rlist grammar, defaults, the planner;
#                                                    reaches selection + catalog via `super::`)
#
# Fixtures: the core/anm suite replays `tests/fixtures/anm/*.json` (generated by
# scripts/gen_anm_fixtures.py from the Python reference codecs) against the REAL
# stock arcs. That leg needs `DDR_WORLD_INSTALL` to point at a World install; it
# SKIPS with a note otherwise (the synthetic tests always run).
#
# Requires: cargo (host toolchain). No Windows toolchain.
# Validation only — writes nothing into the repository.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }

# module name -> repo-relative source path. Names must be unique. Only
# dependency-free modules can mount here (engine-facing files stay
# cabinet-validated).
declare -a MODULE_NAMES=(scene3d_pure scene3d_render_item_layout scene3d_node_layout scene3d_frame_board scene3d_camera_math scene3d_viewport_pass_layout anm selection schedule director_math clock tempo outline catalog pick instance_plan preview_layout preview_state custom_content)
declare -a MODULE_PATHS=(
  "src/services/scene3d/pure.rs"
  "src/services/scene3d/render_item_layout.rs"
  "src/services/scene3d/node_layout.rs"
  "src/services/scene3d/frame_board.rs"
  "src/services/scene3d/camera_math.rs"
  "src/services/scene3d/viewport_pass_layout.rs"
  "src/core/anm/mod.rs"
  "src/mods/background_dancers/selection.rs"
  "src/mods/background_dancers/schedule.rs"
  "src/mods/background_dancers/director_math.rs"
  "src/mods/background_dancers/clock.rs"
  "src/mods/background_dancers/tempo.rs"
  "src/mods/background_dancers/outline.rs"
  "src/mods/background_dancers/catalog.rs"
  "src/mods/background_dancers/pick.rs"
  "src/mods/background_dancers/instance_plan.rs"
  "src/mods/background_dancers/preview/layout.rs"
  "src/mods/background_dancers/preview/state.rs"
  "src/mods/background_dancers/custom_content.rs"
)

for p in "${MODULE_PATHS[@]}"; do
  [[ -r "$REPO_ROOT/$p" ]] || die "module source missing: $p"
done

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<EOF
[package]
name = "background-dancers-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

# Test-only: the core/anm fixture suite reads the Python-generated JSON.
[dependencies]
serde_json = "1"

[workspace]
EOF

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness — generated by"
  echo "//! scripts/validate_background_dancers.sh; never committed."
  echo "#![allow(dead_code)]"
  for i in "${!MODULE_NAMES[@]}"; do
    echo "#[path = \"$REPO_ROOT/${MODULE_PATHS[$i]}\"]"
    echo "pub mod ${MODULE_NAMES[$i]};"
  done
} >"$TMP/src/lib.rs"

export ANM_FIXTURE_DIR="$REPO_ROOT/tests/fixtures/anm"
if [[ -n "${DDR_WORLD_INSTALL:-}" && -d "${DDR_WORLD_INSTALL}/data/arc" ]]; then
  note "core/anm fixture leg: ON (DDR_WORLD_INSTALL set, fixtures in tests/fixtures/anm)"
else
  note "core/anm fixture leg: SKIPPED (DDR_WORLD_INSTALL unset or has no data/arc) -- synthetic tests only"
fi

note "running pure module tests (${MODULE_NAMES[*]})"
(cd "$TMP" && cargo test --quiet)
note "OK"
