#!/usr/bin/env bash
# Offline validation for the ultrafast-boot pure layers
# (`src/mods/fast_bootup/` — implementation plan Step 1's tests, growing as
# later steps add pure modules).
#
# Usage:
#   ./scripts/validate_fast_bootup.sh
#
# Why a harness: plain `cargo test` cannot run on non-x86 hosts (the `retour`
# dependency only compiles for x86/x86_64), so — like
# validate_judgement_offsets.sh — this builds a throwaway HOST cargo crate in
# a temp directory that mounts the feature's dependency-free modules via
# `#[path]` and runs their `#[cfg(test)]` suites there.
#
# Requires: cargo (host toolchain). Nothing else; no game install, no Windows
# toolchain. This script is validation only — it writes nothing into the
# repository.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }

MOD_SRC="$REPO_ROOT/src/mods/fast_bootup"
MODULES=(cache.rs)
# Later Step 1 tasks mount here as they land.
for optional in replay.rs plan.rs; do
  if [[ -r "$MOD_SRC/$optional" ]]; then
    MODULES+=("$optional")
  fi
done
for f in "${MODULES[@]}"; do
  [[ -r "$MOD_SRC/$f" ]] || die "module source missing: src/mods/fast_bootup/$f"
done

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<EOF
[package]
name = "fast-bootup-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[workspace]
EOF

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness — generated by"
  echo "//! scripts/validate_fast_bootup.sh; never committed."
  echo "#![allow(dead_code)]"
  for f in "${MODULES[@]}"; do
    name="${f%.rs}"
    echo "#[path = \"$MOD_SRC/$f\"]"
    echo "pub mod $name;"
  done
} >"$TMP/src/lib.rs"

note "running pure module tests (${MODULES[*]})"
(cd "$TMP" && cargo test --quiet)
note "OK"
