#!/usr/bin/env bash
# Offline validation for DDR SELECTION's pure layers (src/mods/ddr_selection/:
# the package policy table, the trigger, the legacy-intro state machine, the
# legacy stage-panel rules + state machine, the end-banner rules + overlay
# machine, the `_sel` movie rules and the era-bank builder today; the option-forcing table,
# HUD math, era-bank builder and announcer rules join as their steps land).
#
# Usage:
#   ./scripts/validate_ddr_selection.sh
#
# Why a harness: plain `cargo test` cannot run on non-x86 hosts (the `retour`
# dependency only compiles for x86/x86_64), so — like
# validate_two_player_bpl.sh — this builds a throwaway HOST cargo crate in a
# temp directory that mounts the feature's dependency-free modules via
# `#[path]` and runs their `#[cfg(test)]` suites there.
#
# Requires: cargo (host toolchain). No game install, no Windows toolchain.
# Validation only — writes nothing into the repository.

set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

die() { echo "error: $*" >&2; exit 1; }
note() { echo "[*] $*"; }

# Top-level modules: name -> repo-relative path. Only dependency-free
# modules (no `crate::` imports) can mount here.
declare -a MODULE_NAMES=(policy trigger intro_logic panel_logic banner_logic sel_movie_logic marker_keys gauge_math combo_math score_math song_info_logic)
declare -a MODULE_PATHS=(
  "src/mods/ddr_selection/policy.rs"
  "src/mods/ddr_selection/trigger.rs"
  "src/mods/ddr_selection/intro_logic.rs"
  "src/mods/ddr_selection/panel_logic.rs"
  "src/mods/ddr_selection/banner_logic.rs"
  "src/mods/ddr_selection/sel_movie_logic.rs"
  "src/mods/ddr_selection/marker_keys.rs"
  "src/mods/ddr_selection/gauge_math.rs"
  "src/mods/ddr_selection/combo_math.rs"
  "src/mods/ddr_selection/score_math.rs"
  "src/mods/ddr_selection/song_info_logic.rs"
)
# Modules nested under `sound` (they reference each other via `super::`).
declare -a SOUND_NAMES=(cues bank_build rules)
declare -a SOUND_PATHS=(
  "src/mods/ddr_selection/sound/cues.rs"
  "src/mods/ddr_selection/sound/bank_build.rs"
  "src/mods/ddr_selection/sound/rules.rs"
)

for p in "${MODULE_PATHS[@]}" "${SOUND_PATHS[@]}"; do
  [[ -r "$REPO_ROOT/$p" ]] || die "module source missing: $p"
done

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
note "harness dir: $TMP"

cat >"$TMP/Cargo.toml" <<TOML
[package]
name = "ddr-selection-validate"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[workspace]
TOML

mkdir -p "$TMP/src"
{
  echo "//! Throwaway offline-validation harness — generated by"
  echo "//! scripts/validate_ddr_selection.sh; never committed."
  echo "#![allow(dead_code)]"
  for i in "${!MODULE_NAMES[@]}"; do
    echo "#[path = \"$REPO_ROOT/${MODULE_PATHS[$i]}\"]"
    echo "pub mod ${MODULE_NAMES[$i]};"
  done
  echo "pub mod sound {"
  for i in "${!SOUND_NAMES[@]}"; do
    echo "    #[path = \"$REPO_ROOT/${SOUND_PATHS[$i]}\"]"
    echo "    pub mod ${SOUND_NAMES[$i]};"
  done
  echo "}"
} >"$TMP/src/lib.rs"

# Real-bank leg: extract the A3-generation `_n` banks World ships into the
# temp dir (needs $DDR_WORLD_INSTALL; skipped otherwise).
if [[ -n "${DDR_WORLD_INSTALL:-}" && -f "$DDR_WORLD_INSTALL/data/arc/soundbanks_n.arc" ]]; then
  note "extracting the _n banks from \$DDR_WORLD_INSTALL for the real-bank leg"
  B="$TMP/banks"
  mkdir -p "$B/x"
  python3 "$REPO_ROOT/scripts/unpack_arc.py" -o "$B/x" "$DDR_WORLD_INSTALL/data/arc/soundbanks_n.arc" >/dev/null
  python3 "$REPO_ROOT/scripts/unpack_arc.py" -o "$B/x" "$DDR_WORLD_INSTALL/data/arc/se_normal_n.arc" >/dev/null
  for f in voice_n.xsb se_normal_n.xsb se_normal_n.xwb; do
    found=$(find "$B/x" -name "$f" | head -1)
    [[ -n "$found" ]] || die "could not extract $f"
    cp "$found" "$B/$f"
  done
  cp "$DDR_WORLD_INSTALL/data/sound/win/voice_n.xwb" "$B/voice_n.xwb"
  export DDR_SEL_BANK_DIR="$B"
else
  note "DDR_WORLD_INSTALL unset -- real-bank leg skipped"
fi

note "running pure module tests (${MODULE_NAMES[*]} sound::{${SOUND_NAMES[*]}})"
(cd "$TMP" && cargo test --quiet -- --nocapture 2>&1 | grep -vE "^$")
note "OK"
