//! Improved Song Title Sorting (`improved-song-title-sorting`, default ON) —
//! reworks the song-select FILTER overlay's MUSIC TITLE menu so every
//! English letter is its own filter.
//!
//! Stock groups the letters three to a cell (`A,B,C` … `Y,Z`) after the ten
//! kana lines. This mod lays the menu out as:
//!
//! ```text
//! A | B | C | D | E        42-px cells (template 5), five per row
//! F … J / K … O / P … T / U … Y
//! Z | OTHER                OTHER at the 108-px template 2
//! ───────────────          invisible 1-px row break (stock FilterHeader)
//! ア | カ | サ | タ        stock kana lines, stock art, 54-px template 4
//! ナ | ハ | マ | ヤ
//! ラ | ワ
//! ```
//!
//! Nine rows — inside the item grid's ten visible rows, so no scrolling.
//! Layout, table and label names live in [`layout`] (pure, host-tested by
//! `scripts/validate_improved_song_title_sorting.sh`).
//!
//! ## Mechanism
//!
//! Every site comes from `SignatureStore::title_filter_sites`
//! (`derive_title_filter`, verified on every supported build; any miss ⇒ the
//! mod is not registered and the stock menu stays):
//!
//! - **Owned detour:** the MUSIC TITLE builder body ([`hooks`]). It asks the
//!   builder's own factory for one button per item — selection index = the
//!   stock title class (`ChartMetadata+0x88`: 0..=9 kana lines, 10..=35 A..Z,
//!   36 other; the game's classifier is untouched) — sets each button's
//!   template and label key, and constructs a stock `FilterHeader` row break
//!   between OTHER and the kana lines (without it the first kana cell fits on
//!   Z's row). Passes through unless the mod is enabled.
//! - **Table:** a near-allocated 38-row identity range table (row `i` starts
//!   at class `i`, plus the sentinel), so the stock predicate's
//!   `start(i) <= class < start(i + 1)` matches exactly one class. The
//!   predicate's and the chip summary's table LEAs point at it and the
//!   summary's count becomes 37: the chip reads `TITLE A～C` / `TITLE あ～お`
//!   from the rows' first/last labels (runs merge by adjacent selection
//!   index, as stock).
//! - **Persistence:** `services::filter_entry_count` reports 37 for MUSIC
//!   TITLE (category 0), so every selection round-trips through the saved
//!   `filtersort/title` u64. Saved kana-line bits keep their meaning; stock
//!   bits 10..=19 (the letter groups and OTHER) come back as A..J once.
//! - **Labels** ([`labels`]): `sefi_title_<a..z>_5col` (32×20) and
//!   `sefi_title_other_2col` (104×20) from
//!   `data_mods/improved_song_title_sorting/title_labels/` (generated by
//!   `scripts/gen_title_labels.py`), pre-converted into LayeredFS per-image
//!   cache blobs and declared through this mod folder's own merged
//!   texturelist. Prepared at `init` whatever the toggle, so the declarations
//!   and the blobs they name never disagree.
//!
//! ## Degradation
//!
//! Byte patches are checked (expected bytes verified, rolled back on
//! failure) and restored in reverse on `disable`. A detour or patch failure
//! at `enable` leaves the stock menu (`is_active` false). A missing label PNG
//! ⇒ one WARN and that cell has no label. Disabled at runtime while a letter
//! past `J` or OTHER is selected, the stock predicate reads those indices
//! past its own 21-row table (in-bounds `.data`, wrong matches) until the
//! player clears the filter — the same trade-off as series_expansion.
//!
//! RE notes: `docs/filter_menu_system_research.md` (§5.1 MUSIC TITLE, §3.4
//! row breaks, §16 this mod).

mod hooks;
mod labels;
pub mod layout;

use crate::core::memory;
use crate::core::signatures::TitleFilterSites;
use crate::mods::mod_trait::{Mod, ModContext};
use crate::services::filter_entry_count;
use crate::{log_info, log_warn};

/// Filtersort category of MUSIC TITLE (its saved bitfield is `title`).
const TITLE_FILTER_CATEGORY: u32 = 0;
/// Stock MUSIC TITLE item count (the summary's `MOV EDX,20`).
const STOCK_COUNT: u32 = 20;

/// One code patch: `patched` replaces `original` at `addr`.
struct SavedPatch {
    addr: *mut u8,
    original: Vec<u8>,
    patched: Vec<u8>,
}

impl SavedPatch {
    fn apply(&self) -> bool {
        unsafe { memory::apply_checked_patch(self.addr, &self.original, &self.patched).is_ok() }
    }
    fn restore(&self) -> bool {
        unsafe { memory::apply_checked_patch(self.addr, &self.patched, &self.original).is_ok() }
    }
}

/// `disp32` of a RIP-relative instruction at `instr` (`len` bytes) that
/// should reach `target`, or `None` if out of range.
fn rip_disp(instr: *const u8, len: usize, target: *const u8) -> Option<i32> {
    let next = instr as isize + len as isize;
    i32::try_from(target as isize - next).ok()
}

pub struct ImprovedSongTitleSortingMod {
    sites: Option<TitleFilterSites>,
    /// Near-allocated replacement table (never freed: the game's summary
    /// `std::function`s capture its address).
    table: *mut u8,
    /// Predicate LEA, summary LEA, summary count — applied in order,
    /// restored in reverse.
    patches: Vec<SavedPatch>,
    active: bool,
}

// Raw pointers into the game module / our never-freed table.
unsafe impl Send for ImprovedSongTitleSortingMod {}

impl ImprovedSongTitleSortingMod {
    pub fn new() -> Self {
        Self {
            sites: None,
            table: std::ptr::null_mut(),
            patches: Vec::new(),
            active: false,
        }
    }

    /// Allocate and fill the identity range table. `None` on failure.
    fn build_table(module_base: *const u8) -> Option<*mut u8> {
        let rows = layout::table_rows();
        let table = unsafe { memory::alloc_near(module_base, rows.len() * layout::ENTRY_STRIDE) };
        if table.is_null() {
            return None;
        }
        for (i, row) in rows.iter().enumerate() {
            let bytes = layout::encode_row(row)?;
            unsafe {
                std::ptr::copy_nonoverlapping(
                    bytes.as_ptr(),
                    table.add(i * layout::ENTRY_STRIDE),
                    layout::ENTRY_STRIDE,
                );
            }
        }
        Some(table)
    }

    /// The three code patches, with their current bytes verified as stock
    /// (both LEAs load the stock table, the count is 20).
    fn plan_patches(sites: &TitleFilterSites, table: *const u8) -> Option<Vec<SavedPatch>> {
        let mut out = Vec::new();
        for lea in [sites.predicate_lea, sites.summary_table_lea] {
            let disp_addr = unsafe { lea.add(3) } as *mut u8;
            let current = unsafe { crate::core::scanner::decode_rip_relative(disp_addr) };
            if current != sites.table {
                log_warn!(
                    "ImprovedTitleSorting: table LEA at {:p} no longer loads the stock table",
                    lea
                );
                return None;
            }
            let disp = rip_disp(lea, 7, table)?;
            out.push(SavedPatch {
                addr: disp_addr,
                original: unsafe { std::slice::from_raw_parts(disp_addr, 4) }.to_vec(),
                patched: disp.to_le_bytes().to_vec(),
            });
        }
        out.push(SavedPatch {
            addr: sites.summary_count as *mut u8,
            original: STOCK_COUNT.to_le_bytes().to_vec(),
            patched: layout::CLASS_COUNT.to_le_bytes().to_vec(),
        });
        Some(out)
    }

    /// Undo whatever `enable` applied (reverse order).
    fn rollback(&mut self, applied: usize) {
        hooks::set_active(false);
        for patch in self.patches.iter().take(applied).rev() {
            if !patch.restore() {
                log_warn!(
                    "ImprovedTitleSorting: could not restore the patch at {:p}",
                    patch.addr
                );
            }
        }
        filter_entry_count::clear_override(TITLE_FILTER_CATEGORY);
    }
}

impl Mod for ImprovedSongTitleSortingMod {
    fn id(&self) -> &str {
        "improved-song-title-sorting"
    }
    fn name(&self) -> &str {
        "Improved Song Title Sorting"
    }
    fn description(&self) -> &str {
        "MUSIC TITLE filter with one entry per letter"
    }
    fn required_signatures(&self) -> &[&str] {
        &[
            "title_builder_loop",
            "title_predicate",
            "title_label_builder_count",
            "filter_header_alloc",
        ]
    }

    fn init(&mut self, ctx: &ModContext) -> bool {
        let Some(sites) = ctx.signatures.title_filter_sites() else {
            log_warn!("ImprovedTitleSorting: MUSIC TITLE sites unresolved on this build");
            return false;
        };
        let Some(table) = Self::build_table(ctx.game_module.base) else {
            log_warn!("ImprovedTitleSorting: failed to build the filter table");
            return false;
        };
        let Some(patches) = Self::plan_patches(&sites, table) else {
            log_warn!("ImprovedTitleSorting: MUSIC TITLE code differs from stock — mod disabled");
            return false;
        };
        let declared = labels::prepare();
        log_info!(
            "ImprovedTitleSorting: initialized — builder {:p}, table {:p} ({} rows), {} label(s)",
            sites.builder,
            table,
            layout::CLASS_COUNT + 1,
            declared
        );
        self.sites = Some(sites);
        self.table = table;
        self.patches = patches;
        true
    }

    fn enable(&mut self) {
        if self.active {
            return;
        }
        let Some(sites) = self.sites else {
            return;
        };
        // Detour first (pass-through until active), then the patches, the
        // count override and finally the active flag.
        let installed = unsafe {
            let runtime = hooks::Runtime::new(&sites, layout::items());
            hooks::install(&sites, runtime)
        };
        if !installed {
            log_warn!("ImprovedTitleSorting: detour unavailable — MUSIC TITLE menu left stock");
            return;
        }
        for (i, patch) in self.patches.iter().enumerate() {
            if !patch.apply() {
                log_warn!(
                    "ImprovedTitleSorting: patch at {:p} failed — MUSIC TITLE menu left stock",
                    patch.addr
                );
                self.rollback(i);
                return;
            }
        }
        if !filter_entry_count::set_override(TITLE_FILTER_CATEGORY, layout::CLASS_COUNT) {
            log_warn!(
                "ImprovedTitleSorting: entry-count override unavailable — letters past J and OTHER won't be remembered"
            );
        }
        hooks::set_active(true);
        self.active = true;
        log_info!(
            "ImprovedTitleSorting: enabled — {} patches, {} items",
            self.patches.len(),
            layout::CLASS_COUNT
        );
    }

    fn disable(&mut self) {
        if !self.active {
            return;
        }
        let applied = self.patches.len();
        self.rollback(applied);
        self.active = false;
        log_info!("ImprovedTitleSorting: disabled");
    }

    fn is_active(&self) -> bool {
        self.active
    }
}
